Repository LLNL/lbann, pull requests merged in 2018-02, with the labels that each got.

#209 Aluminum build system integration
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/FindALUMINUM.cmake
  scripts/build_lbann_lc.sh
  superbuild/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: review requested

#210 Weighted sums in sum layer
  include/lbann/layers/transform/sum.hpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement

#218 Parallelizing CPU-GPU memory transfers.
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/resnet50/model_resnet50.prototext
  src/utils/cudnn_wrapper.cpp
Labels: enhancement

#219 Checkpoint bug fix
  include/lbann/callbacks/callback_checkpoint.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/io/persist.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/target/generic_target_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/models/model.hpp
  include/lbann/models/sequential.hpp
  include/lbann/utils/random.hpp
  src/callbacks/callback_checkpoint.cpp
  src/data_readers/data_reader.cpp
  src/io/file_io.cpp
  src/io/persist.cpp
  src/layers/layer.cpp
  src/metrics/metric.cpp
  src/models/model.cpp
  src/models/sequential.cpp
  src/utils/random.cpp
Labels: bug, in progress, review requested

#220 Optimizer refactor
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  include/lbann/utils/cudnn_wrapper.hpp
  src/callbacks/callback_imcomm.cpp
  src/layers/learning/fully_connected.cpp
  src/objective_functions/weight_regularization/l2.cpp
  src/optimizers/adagrad.cpp
  src/optimizers/adam.cpp
  src/optimizers/adam.cu
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/optimizer.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/sgd.cpp
  src/optimizers/sgd.cu
  src/utils/cudnn_wrapper.cpp
Labels: review requested

#222 Bamboo prototext updates to comply with refactored IO layers.
  bamboo/unit_tests/prototext/model_mnist_simple_1.prototext
  bamboo/unit_tests/prototext/model_mnist_simple_2.prototext
Labels: bug

#224 Improve comm/comp overlap in convolution
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  src/optimizers/optimizer.cpp
Labels: bug, enhancement, review requested

#226 Emergency bugfixes
  include/lbann/layers/transform/concatenation.hpp
  src/callbacks/callback_gradient_check.cpp
  src/layers/layer.cpp
  src/optimizers/optimizer.cpp
Labels: bug

#229 Miscellaneous bugfixes for VAEs
  include/lbann/layers/activations/relu.hpp
  include/lbann/layers/activations/sigmoid.hpp
  include/lbann/layers/transform/noise.hpp
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  src/layers/activations/CMakeLists.txt
  src/layers/activations/sigmoid.cu
  src/objective_functions/kl_divergence.cpp
  src/proto/proto_common.cpp
Labels: bug, enhancement

#230 removing use_cudnn and replacing with disable_cuda, which defaults to…
  bamboo/unit_tests/prototext/model_mnist_simple_1.prototext
  bamboo/unit_tests/prototext/model_mnist_simple_2.prototext
  model_zoo/lbann.cpp
  model_zoo/lbann2.cpp
  model_zoo/models/alexnet/data.prototext
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_200x150x100x100x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_500x250x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_sigmoid.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_dnn_chem_ecfp.prototext
  model_zoo/models/autoencoder_cifar10/model_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_imagenet/model_conv_autoencoder_imagenet.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/model_conv_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  model_zoo/models/char_rnn/model_char_rnn.prototext
  model_zoo/models/greedy_layerwise_autoencoder_mnist/model_greedy_layerwise_autoencoder_mnist.prototext
  model_zoo/models/imagenet/model_imagenet.prototext
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_bead_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_molecular_autoencoder_pilot2.prototext
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/models/resnet50/model_resnet50_motif.prototext
  model_zoo/models/resnet50/model_resnet50_sequential.prototext
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/siamese_alexnet/model_siamese_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_1.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_2.prototext
  model_zoo/tests/model_lenet_mnist_ckpt.prototext
  model_zoo/tests/model_mnist_distributed_io.prototext
  model_zoo/tests/model_mnist_partitioned_io.prototext
  model_zoo/tests/model_mnist_resnet.prototext
  model_zoo/tests/model_mnist_ridge_regression.prototext
  model_zoo/tests/model_mnist_softmax_regression.prototext
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: review requested

#212 To remove swap_role()
  include/lbann/data_readers/compound_data_reader.hpp
  include/lbann/data_readers/data_reader.hpp
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#208 fix the absolute sample count feature of the data reader
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
Labels: bug, review requested

#227 Mesh reader
  include/lbann/data_readers/data_reader_mesh.hpp
  include/lbann/lbann.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_mesh.cpp
  src/proto/proto_common.cpp
Labels: enhancement
