Repository LLNL/lbann, pull requests merged in 2018-08, with the labels that each got.

#561 update data_reader_jag_conduit.prototext to reflect the recent changes
  model_zoo/models/jag/data_reader_jag_conduit.prototext
Labels: refactor

#553 Update jpeg-turbo and protobuf to use cmake in superbuild
  cmake/modules/SetupProtobuf.cmake
  src/proto/CMakeLists.txt
  superbuild/jpeg-turbo/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
  superbuild/protobuf/CMakeLists.txt
Labels: review requested

#559 conduit hdf5 reader
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit_hdf5.hpp
  include/lbann/data_store/jag_store.hpp
  include/lbann/lbann.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit_hdf5.cpp
  src/data_store/CMakeLists.txt
  src/data_store/jag_converter.cpp
  src/data_store/jag_store.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
Labels: enhancement, in progress

#560 Manually setting thread affinity on Pascal.
  experiments/run_lbann_experiment.sh
Labels: bug, review requested

#563 Signal handler conforms to POSIX C standard.
  include/lbann/utils/stack_trace.hpp
  model_zoo/lbann.cpp
  src/utils/stack_trace.cpp
Labels: enhancement

#564 Mean squared error layer and GPU abs layer
  include/lbann/layers/activations/abs.hpp
  include/lbann/layers/loss/CMakeLists.txt
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/cuda.hpp
  model_zoo/tests/model_mnist_ridge_regression.prototext
  src/layers/activations/CMakeLists.txt
  src/layers/layer.cpp
  src/layers/loss/CMakeLists.txt
  src/layers/loss/mean_squared_error.cpp
  src/layers/loss/mean_squared_error.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#557 Weights refactor
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/random.hpp
  include/lbann/weights/CMakeLists.txt
  include/lbann/weights/fan_in_fan_out_initializers.hpp
  include/lbann/weights/initializer.hpp
  include/lbann/weights/variance_scaling_initializers.hpp
  include/lbann/weights/weights.hpp
  src/layers/layer.cpp
  src/models/model.cpp
  src/proto/factories/weights_factory.cpp
  src/weights/CMakeLists.txt
  src/weights/fan_in_fan_out_initializers.cpp
  src/weights/initializer.cpp
  src/weights/variance_scaling_initializers.cpp
  src/weights/weights.cpp
Labels: bug, refactor, review requested

#570 Fix build failure on Surface
  experiments/run_lbann_experiment.sh
  scripts/build_lbann_lc.sh
Labels: bug, build, question, review requested

#494 Compiler test update -- Pascal
  bamboo/common_python/tools.py
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/conftest.py
  bamboo/unit_tests/conftest.py
  scripts/spack_recipes/build_lbann.sh
Labels: in progress

#577 Removing deprecated repeated_input_layer.
  include/lbann/layers/io/input/CMakeLists.txt
  include/lbann/layers/io/input/repeated_input_layer.hpp
  include/lbann/lbann.hpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: refactor

#576 fix jag_store macro check on conduit existence
  include/lbann/data_store/jag_store.hpp
  src/data_store/jag_store.cpp
Labels: bug

#575 Use the exported conduit targets in the FindCONDUIT module
  cmake/modules/FindCONDUIT.cmake
Labels: bug, build

#581 Update profiling annotations
  include/lbann/callbacks/profiler.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/profiling.hpp
  src/callbacks/callback_summary.cpp
  src/callbacks/profiler.cpp
  src/utils/CMakeLists.txt
  src/utils/profiling.cpp
Labels: enhancement, review requested

#574 Reconcile redundant weight values after each epoch
  include/lbann/models/model.hpp
  include/lbann/weights/weights.hpp
  src/models/model.cpp
  src/weights/weights.cpp
Labels: bug, review requested

#582 Sort layer
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/sort.hpp
  include/lbann/lbann.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/sort.cpp
  src/layers/transform/sort.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#589 Remove redundant gradient clearing
  src/optimizers/optimizer.cpp
Labels: enhancement, review requested

#591 Update CUDA, NCCL, cuDNN versions
  scripts/build_lbann_lc.sh
Labels: enhancement, review requested

#592 Pinned memory for CPU activations
  src/layers/layer.cpp
Labels: enhancement, review requested

#593 Batch norm prints a warning if mini-batch is too small.
  include/lbann/layers/regularizers/batch_normalization.hpp
Labels: enhancement

#597 Strange bugfix for #586.
  include/lbann/comm.hpp
Labels: bug, review requested

#599 Experiment script uses workarounds for MVAPICH bugs.
  experiments/run_lbann_experiment.sh
Labels: bug

#600 Bugfix for relatively small fully-connected layers
  src/comm.cpp
  src/objective_functions/weight_regularization/l2.cpp
Labels: bug, review requested
