Repository LLNL/lbann, pull requests merged in 2018-10, with the labels that each got.

#631 Binary math layers
  ReleaseNotes.txt
  include/lbann/layers/activations/CMakeLists.txt
  include/lbann/layers/activations/power.hpp
  include/lbann/layers/math/CMakeLists.txt
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/math/unary.hpp
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/max.hpp
  include/lbann/layers/transform/min.hpp
  include/lbann/lbann.hpp
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  model_zoo/models/jag/vae_fcn.prototext
  src/layers/math/CMakeLists.txt
  src/layers/math/binary.cpp
  src/layers/math/binary.cu
  src/layers/math/unary.cpp
  src/layers/math/unary.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#636 Allow disabling OpenMP parallelism for data fetch loop
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/utils/omp_pragma.hpp
  scripts/build_lbann_lc.sh
  src/data_readers/data_reader.cpp
Labels: enhancement, review requested

#548 Added an optimization to use an asynchronous copy from the previous
  include/lbann/layers/layer.hpp
  src/layers/layer.cpp
Labels: enhancement, in progress

#543 Added a thread safe set of buffers for OpenCV decoding in the image
  include/lbann/data_readers/cv_utils.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_readers/image_utils.hpp
  src/data_readers/cv_utils.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_readers/data_reader_imagenet_patches.cpp
  src/data_readers/data_reader_multi_images.cpp
  src/data_readers/data_reader_triplet.cpp
  src/data_readers/image_utils.cpp
Labels: enhancement

#644 Synthetic responses
  include/lbann/data_readers/data_reader_synthetic.hpp
  src/data_readers/data_reader_synthetic.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement

#638 Safe reciprocal and safe divide layers
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/math/unary.hpp
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/safe_inv.hpp
  include/lbann/lbann.hpp
  src/layers/math/binary.cpp
  src/layers/math/binary.cu
  src/layers/math/unary.cpp
  src/layers/math/unary.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#648 add the DAG version of the siamese model prototext and
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
Labels: enhancement, review requested

#646 Save image callback can accommodate any layer.
  include/lbann/callbacks/callback_save_images.hpp
  model_zoo/models/autoencoder_cifar10/model_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_imagenet/model_conv_autoencoder_imagenet.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/model_conv_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/greedy_layerwise_autoencoder_mnist/model_greedy_layerwise_autoencoder_mnist.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  model_zoo/models/jag/vae_fcn.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_bead_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_molecular_autoencoder_pilot2.prototext
  src/callbacks/callback_save_images.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#656 Use H Al communicators
  include/lbann/comm.hpp
  src/comm.cpp
Labels: enhancement

#598 Refresh jag conduit
  include/lbann/comm.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/io/data_buffers/distributed_io_buffer.hpp
  include/lbann/io/data_buffers/partitioned_io_buffer.hpp
  include/lbann/proto/proto_common.hpp
  model_zoo/models/jag/cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  model_zoo/models/jag/input.minmax.1M.txt
  model_zoo/models/jag/scalar.minmax.1M.txt
  src/data_readers/data_reader_jag.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  tools/compute_mean/Mat.hpp
  tools/compute_mean/lbann/utils/glob.hpp
  tools/compute_mean/lbann/utils/omp_pragma.hpp
  tools/compute_mean/lbann/utils/peek_map.hpp
  tools/compute_mean/lbann/utils/timer.hpp
Labels: bug, enhancement, review requested

#664 Refactoring CUDA utility header
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/cuda.hpp
  include/lbann/utils/impl/CMakeLists.txt
  include/lbann/utils/impl/cuda.hpp
  src/layers/activations/sigmoid.cu
  src/layers/image/bilinear_resize.cu
  src/layers/loss/cross_entropy.cu
  src/layers/loss/entrywise.cu
  src/layers/math/binary.cu
  src/layers/math/unary.cpp
  src/layers/math/unary.cu
  src/layers/regularizers/batch_normalization.cu
  src/optimizers/adagrad.cu
  src/utils/cuda.cu
Labels: refactor

#660 Variance and covariance layers
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_l2_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_variance.py
  include/lbann/layers/CMakeLists.txt
  include/lbann/layers/misc/CMakeLists.txt
  include/lbann/layers/misc/covariance.hpp
  include/lbann/layers/misc/variance.hpp
  include/lbann/lbann.hpp
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
  src/layers/misc/CMakeLists.txt
  src/layers/misc/covariance.cpp
  src/layers/misc/covariance.cu
  src/layers/misc/variance.cpp
  src/layers/misc/variance.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#666 Categorical accuracy layer
  ReleaseNotes.txt
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/cuda.hpp
  include/lbann/utils/impl/cuda.hpp
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/models/vram/generate_dram.py
  model_zoo/tests/model_mnist_softmax_classifier.prototext
  src/layers/loss/CMakeLists.txt
  src/layers/loss/categorical_accuracy.cpp
  src/layers/loss/categorical_accuracy.cu
  src/layers/loss/top_k_categorical_accuracy.cu
  src/layers/transform/in_top_k.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#665 Reverting #548.
  include/lbann/layers/layer.hpp
  src/layers/layer.cpp
Labels: bug

#667 Remove deprecated functionality in model zoo prototexts
  model_zoo/models/alexnet/data.prototext
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/autoencoder_cifar10/model_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_imagenet/model_conv_autoencoder_imagenet.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/model_conv_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  model_zoo/models/char_rnn/char_lstm.prototext
  model_zoo/models/char_rnn/char_rnn.prototext
  model_zoo/models/greedy_layerwise_autoencoder_mnist/model_greedy_layerwise_autoencoder_mnist.prototext
  model_zoo/models/greedy_layerwise_autoencoder_mnist/runme.py
  model_zoo/models/imagenet/model_imagenet.prototext
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/models/resnet50/model_resnet50_motif.prototext
  model_zoo/models/resnet50/model_resnet50_sequential.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_1.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_2.prototext
  model_zoo/models/vram/dram_template.prototext
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
  model_zoo/tests/model_lenet_mnist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_dist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_lbann2ckpt.prototext
  model_zoo/tests/model_mnist_conv_graph.prototext
  model_zoo/tests/model_mnist_distributed_io.prototext
  model_zoo/tests/model_mnist_partitioned_io.prototext
  model_zoo/tests/model_mnist_ridge_regression.prototext
  model_zoo/tests/model_mnist_softmax_classifier.prototext
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
Labels: refactor, review requested

#675 Remove deprecated functionality in JAG models
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m1_template.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/jag/gan/cyclic/cyclic_gan_model.prototext
  model_zoo/models/jag/gan/cyclic/model_template.prototext
  model_zoo/models/jag/gan/vanilla/gan.prototext
  model_zoo/models/jag/gan/vanilla/gan_template.prototext
  model_zoo/models/jag/vae_fcn.prototext
Labels: refactor

#671 Remove deprecated functionality in CANDLE Pilot1 models
  model_zoo/models/autoencoder_candle_pilot1/README.md
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_200x150x100x100x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_500x250x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_sigmoid.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_dnn_chem_ecfp.prototext
  model_zoo/models/candle/pilot1/ae_nodeselect_gdc.prototext
  model_zoo/models/candle/pilot1/combo.prototext
Labels: refactor

#681 Patch build system for Theta
  ReleaseNotes.txt
  cmake/modules/SetupProtobuf.cmake
  superbuild/lbann/CMakeLists.txt
  superbuild/opencv/CMakeLists.txt
  superbuild/protobuf/CMakeLists.txt
Labels: build, enhancement, review requested

#682 Timer callback keeps separate data for each execution mode
  include/lbann/callbacks/callback_timer.hpp
  src/callbacks/callback_timer.cpp
Labels: bug, review requested
