Repository LLNL/lbann, pull requests merged in 2018-05, with the labels that each got.

#311 Metric that interacts with evaluation layers.
  include/lbann/lbann.hpp
  include/lbann/metrics/metric.hpp
  src/metrics/CMakeLists.txt
  src/metrics/layer_metric.cpp
  src/metrics/metric.cpp
  src/proto/factories/metric_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#316 Bugfixes for "Xavier" initializers
  include/lbann/weights/fan_in_fan_out_initializers.hpp
  src/proto/lbann.proto
  src/weights/fan_in_fan_out_initializers.cpp
Labels: bug

#319 initial jag_conduit data reader
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/FindCONDUIT.cmake
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/lbann.hpp
  scripts/build_lbann_lc.sh
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_jag_conduit.cpp
Labels: enhancement, review requested

#322 Bamboo updates
  bamboo/clean.sh
  bamboo/common_python/test_tools.py
  bamboo/common_python/tools.py
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/conftest.py
  bamboo/unit_tests/conftest.py
  scripts/spack_recipes/build_lbann.sh
Labels: in progress

#314 Update Weekly Develop's expected values
  bamboo/integration_tests/expected_values/catalyst/clang4/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/gcc4/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/gcc7/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/intel18/expected_performance.csv
  bamboo/integration_tests/expected_values/surface/gcc4/expected_performance.csv
Labels: in progress

#321 flexible JAG reader
  CMakeLists.txt
  include/lbann/data_readers/data_reader_jag.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  model_zoo/models/jag/data_reader_jag.prototext
  src/data_readers/data_reader_jag.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, in progress, review requested

#317 Updated OS X build script
  scripts/build_lbann_osx.sh
  scripts/spack_recipes/build_lbann.sh
Labels: review requested

#312 Data store ssd
  include/lbann/comm.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_store/data_store_csv.hpp
  include/lbann/data_store/data_store_image.hpp
  include/lbann/data_store/data_store_imagenet.hpp
  include/lbann/data_store/data_store_multi_images.hpp
  include/lbann/data_store/generic_data_store.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  src/comm.cpp
  src/data_readers/data_reader.cpp
  src/data_store/data_store_csv.cpp
  src/data_store/data_store_image.cpp
  src/data_store/data_store_imagenet.cpp
  src/data_store/data_store_imagenet_patches.cpp
  src/data_store/data_store_merge_features.cpp
  src/data_store/data_store_multi_images.cpp
  src/data_store/data_store_pilot2_molecular.cpp
  src/data_store/data_store_triplet.cpp
  src/data_store/generic_data_store.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#324 Bamboo Updates Including README
  bamboo/README.md
  bamboo/common_python/test_tools.py
  bamboo/common_python/tools.py
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/full_alexnet.sh
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_io_buffers.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/conftest.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_resnet.py
  bamboo/unit_tests/test_unit_ridge_regression.py
Labels: in progress

#329 More Bamboo Updates
  bamboo/README.md
  bamboo/compiler_tests/test_compiler.py
  bamboo/unit_tests/error/README.md
  bamboo/unit_tests/output/README.md
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_resnet.py
  bamboo/unit_tests/test_unit_ridge_regression.py
Labels: in progress

#328 create tarball of files on local ssd, to enable faster startup time in subsequent runs
  include/lbann/comm.hpp
  include/lbann/data_store/data_store_image.hpp
  include/lbann/data_store/generic_data_store.hpp
  model_zoo/lbann.cpp
  src/data_store/data_store_image.cpp
  src/data_store/data_store_imagenet.cpp
  src/data_store/generic_data_store.cpp
  src/proto/proto_common.cpp
Labels: enhancement, in progress

#336 Fix GPU Aluminum allreduces
  src/optimizers/optimizer.cpp
Labels: bug

#354 GPU support in CheckNaN callback
  src/callbacks/callback_checknan.cpp
Labels: bug, enhancement

#337 Fix off-by-one when determining the pooling mode name.
  src/base.cpp
Labels: bug

#355 Sync Hydrogen before Al/NCCL allreduce
  src/comm.cpp
Labels: bug

#356 GPU performance optimization
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/sigmoid.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/objective_functions/weight_regularization/l2.hpp
  include/lbann/weights/weights.hpp
  src/layers/activations/softmax.cpp
  src/layers/layer.cpp
  src/objective_functions/weight_regularization/l2.cpp
  src/weights/weights.cpp
Labels: enhancement

#298 FC layers can apply transpose of weights matrix.
  include/lbann/layers/learning/fully_connected.hpp
  model_zoo/historical/cnn_mnist.cpp
  model_zoo/historical/lenet_mnist.cpp
  model_zoo/models/candle/pilot1/ae_nodeselect_gdc.prototext
  src/layers/learning/fully_connected.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement

#361 set num_neurons in FC to num_labels from data_reader
  include/lbann/layers/learning/fully_connected.hpp
  model_zoo/models/alexnet/model_alexnet.prototext
  src/proto/factories/layer_graph_factory.cpp
  src/proto/lbann.proto
Labels: enhancement

#335 Siamse patch list tool
  include/lbann/data_readers/offline_patches_npz.hpp
  include/lbann/utils/cnpy_utils.hpp
  include/lbann/utils/file_utils.hpp
  src/data_readers/offline_patches_npz.cpp
  src/utils/cnpy_utils.cpp
  tools/compute_mean/CMakeLists.txt
  tools/compute_mean/Mat.hpp
  tools/compute_mean/lbann/utils/cnpy_utils.hpp
  tools/compute_mean/lbann/utils/file_utils.cpp
  tools/siamese_patch_list/CMakeLists.txt
  tools/siamese_patch_list/lbann
  tools/siamese_patch_list/mem.hpp
  tools/siamese_patch_list/siamese_patches.cpp
Labels: enhancement, review requested

#325 Cycle gan
  experiments/run_lbann_cycgan_experiment.sh
  include/lbann/data_readers/data_reader_jag.hpp
  include/lbann/data_readers/data_reader_merge_features.hpp
  include/lbann/layers/activations/abs.hpp
  include/lbann/layers/activations/l2_loss.hpp
  include/lbann/layers/activations/sigmoid_bce_with_logits.hpp
  include/lbann/lbann.hpp
  include/lbann/models/greedy_layerwise_autoencoder.hpp
  include/lbann/models/model.hpp
  model_zoo/CMakeLists.txt
  model_zoo/lbann_cycgan.cpp
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m1.py
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m2.py
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m3.py
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m1_template.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/jag/cycle_gan/generate_cycgan_m1.py
  model_zoo/models/jag/cycle_gan/generate_cycgan_m2.py
  model_zoo/models/jag/cycle_gan/generate_cycgan_m3.py
  src/data_readers/data_reader_jag.cpp
  src/data_readers/data_reader_merge_features.cpp
  src/models/greedy_layerwise_autoencoder.cpp
  src/models/model.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, in progress

#364 Jag conduit multi-source data
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/init_image_data_readers.cpp
Labels: enhancement, in progress

#369 Fix compilation errors in debug build
  include/lbann/layers/regularizers/dropout.hpp
  src/objective_functions/weight_regularization/l2.cpp
Labels: bug

#367 Skip failing tests
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_resnet.py
  bamboo/unit_tests/test_unit_ridge_regression.py
Labels: in progress

#373 Resize layer activations more carefully.
  src/layers/layer.cpp
Labels: bug

#377 Skip more failing tests
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  scripts/spack_recipes/build_lbann.sh
Labels: in progress

#375 Fix softmax GPU cutoff kernels
  include/lbann/layers/activations/softmax.hpp
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
Labels: bug

#368 Precomputed scaling
  include/lbann/data_readers/cv_subtractor.hpp
  src/data_readers/cv_subtractor.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  tests/test_img_pipeline/CMakeLists.txt
  tests/test_img_pipeline/main.cpp
  tests/test_patchworks/CMakeLists.txt
Labels: enhancement, review requested

#381 Fix spacing in batchnorm description.
  include/lbann/layers/regularizers/batch_normalization.hpp
Labels: enhancement

#378 Jag conduit data reader for cycle_gan
  include/lbann/data_readers/data_reader_jag.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  model_zoo/models/jag/data_reader_jag.prototext
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  src/data_readers/data_reader_jag.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, review requested
