Repository LLNL/lbann, pull requests merged in 2018-07, with the labels that each got.

#496 Aluminum/NCCL updates
  include/lbann/comm.hpp
  src/comm.cpp
Labels: enhancement, review requested

#493 handle nullptr of the data reader undefined for an execution mode
  include/lbann/lbann.hpp
  include/lbann/proto/factories.hpp
  include/lbann/utils/peek_map.hpp
  model_zoo/lbann.cpp
  src/data_store/generic_data_store.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/proto_common.cpp
Labels: bug, enhancement, review requested

#506 Warning macro
  include/lbann/utils/exception.hpp
Labels: enhancement

#495 support for partitioning datasets amongst models.
  include/lbann/data_readers/data_reader.hpp
  src/data_readers/data_reader.cpp
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, in progress

#505 Avoid TranslateBetweenGrids
  model_zoo/lbann2.cpp
Labels: bug, review requested

#512 GPU evaluation layer
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/metrics/layer_metric.hpp
  include/lbann/objective_functions/layer_term.hpp
  model_zoo/tests/model_mnist_conv_graph.prototext
  src/layers/transform/CMakeLists.txt
  src/layers/transform/evaluation.cpp
  src/metrics/layer_metric.cpp
  src/objective_functions/layer_term.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/model_factory.cpp
Labels: enhancement, review requested

#515 Refactoring tensor dimension management in layers
  include/lbann/layers/activations/sigmoid.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/input/repeated_input_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/discrete_random.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/max.hpp
  include/lbann/layers/transform/min.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  src/layers/layer.cpp
  src/models/greedy_layerwise_autoencoder.cpp
  src/models/model.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/utils/cudnn.cpp
Labels: enhancement, review requested

#518 Warning macro deduces MPI rank by asking MPI.
  include/lbann/utils/exception.hpp
Labels: enhancement, review requested

#521 Fix performance regression in metrics
  include/lbann/layers/transform/evaluation.hpp
  src/layers/transform/evaluation.cpp
Labels: review requested

#522 Experiment script option to enable CUDA-MEMCHECK.
  experiments/run_lbann_experiment.sh
  scripts/debug/cuda-memcheck.sh
Labels: enhancement, review requested

#519 Removing ancient command-line argument parsers
  include/lbann/CMakeLists.txt
  include/lbann/lbann.hpp
  include/lbann/params.hpp
  src/CMakeLists.txt
  src/params.cpp
Labels: refactor, review requested

#532 Avoiding GCC 8.1 in build script.
  scripts/build_lbann_lc.sh
Labels: bug, review requested

#514 support for new jag format
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/layers/layer.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, in progress

#536 Fix include for hwloc. Also, prefer the HWLOC with your MPI library.
  cmake/modules/FindHWLOC.cmake
Labels: bug

#531 Optimizations for GPU memory
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  src/layers/layer.cpp
  src/proto/factories/layer_factory.cpp
Labels: enhancement, review requested

#538 freeze custom weights consistently with respective layers
  src/proto/factories/model_factory.cpp
Labels: bug, review requested

#545 Updating DRAM to use new functionality.
  model_zoo/models/vram/.gitignore
  model_zoo/models/vram/dram_template.prototext
  model_zoo/models/vram/generate_dram.py
Labels: enhancement

#549 Update profiler
  include/lbann/callbacks/profiler.hpp
  src/callbacks/profiler.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#558 Restore metrics using non-blocking allreduces.
  include/lbann/layers/transform/evaluation.hpp
  src/layers/transform/evaluation.cpp
  src/models/model.cpp
Labels: enhancement, review requested
