Repository LLNL/lbann, pull requests merged in 2018-11, with the labels that each got.

#688 Superbuild output update
  CMakeLists.txt
  superbuild/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/cnpy/CMakeLists.txt
  superbuild/cub/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/jpeg-turbo/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
  superbuild/openblas/CMakeLists.txt
  superbuild/opencv/CMakeLists.txt
  superbuild/protobuf/CMakeLists.txt
Labels: build, enhancement, review requested

#685 fix the bug in methods to obtain slice points and number of neurons
  src/proto/factories/layer_factory.cpp
Labels: bug, review requested

#695 FC layer doesn't need output dimensions at instantiation.
  src/proto/factories/layer_factory.cpp
Labels: bug, review requested

#699 some quick fixes for lbann versioning
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/SetupElemental.cmake
  cmake/modules/SetupProtobuf.cmake
Labels: build, enhancement, review requested

#702 Moving MNIST reader removes empty space around digits.
  src/data_readers/data_reader_moving_mnist.cpp
Labels: enhancement

#708 Tune host-transfer use for Sierra
  src/comm.cpp
Labels: enhancement

#700 Finish install target
  CMakeLists.txt
  cmake/VTune.cmake
  cmake/configure_files/LBANNConfig.cmake.in
  cmake/configure_files/lbann_config.hpp.in
  cmake/jpeg-turbo.cmake
  cmake/modules/FindCUB.cmake
  cmake/modules/FindNCCL.cmake
  cmake/modules/FindVTune.cmake
  cmake/modules/LBANNCMakeUtilities.cmake
  cmake/modules/LBANNDebugUtilities.cmake
  cmake/modules/SetupCUDAToolkit.cmake
  cmake/modules/SetupCXX.cmake
  cmake/modules/SetupElemental.cmake
  cmake/modules/SetupMPI.cmake
  cmake/modules/SetupOpenMP.cmake
  cmake/modules/SetupVTune.cmake
  external/TBinf/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: build, enhancement, review requested

#712 Confusion matrix callback
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_confusion_matrix.hpp
  include/lbann/lbann.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_confusion_matrix.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#709 Channel-wise mean layer
  include/lbann/layers/misc/CMakeLists.txt
  include/lbann/layers/misc/channelwise_mean.hpp
  include/lbann/lbann.hpp
  model_zoo/tests/layer_tests/model_channelwise_mean.prototext
  src/layers/misc/CMakeLists.txt
  src/layers/misc/channelwise_mean.cpp
  src/layers/misc/channelwise_mean.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#669 Removing deprecated test in model zoo
  model_zoo/tests/CMakeLists.txt
  model_zoo/tests/lbann_self_test.cpp
Labels: refactor, review requested

#713 Removing references to lscratchf partition
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_io_buffers.py
  bamboo/unit_tests/prototext/data_reader_mnist.prototext
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_mnist_conv_graph.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
  experiments/run_lbann_cycgan_experiment.sh
  model_zoo/data_readers/CANDLE/pilot2/data_reader_candle_pilot2_6k_run10.prototext
  model_zoo/data_readers/data_reader_cifar10.prototext
  model_zoo/data_readers/data_reader_mnist.prototext
  model_zoo/data_readers/data_reader_moving_mnist.prototext
  model_zoo/models/gan/mnist/adversarial_data.prototext
  model_zoo/models/gan/mnist/discriminator_data.prototext
  model_zoo/models/imagenet/data_reader_imagenet.prototext
  model_zoo/models/imagenet/model_imagenet.prototext
  model_zoo/models/imagenet/runme.py
  scripts/build_lbann_lc.sh
Labels: bug, review requested

#715 Callback to check metric values
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_check_metric.hpp
  include/lbann/callbacks/callback_check_reconstruction_error.hpp
  include/lbann/lbann.hpp
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_check_metric.cpp
  src/callbacks/callback_check_reconstruction_error.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#716 Follow-up refactoring for PR #715.
  bamboo/common_python/tools.py
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_check_gradients.hpp
  include/lbann/lbann.hpp
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/tests/layer_tests/model_channelwise_mean.prototext
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_log_softmax.prototext
  model_zoo/tests/layer_tests/model_softmax.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
  model_zoo/tests/model_mnist_conv_graph.prototext
  model_zoo/tests/model_mnist_ridge_regression.prototext
  model_zoo/tests/model_mnist_softmax_classifier.prototext
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_check_gradients.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: refactor

#719 CosmoFlow Prototype
  model_zoo/data_readers/data_reader_synthetic_cosmoflow_128.prototext
  model_zoo/models/cosmoflow/model_cosmoflow.prototext
Labels: enhancement, review requested

#718 Minor changes to entry-wise layers.
  include/lbann/layers/loss/entrywise.hpp
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/math/unary.hpp
  src/layers/math/binary.cpp
  src/layers/math/binary.cu
  src/layers/math/unary.cpp
  src/layers/math/unary.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: refactor

#720 GPU implementation of leaky ReLU layer
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/activations/relu.hpp
  model_zoo/tests/layer_tests/model_leaky_relu.prototext
  src/layers/activations/CMakeLists.txt
  src/layers/activations/leaky_relu.cpp
  src/layers/activations/leaky_relu.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, refactor, review requested

#703 Hint layers for layer output dimensions
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/log_softmax.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/mean_absolute_error.hpp
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/misc/covariance.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/regularizers/selu_dropout.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/in_top_k.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/sort.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/layers/transform/weights.hpp
  model_zoo/models/alexnet/model_alexnet.prototext
  src/layers/layer.cpp
  src/layers/transform/evaluation.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#680 Removing deprecated Siamese model
  include/lbann/lbann.hpp
  include/lbann/models/CMakeLists.txt
  include/lbann/models/siamese.hpp
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/runme.py
  model_zoo/models/siamese/siamese_alexnet/model_siamese_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  src/models/CMakeLists.txt
  src/models/siamese.cpp
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
Labels: refactor, review requested

#676 Remove deprecated functionality in CANDLE Pilot2 models
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_bead_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_molecular_autoencoder_pilot2.prototext
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: refactor, review requested

#679 Remove support for deprecated metrics
  include/lbann/lbann.hpp
  include/lbann/metrics/CMakeLists.txt
  include/lbann/metrics/boolean_accuracy.hpp
  include/lbann/metrics/boolean_false_negatives.hpp
  include/lbann/metrics/boolean_false_positives.hpp
  include/lbann/metrics/categorical_accuracy.hpp
  include/lbann/metrics/mean_absolute_deviation.hpp
  include/lbann/metrics/mean_squared_error.hpp
  include/lbann/metrics/pearson_correlation.hpp
  include/lbann/metrics/r2.hpp
  include/lbann/metrics/top_k_categorical_accuracy.hpp
  include/lbann/proto/factories.hpp
  src/metrics/CMakeLists.txt
  src/metrics/boolean_accuracy.cpp
  src/metrics/boolean_false_negatives.cpp
  src/metrics/boolean_false_positives.cpp
  src/metrics/categorical_accuracy.cpp
  src/metrics/mean_absolute_deviation.cpp
  src/metrics/mean_squared_error.cpp
  src/metrics/pearson_correlation.cpp
  src/metrics/r2.cpp
  src/metrics/top_k_categorical_accuracy.cpp
  src/proto/factories/CMakeLists.txt
  src/proto/factories/metric_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
Labels: refactor, review requested

#729 Remove deprecated sequential model
  include/lbann/lbann.hpp
  include/lbann/models/CMakeLists.txt
  include/lbann/models/sequential.hpp
  src/models/CMakeLists.txt
  src/models/sequential.cpp
  src/proto/factories/model_factory.cpp
Labels: refactor, review requested
