Repository LLNL/lbann, pull requests merged in 2018-06, with the labels that each got.

#383 Layers for visual attention.
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/max.hpp
  include/lbann/layers/transform/min.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/lbann.hpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
  viz/properties.txt
Labels: enhancement, review requested

#387 fix the name of the member variable, m_model_rank, of generic_data_reader
  include/lbann/data_readers/data_reader.hpp
Labels: review requested

#376 Updated the I/O layers and data buffers to support multiple activations in the input layer, e.g. a data sample and label / response.
  CMakeLists.txt
  include/lbann/io/data_buffers/distributed_io_buffer.hpp
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/io/data_buffers/partitioned_io_buffer.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/input/repeated_input_layer.hpp
  include/lbann/layers/io/io_layer.hpp
  include/lbann/layers/io/target/generic_target_layer.hpp
  include/lbann/layers/io/target/reconstruction.hpp
  include/lbann/layers/io/target/target_layer.hpp
  model_zoo/README.md
  model_zoo/historical/CMakeLists.txt
  model_zoo/historical/cnn_mnist.cpp
  model_zoo/historical/lenet_mnist.cpp
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_dnn_chem_ecfp.prototext
  model_zoo/models/candle/pilot1/combo.prototext
  model_zoo/models/char_rnn/char_lstm.prototext
  model_zoo/models/char_rnn/char_rnn.prototext
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  model_zoo/models/imagenet/model_imagenet.prototext
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/models/resnet50/model_resnet50_motif.prototext
  model_zoo/models/resnet50/model_resnet50_sequential.prototext
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/siamese_alexnet/model_siamese_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_1.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_2.prototext
  model_zoo/tests/model_lenet_mnist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_dist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_lbann2ckpt.prototext
  model_zoo/tests/model_mnist_distributed_io.prototext
  model_zoo/tests/model_mnist_partitioned_io.prototext
  model_zoo/tests/model_mnist_resnet.prototext
  model_zoo/tests/model_mnist_ridge_regression.prototext
  model_zoo/tests/model_mnist_softmax_regression.prototext
  src/callbacks/callback_io.cpp
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
Labels: enhancement, in progress

#395 Precomputed scaling
  include/lbann/data_readers/cv_subtractor.hpp
  model_zoo/models/siamese/finetune-cub/data_reader_cub.prototext
  model_zoo/models/siamese/siamese_alexnet/data_reader_imagenet_patches.prototext
  model_zoo/models/siamese/siamese_alexnet/model_siamese_alexnet.prototext
  model_zoo/models/siamese/triplet/data_reader_multi_images.prototext
  model_zoo/models/siamese/triplet/data_reader_triplet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm.prototext
  src/data_readers/cv_subtractor.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  tests/test_img_pipeline/CMakeLists.txt
  tests/test_img_pipeline/lbann_config.hpp
  tests/test_img_pipeline/main.cpp
Labels: enhancement, review requested

#402 compute_mean tool update
  tests/test_patchworks/CMakeLists.txt
  tests/test_patchworks/Mat.hpp
  tests/test_patchworks/lbann_config.hpp
  tools/compute_mean/Mat.hpp
  tools/compute_mean/mean_image.cpp
  tools/compute_mean/walltimes.cpp
Labels: enhancement

#403 Jag conduit data reader update
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  src/proto/proto_common.cpp
Labels: bug, enhancement, review requested

#408 Fixing runtime errors in check_nan callback.
  include/lbann/callbacks/callback_checknan.hpp
  src/callbacks/callback_checknan.cpp
Labels: bug

#410 Updated the input layer to support reconstruction target layers
  include/lbann/base.hpp
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/input/input_layer.hpp
  include/lbann/layers/io/input/repeated_input_layer.hpp
  include/lbann/layers/io/io_layer.hpp
  include/lbann/layers/io/target/reconstruction.hpp
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_200x150x100x100x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_sigmoid.prototext
  model_zoo/models/autoencoder_cifar10/model_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_imagenet/model_conv_autoencoder_imagenet.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/model_conv_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/vae_mnist.prototext
  model_zoo/models/candle/pilot1/ae_nodeselect_gdc.prototext
  model_zoo/models/candle/pilot1/combo.prototext
  model_zoo/models/greedy_layerwise_autoencoder_mnist/model_greedy_layerwise_autoencoder_mnist.prototext
  model_zoo/models/jag/vae_fcn.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_bead_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_molecular_autoencoder_pilot2.prototext
  src/models/greedy_layerwise_autoencoder.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/lbann.proto
Labels: bug, in progress, review requested

#406 fix clang compilation errors
  include/lbann/layers/io/target/reconstruction.hpp
Labels: bug, review requested

#418 Improvements to debug callback
  include/lbann/callbacks/callback_debug.hpp
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  model_zoo/models/alexnet/model_alexnet.prototext
  src/callbacks/callback_debug.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#409 correct value type handling in jag_conduit data reader
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  src/data_readers/data_reader_jag_conduit.cpp
Labels: enhancement, review requested

#419 Improving gradient checking unit test for convolutional graph models.
  bamboo/unit_tests/test_unit_conv_graph.py
  bamboo/unit_tests/test_unit_resnet.py
  model_zoo/tests/model_mnist_conv_graph.prototext
  src/proto/lbann.proto
Labels: enhancement, review requested

#427 Detect GPU matrices in allreduces
  include/lbann/comm.hpp
  src/comm.cpp
  src/optimizers/optimizer.cpp
Labels: enhancement

#421 use cv::imdecode() instead of cv::imread()
  include/lbann/data_readers/cv_utils.hpp
  src/data_readers/cv_utils.cpp
  src/data_readers/image_utils.cpp
Labels: enhancement, review requested

#437 Fix cuDNN workspace size
  include/lbann/utils/cudnn_wrapper.hpp
  model_zoo/lbann.cpp
Labels: enhancement

#438 ImageNet crops to 224x224
  model_zoo/data_readers/data_reader_imagenet.prototext
Labels: bug

#417 GPU model-parallel softmax
  include/lbann/layers/activations/softmax.hpp
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
  src/proto/factories/layer_graph_factory.cpp
Labels: enhancement

#430 GPU implementation of Adagrad.
  include/lbann/optimizers/adagrad.hpp
  src/optimizers/CMakeLists.txt
  src/optimizers/adagrad.cu
Labels: enhancement, review requested

#431 Removing deprecated KL divergence objective function term.
  include/lbann/lbann.hpp
  include/lbann/objective_functions/kl_divergence.hpp
  include/lbann/objective_functions/layer_term.hpp
  src/objective_functions/CMakeLists.txt
  src/objective_functions/kl_divergence.cpp
  src/proto/factories/objective_function_factory.cpp
  src/proto/lbann.proto
Labels: review requested

#435 Overwrite error signals during backprop instead of adding to them
  include/lbann/layers/activations/activation.hpp
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/io/target/generic_target_layer.hpp
  include/lbann/layers/io/target/reconstruction.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/regularizers/selu_dropout.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/categorical_random.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/discrete_random.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/max.hpp
  include/lbann/layers/transform/min.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/safe_inv.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/zero.hpp
  include/lbann/models/model.hpp
  src/callbacks/callback_gradient_check.cpp
  src/layers/activations/relu.cpp
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
  src/layers/activations/tanh.cpp
  src/layers/layer.cpp
  src/layers/learning/fully_connected.cpp
  src/layers/regularizers/batch_normalization.cu
  src/models/model.cpp
Labels: enhancement, review requested

#446 Trying to fix performance regression.
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/number_theory.hpp
  src/utils/CMakeLists.txt
  src/utils/cudnn_wrapper.cpp
  src/utils/number_theory.cpp
Labels: bug

#449 cleaning up deprecated image preprocessing
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_imagenet_org.hpp
  include/lbann/data_readers/data_reader_imagenet_single.hpp
  include/lbann/lbann.hpp
  model_zoo/models/imagenet/data_reader_imagenet_org.prototext
  model_zoo/models/imagenet/data_reader_imagenet_single.prototext
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_imagenet_org.cpp
  src/data_readers/data_reader_imagenet_single.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: review requested

#450 remove the deprecated OpenBLAS patching used for the old build script
  external/OpenBLAS/ChangedFiles.EL_OpenBLAS.txt
  external/OpenBLAS/ChangedFiles.OpenBLAS.txt
  external/OpenBLAS/EL_OpenBLAS.patch
  external/OpenBLAS/Makefile.power.new
  external/OpenBLAS/Makefile.system.new
  external/OpenBLAS/OpenBLAS.cmake.new
  external/OpenBLAS/OpenBLAS.patch
  external/OpenBLAS/c_check.new
  external/OpenBLAS/f_check.new
  external/OpenBLAS/genPatchELOpenBLAS.sh
  external/OpenBLAS/genPatchOpenBLAS.sh
  external/OpenBLAS/noop.sh
  external/OpenBLAS/old/EL_OpenBLAS.patch
  external/OpenBLAS/old/OpenBLAS.patch
  external/OpenBLAS/patchELOpenBLAS.sh
  external/OpenBLAS/patchOpenBLAS.sh
Labels: review requested

#444 siamse minor updates
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm.prototext
  src/data_readers/cv_process.cpp
Labels: bug, enhancement, review requested

#453 Image preprocessing pipeline test update
  tests/test_img_pipeline/Mat.hpp
  tools/compute_mean/Mat.hpp
Labels: enhancement

#454 Fixes build failure on non-gpu systems
  include/lbann/callbacks/callback_gpu_memory_usage.hpp
Labels: bug, review requested

#457 Improving worst-case behavior of prime factorization.
  src/utils/number_theory.cpp
Labels: enhancement

#412 Summarize certain runtimes from every rank
  include/lbann/utils/summary.hpp
  src/callbacks/callback_timer.cpp
  src/layers/layer.cpp
  src/utils/summary.cpp
Labels: enhancement

#458 Jag conduit bug fix
  src/data_readers/data_reader_jag_conduit.cpp
  tools/compute_mean/Mat.hpp
Labels: bug

#461 add key filtering mechanisms to jag_conduit data reader
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#443 removing irrelevant "validation_percent" in prototext of the testset data reader
  model_zoo/data_readers/data_reader_ascii.prototext
  model_zoo/data_readers/data_reader_candle_pilot1.prototext
  model_zoo/data_readers/data_reader_candle_pilot1_combo.prototext
  model_zoo/data_readers/data_reader_candle_pilot1_growth.prototext
  model_zoo/data_readers/data_reader_cifar10.prototext
  model_zoo/data_readers/data_reader_imagenet.prototext
  model_zoo/data_readers/data_reader_mnist.prototext
  model_zoo/data_readers/data_reader_nci.prototext
  model_zoo/data_readers/data_reader_nci.prototext.bve
  model_zoo/data_readers/data_reader_synthetic.prototext
  model_zoo/models/imagenet/data_reader_imagenet.prototext
  model_zoo/models/jag/data_reader_jag.prototext
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  model_zoo/models/siamese/finetune-cub/data_reader_cub.prototext
  model_zoo/models/siamese/siamese_alexnet/data_reader_imagenet_patches.prototext
  model_zoo/models/siamese/triplet/data_reader_multi_images.prototext
  model_zoo/models/siamese/triplet/data_reader_triplet.prototext
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#463 Skip single-GPU allreduces
  src/comm.cpp
Labels: enhancement

#469 fix on the matrix view passing for numpy-based jag data reader
  src/data_readers/data_reader_jag.cpp
Labels: bug

#471 Removing recurrent model.
  include/lbann/models/CMakeLists.txt
  include/lbann/models/recurrent.hpp
  src/models/CMakeLists.txt
  src/models/recurrent.cpp
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: review requested

#470 Finer-grained NCCL streams
  include/lbann/comm.hpp
  src/comm.cpp
  src/models/model.cpp
Labels: enhancement, review requested

#442 Simple image resize
  include/lbann/data_readers/cv_process.hpp
  include/lbann/data_readers/cv_resizer.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/cv_resizer.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  tests/test_img_pipeline/CMakeLists.txt
  tests/test_img_pipeline/main.cpp
  tests/test_patchworks/CMakeLists.txt
Labels: enhancement, review requested

#498 Fix all the compiler errors with intel/18.0.0
  include/lbann/callbacks/callback_checkpoint.hpp
  include/lbann/callbacks/callback_debug.hpp
  include/lbann/callbacks/callback_sync_layers.hpp
  include/lbann/data_store/data_store_image.hpp
  include/lbann/data_store/data_store_merge_samples.hpp
  include/lbann/data_store/data_store_pilot2_molecular.hpp
  src/callbacks/callback_checkpoint.cpp
  src/proto/init_image_data_readers.cpp
Labels: bug, review requested

#497 fix cmake variable name to enable NVPROF
  CMakeLists.txt
Labels: bug, review requested
