Repository LLNL/lbann, pull requests merged in 2018-12, with the labels that each got.

#730 Setting up validation set with moving MNIST data reader
  src/proto/proto_common.cpp
Labels: enhancement

#731 Quick bugfix for compilation error with JAG utils
  model_zoo/jag_utils/CMakeLists.txt
Labels: bug, review requested

#701 Refactoring layer descriptions
  include/lbann/layers/activations/elu.hpp
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/io_layer.hpp
  include/lbann/layers/io/target/generic_target_layer.hpp
  include/lbann/layers/io/target/reconstruction.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/layers/transform/zero.hpp
  include/lbann/models/model.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann2.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  src/layers/layer.cpp
  src/models/model.cpp
Labels: refactor, review requested

#734 Restoring CycleGAN layers that were accidentally deleted
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
Labels: bug

#739 Squared difference layer
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  include/lbann/layers/math/binary.hpp
  model_zoo/tests/layer_tests/model_squared_difference.prototext
  src/layers/math/binary.cpp
  src/layers/math/binary.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#740 Prototext file saving can handle case where model name is not set.
  src/proto/proto_common.cpp
Labels: bug, review requested

#749 Output dumping callback supports multiple file formats
  include/lbann/callbacks/callback_dump_outputs.hpp
  src/callbacks/callback_dump_outputs.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#745 Bugfix shared data readers
  include/lbann/models/model.hpp
  include/lbann/proto/proto_common.hpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/models/jag/ae_cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  src/data_readers/data_reader_jag_conduit.cpp
  src/models/model.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
Labels: bug

#748 Updated the callback_save_model to save the model's weights at the end
  experiments/LC_cluster_specific_defaults.sh
  experiments/run_lbann_cycgan_inference.sh
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_checkpoint.hpp
  include/lbann/callbacks/callback_save_model.hpp
  include/lbann/io/persist.hpp
  include/lbann/lbann.hpp
  include/lbann/models/model.hpp
  include/lbann/utils/lbann_library.hpp
  model_zoo/lbann2.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_inf.cpp
  model_zoo/models/jag/ae_cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  src/callbacks/callback_checkpoint.cpp
  src/callbacks/callback_dump_outputs.cpp
  src/callbacks/callback_save_model.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/io/persist.cpp
  src/models/model.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
  src/weights/weights.cpp
Labels: enhancement

#752 Changed the save_model callback so that there is an explicit flag to
  include/lbann/callbacks/callback_save_model.hpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/models/jag/ae_cycle_gan/cycgan_m1.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/data_reader_jag_conduit_lustre.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  src/callbacks/callback_save_model.cpp
  src/models/model.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement

#753 fix the debug message for the shared jag_conduit data reader usin…
  src/proto/proto_common.cpp
Labels: bug

#760 Corrected a bug in the jag conduit reader where shuffling and then
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
Labels: bug

#757 Fix compilation error
  src/utils/summary.cpp
Labels: bug, review requested

#771 Add get_linearized_label_size to synthetic data reader
  include/lbann/data_readers/data_reader_synthetic.hpp
Labels: bug

#759 Strict dimension checks for layer input tensors
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/mean_absolute_error.hpp
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/misc/covariance.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/weighted_sum.hpp
Labels: enhancement, review requested

#755 Tessellate layer
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_layer_tessellate.py
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/tessellate.hpp
  include/lbann/lbann.hpp
  model_zoo/tests/layer_tests/model_tessellate.prototext
  src/layers/transform/CMakeLists.txt
  src/layers/transform/tessellate.cpp
  src/layers/transform/tessellate.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#742 Clamp layer
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_layer_clamp.py
  include/lbann/layers/math/CMakeLists.txt
  include/lbann/layers/math/clamp.hpp
  include/lbann/lbann.hpp
  model_zoo/tests/layer_tests/model_clamp.prototext
  src/layers/math/CMakeLists.txt
  src/layers/math/clamp.cpp
  src/layers/math/clamp.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#724 Update Aluminum algorithm name
  include/lbann/comm.hpp
Labels: enhancement, review requested

#780 Updated the background I/O fetch function to take the execution mode
  include/lbann/layers/io/input/generic_input_layer.hpp
Labels: bug

#786 Removed support for the distributed I/O buffer classes.
  include/lbann/io/data_buffers/distributed_io_buffer.hpp
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/input/input_layer.hpp
  include/lbann/layers/io/target/generic_target_layer.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/io/data_buffers/CMakeLists.txt
  src/io/data_buffers/distributed_io_buffer.cpp
  src/proto/factories/layer_factory.cpp
Labels: enhancement

#784 Callback to perturb Adam hyperparameters
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_perturb_adam.hpp
  include/lbann/lbann.hpp
  include/lbann/optimizers/adam.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_perturb_adam.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#793 Minor improvements to moving MNIST data reader
  src/data_readers/data_reader_moving_mnist.cpp
Labels: enhancement

#792 Update build system docs
  CMakeLists.txt
  README.md
  docs/BuildingLBANN.md
  docs/conf.py
  docs/getting_started.rst
  superbuild/aluminum/CMakeLists.txt
Labels: build, documentation, enhancement

#773 LTFB can handle multiple processes per model
  include/lbann/callbacks/callback_ltfb.hpp
  include/lbann/models/model.hpp
  model_zoo/models/jag/ae_cycle_gan/3models/cycle_gan.prototext
  model_zoo/models/jag/gan/cyclic/model_template.prototext
  model_zoo/models/jag/gan/vanilla/gan.prototext
  src/callbacks/callback_ltfb.cpp
  src/models/model.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: bug, in progress, review requested

#795 Fix build
  superbuild/aluminum/CMakeLists.txt
Labels: bug
