Repository LLNL/lbann, pull requests merged in 2018-04, with the labels that each got.

#269 Update Aluminum interface
  cmake/modules/FindALUMINUM.cmake
  include/lbann/comm.hpp
  src/comm.cpp
  superbuild/aluminum/CMakeLists.txt
Labels: enhancement

#266 Optimizing GPU L2 regularization term.
  include/lbann/objective_functions/weight_regularization/l2.hpp
  include/lbann/utils/cublas_wrapper.hpp
  src/objective_functions/weight_regularization/l2.cpp
  src/optimizers/optimizer.cpp
  src/utils/cublas_wrapper.cpp
  src/utils/cudnn_wrapper.cpp
Labels: enhancement

#247 LSTMs
  include/lbann/layers/layer.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/models/recurrent.hpp
  model_zoo/models/char_rnn/char_lstm.prototext
  model_zoo/models/char_rnn/char_rnn.prototext
  src/models/model.cpp
  src/models/recurrent.cpp
Labels: bug, review requested

#268 Freezer
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/models/directed_acyclic_graph.hpp
  include/lbann/models/model.hpp
  include/lbann/models/recurrent.hpp
  include/lbann/models/siamese.hpp
  include/lbann/weights/weights.hpp
  src/layers/layer.cpp
  src/models/model.cpp
  src/models/sequential.cpp
  src/models/siamese.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/lbann.proto
  src/weights/weights.cpp
Labels: enhancement, review requested

#282 Fix ResNet50 max-pooling padding
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/models/resnet50/model_resnet50_motif.prototext
  model_zoo/models/resnet50/model_resnet50_sequential.prototext
Labels: bug

#286 specifying the weight initialization method for each layer of siamese model
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm.prototext
  model_zoo/models/siamese/triplet/opt_sgd.prototext
Labels: enhancement, review requested

#292 Fixing circular dependence in header files.
  include/lbann/layers/transform/evaluation.hpp
Labels: bug

#295 make broadcast more general
  include/lbann/comm.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  src/data_readers/data_reader_csv.cpp
Labels: enhancement, review requested

#299 clang approved version of broadcast interfaces
  include/lbann/comm.hpp
  include/lbann/detect_El_mpi.hpp
  src/comm.cpp
Labels: bug, review requested

#296 Draft GAN implementation
  experiments/run_lbann_experiment.sh
  include/lbann/callbacks/callback_dump_weights.hpp
  include/lbann/callbacks/callback_save_images.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/layers/transform/zero.hpp
  include/lbann/lbann.hpp
  model_zoo/CMakeLists.txt
  model_zoo/lbann_gan.cpp
  model_zoo/models/gan/mnist/adversarial_data.prototext
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_data.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  src/callbacks/callback_save_images.cpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_mnist.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, in progress, review requested

#277 Enable testing of debug version of compilers
  bamboo/clean.sh
  bamboo/common_python/test_tools.py
  bamboo/common_python/tools.py
  bamboo/compiler_tests/error/README.md
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/expected_values/catalyst/gcc4/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/intel18/expected_performance.csv
  bamboo/integration_tests/expected_values/ray/gcc4/expected_performance.csv
  bamboo/integration_tests/expected_values/surface/gcc4/expected_performance.csv
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_io_buffers.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/conftest.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
Labels: in progress

#310 Add Docker definition file, update singularity definition file
  README.md
  containers/Dockerfile
  containers/README.md
  containers/lbann.def
  singularity/README.md
  singularity/lbann.def
Labels: enhancement, review requested
