Repository LLNL/lbann, pull requests merged in 2018-09, with the labels that each got.

#602 Debugging and optimizing VRAM
  include/lbann/layers/activations/sigmoid.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/utils/cuda.hpp
  src/layers/activations/CMakeLists.txt
  src/layers/activations/sigmoid.cpp
  src/layers/activations/sigmoid.cu
  src/layers/loss/top_k_categorical_accuracy.cu
  src/layers/transform/CMakeLists.txt
  src/layers/transform/crop.cpp
  src/layers/transform/crop.cu
  src/proto/factories/layer_factory.cpp
  src/utils/number_theory.cpp
Labels: bug, enhancement, review requested

#610 Fixed a bug in how the distributed I/O layer works when there are not
  include/lbann/io/data_buffers/distributed_io_buffer.hpp
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/io/data_buffers/partitioned_io_buffer.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  src/io/data_buffers/distributed_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
Labels: bug

#608 Nicer pattern for GPU activation layers
  include/lbann/layers/activations/relu.hpp
  include/lbann/layers/activations/sigmoid.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/cuda.hpp
  include/lbann/utils/entrywise_operator.hpp
  src/layers/activations/relu.cpp
  src/layers/activations/relu.cu
  src/layers/activations/sigmoid.cpp
  src/layers/activations/sigmoid.cu
Labels: enhancement, review requested

#621 Fix model_gather
  include/lbann/comm.hpp
Labels: bug

#620 Batch norm refactor
  include/lbann/layers/regularizers/batch_normalization.hpp
  src/layers/regularizers/CMakeLists.txt
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/proto/factories/layer_factory.cpp
Labels: refactor, review requested

#607 add capability to pull num_neruons from data reader for data_reader_jag_conduit_hdf5
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#627 fix the compilation error by adding the macro guard
  src/proto/factories/layer_factory.cpp
Labels: bug

#630 Updating run script to use raw ImageNet images.
  experiments/run_lbann_experiment.sh
Labels: review requested

#617 Feature hydrogen aluminum integration more updates
  include/lbann/comm.hpp
  model_zoo/tests/comm_test.cpp
  scripts/build_lbann_lc.sh
  src/callbacks/callback_ltfb.cpp
  src/comm.cpp
  src/layers/loss/top_k_categorical_accuracy.cpp
  src/layers/loss/top_k_categorical_accuracy.cu
  src/metrics/top_k_categorical_accuracy.cpp
Labels: review requested

#635 modify build script to optionally use ninja
  scripts/build_lbann_lc.sh
Labels: build, enhancement, review requested

#633 GPU evaluation layer no longer blocks host.
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/utils/cuda.hpp
  src/layers/transform/evaluation.cpp
  src/utils/CMakeLists.txt
  src/utils/cuda.cu
Labels: review requested

#634 GPU L2 weight regularization no longer blocks host
  include/lbann/objective_functions/weight_regularization/l2.hpp
  src/objective_functions/CMakeLists.txt
  src/objective_functions/weight_regularization/CMakeLists.txt
  src/objective_functions/weight_regularization/l2.cpp
  src/objective_functions/weight_regularization/l2.cu
  src/utils/cuda.cu
Labels: review requested
