Repository LLNL/lbann, pull requests merged in 2018-03, with the labels that each got.

#238 GPU debugging
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/utils/cudnn_wrapper.hpp
  src/optimizers/optimizer.cpp
  src/utils/cudnn_wrapper.cpp
Labels: bug, enhancement

#239 learning rate change schedule "poly"
  include/lbann/callbacks/callback_learning_rate.hpp
  include/lbann/models/model.hpp
  src/callbacks/callback_learning_rate.cpp
  src/models/model.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#241 Automatically add dummy and split layers where needed
  include/lbann/layers/layer.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/models/model.hpp
  model_zoo/models/resnet50/model_resnet50.prototext
  model_zoo/tests/model_mnist_resnet.prototext
  src/models/model.cpp
  src/models/sequential.cpp
Labels: enhancement

#236 Accumulating gradients with non-blocking GPU allreduces
  include/lbann/comm.hpp
  include/lbann/data_readers/data_reader_csv.hpp
  include/lbann/data_store/generic_data_store.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/utils/cudnn_wrapper.hpp
  src/comm.cpp
  src/optimizers/optimizer.cpp
  src/utils/cudnn_wrapper.cpp
Labels: enhancement

#244 Build script update
  README.md
  scripts/build_lbann_lc.sh
Labels: bug, review requested

#242 Prototext parser refactor
  include/lbann/base.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/proto/factories.hpp
  include/lbann/proto/proto_common.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann2.cpp
  src/proto/CMakeLists.txt
  src/proto/factories/CMakeLists.txt
  src/proto/factories/callback_factory.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/metric_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/objective_function_factory.cpp
  src/proto/factories/optimizer_factory.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  viz/properties.txt
Labels: enhancement, review requested

#243 Archive results of previous builds
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/test_integration_io_buffers.py
  bamboo/integration_tests/test_integration_performance.py
Labels: in progress

#248 Prototext interface for specifying weights
  include/lbann/proto/factories.hpp
  include/lbann/weights/weights.hpp
  src/layers/layer.cpp
  src/proto/factories/CMakeLists.txt
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/weights_factory.cpp
  src/proto/lbann.proto
  src/weights/weights.cpp
Labels: enhancement

#249 Boolean accuracy metrics
  include/lbann/lbann.hpp
  include/lbann/metrics/CMakeLists.txt
  include/lbann/metrics/boolean_accuracy.hpp
  include/lbann/metrics/boolean_false_negatives.hpp
  include/lbann/metrics/boolean_false_positives.hpp
  src/metrics/CMakeLists.txt
  src/metrics/boolean_accuracy.cpp
  src/metrics/boolean_false_negatives.cpp
  src/metrics/boolean_false_positives.cpp
  src/proto/factories/metric_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#252 Bugfix for GPU memory deallocation.
  src/utils/cudnn_wrapper.cpp
Labels: bug

#261 Debugging combo model
  src/weights/weights.cpp
Labels: bug, in progress

#260 GPU dropout
  include/lbann/layers/regularizers/dropout.hpp
  src/proto/factories/layer_factory.cpp
Labels: enhancement, review requested

#259 Non-blocking objective function interface
  include/lbann/comm.hpp
  include/lbann/objective_functions/kl_divergence.hpp
  include/lbann/objective_functions/loss_functions/binary_cross_entropy.hpp
  include/lbann/objective_functions/loss_functions/cross_entropy.hpp
  include/lbann/objective_functions/loss_functions/cross_entropy_with_uncertainty.hpp
  include/lbann/objective_functions/loss_functions/geom_negloglike.hpp
  include/lbann/objective_functions/loss_functions/loss_function.hpp
  include/lbann/objective_functions/loss_functions/mean_absolute_deviation.hpp
  include/lbann/objective_functions/loss_functions/mean_absolute_error.hpp
  include/lbann/objective_functions/loss_functions/mean_squared_error.hpp
  include/lbann/objective_functions/loss_functions/poisson_negloglike.hpp
  include/lbann/objective_functions/loss_functions/polya_negloglike.hpp
  include/lbann/objective_functions/objective_function.hpp
  include/lbann/objective_functions/objective_function_term.hpp
  include/lbann/objective_functions/weight_regularization/group_lasso.hpp
  include/lbann/objective_functions/weight_regularization/l1.hpp
  include/lbann/objective_functions/weight_regularization/l2.hpp
  src/callbacks/callback_gradient_check.cpp
  src/comm.cpp
  src/models/model.cpp
  src/objective_functions/kl_divergence.cpp
  src/objective_functions/loss_functions/binary_cross_entropy.cpp
  src/objective_functions/loss_functions/cross_entropy.cpp
  src/objective_functions/loss_functions/cross_entropy_with_uncertainty.cpp
  src/objective_functions/loss_functions/geom_negloglike.cpp
  src/objective_functions/loss_functions/loss_function.cpp
  src/objective_functions/loss_functions/mean_absolute_deviation.cpp
  src/objective_functions/loss_functions/mean_absolute_error.cpp
  src/objective_functions/loss_functions/mean_squared_error.cpp
  src/objective_functions/loss_functions/poisson_negloglike.cpp
  src/objective_functions/loss_functions/polya_negloglike.cpp
  src/objective_functions/objective_function.cpp
  src/objective_functions/weight_regularization/group_lasso.cpp
  src/objective_functions/weight_regularization/l1.cpp
  src/objective_functions/weight_regularization/l2.cpp
Labels: enhancement, review requested

#262 Work around for Spectrum MPI
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/comm.hpp
  scripts/build_lbann_lc.sh
Labels: bug

#267 Summarize metric times
  include/lbann/metrics/metric.hpp
  scripts/plotting/plot_comp_times.py
  src/metrics/metric.cpp
  src/models/model.cpp
Labels: enhancement

#264 dropout fix for the copy constructor and the '=' operator
  include/lbann/layers/regularizers/dropout.hpp
Labels: bug, review requested
