Repository LLNL/lbann, pull requests merged in 2019-11, with the labels that each got.

#1325 Convert Bamboo layer unit tests to use Python frontend
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_datareader_python.py
  bamboo/unit_tests/test_unit_layer_argmax.py
  bamboo/unit_tests/test_unit_layer_argmin.py
  bamboo/unit_tests/test_unit_layer_channelwise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_convolution.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_cross_entropy.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_embedding.py
  bamboo/unit_tests/test_unit_layer_entrywise_batch_normalization.py
  bamboo/unit_tests/test_unit_layer_entrywise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_fully_connected.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_mean_squared_error.py
  bamboo/unit_tests/test_unit_layer_one_hot.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_slice.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  model_zoo/tests/layer_tests/model_channelwise_mean.prototext
  model_zoo/tests/layer_tests/model_clamp.prototext
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_elu.prototext
  model_zoo/tests/layer_tests/model_identity.prototext
  model_zoo/tests/layer_tests/model_l1_norm.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_leaky_relu.prototext
  model_zoo/tests/layer_tests/model_log_sigmoid.prototext
  model_zoo/tests/layer_tests/model_log_softmax.prototext
  model_zoo/tests/layer_tests/model_mean_absolute_error.prototext
  model_zoo/tests/layer_tests/model_relu.prototext
  model_zoo/tests/layer_tests/model_selu.prototext
  model_zoo/tests/layer_tests/model_sigmoid.prototext
  model_zoo/tests/layer_tests/model_softplus.prototext
  model_zoo/tests/layer_tests/model_softsign.prototext
  model_zoo/tests/layer_tests/model_squared_difference.prototext
  model_zoo/tests/layer_tests/model_tessellate.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
Labels: CI, review requested

#1334 Update docs to reflect the trainer refactor
  docs/running_lbann.rst
Labels: bug, documentation

#1332 Documentation updates
  docs/RSTDocsFlavorText.py
  docs/SourceTreeDoxyfile
  docs/conf.py
  docs/documentation_building.rst
  docs/index.rst
Labels: documentation, enhancement, review requested

#1337 Add hacked bugfixes for Lassen
  python/lbann/contrib/lc/launcher.py
Labels: bug, python, review requested

#1340 Tidy the source for imcomm callback
  include/lbann/callbacks/imcomm.hpp
  src/callbacks/imcomm.cpp
Labels: refactor, review requested

#1335 Move vision models to applications directory
  applications/vision/README.md
  applications/vision/alexnet.py
  applications/vision/data/__init__.py
  applications/vision/data/imagenet/__init__.py
  applications/vision/data/imagenet/data_reader.prototext
  applications/vision/data/mnist/.gitignore
  applications/vision/data/mnist/__init__.py
  applications/vision/data/mnist/data_reader.prototext
  applications/vision/densenet.py
  applications/vision/lenet.py
  applications/vision/resnet.py
  docs/running_lbann.rst
  model_zoo/vision/.gitignore
Labels: refactor, review requested

#1339 Identify and fix bugs in data_reader_jag_conduit
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_conduit.cpp
Labels: bug, refactor, review requested

#1342 Fix bug in model zoo CMake
  model_zoo/CMakeLists.txt
Labels: bug, review requested

#1336 Initialize RNGs for trainers differently by default
  model_zoo/models/jag/gan/vanilla/gan.prototext
  model_zoo/models/jag/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/wae_nobn.prototext
  src/proto/model.proto
  src/proto/trainer.proto
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1324 Clara-based argument parser
  CMakeLists.txt
  bamboo/compiler_tests/build_script.sh
  cmake/modules/FindClara.cmake
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/argument_parser.hpp
  include/lbann/utils/environment_variable.hpp
  include/lbann/utils/from_string.hpp
  scripts/build_lbann_lc.sh
  src/utils/CMakeLists.txt
  src/utils/argument_parser.cpp
  src/utils/environment_variable.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/argument_parser_test.cpp
  src/utils/unit_test/environment_variable_test.cpp
  src/utils/unit_test/from_string_test.cpp
  src/utils/unit_test/stubs/preset_env_accessor.cpp
  src/utils/unit_test/stubs/preset_env_accessor.hpp
  superbuild/CMakeLists.txt
  superbuild/clara/CMakeLists.txt
Labels: enhancement, review requested

#1338 Create NLP application directory
  applications/nlp/README.md
  applications/nlp/data/.gitignore
  applications/nlp/rnn/dataset.py
  applications/nlp/rnn/main.py
  applications/nlp/utils/__init__.py
  applications/nlp/utils/gutenberg.py
Labels: review requested

#1329 Data store cache
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_conduit.cpp
  src/models/model.cpp
Labels: bug, enhancement, review requested

#1348 Specify a layer's parents in Python frontend with positional args
  applications/vision/alexnet.py
  applications/vision/lenet.py
  applications/vision/resnet.py
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_lenet.py
  bamboo/integration_tests/test_integration_resnet50.py
  bamboo/unit_tests/test_unit_layer_channelwise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_convolution.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_cross_entropy.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_entrywise_batch_normalization.py
  bamboo/unit_tests/test_unit_layer_entrywise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_fully_connected.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_mean_squared_error.py
  bamboo/unit_tests/test_unit_layer_one_hot.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_slice.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  python/lbann/layer.py
  python/lbann/models/resnet.py
  python/lbann/modules.py
Labels: enhancement, python, review requested

#1346 Implement matrix multiply layer
  bamboo/unit_tests/test_unit_layer_matmul.py
  include/lbann/layers/math/CMakeLists.txt
  include/lbann/layers/math/matmul.hpp
  include/lbann/utils/cublas.hpp
  src/layers/math/CMakeLists.txt
  src/layers/math/matmul.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/utils/cublas.cpp
Labels: enhancement, review requested

#1349 update the versions for Aluminum and Hydrogen
  CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
Labels: enhancement, review requested

#1341 Move gradient scaling from learning layers to evaluation layer
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/transform/weights.hpp
  src/layers/learning/channelwise_scale_bias.cpp
  src/layers/learning/channelwise_scale_bias.cu
  src/layers/learning/embedding.cpp
  src/layers/learning/entrywise_scale_bias.cpp
  src/layers/learning/entrywise_scale_bias.cu
  src/layers/learning/fully_connected.cpp
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/layers/regularizers/entrywise_batch_normalization.cpp
  src/layers/regularizers/entrywise_batch_normalization.cu
  src/layers/transform/evaluation.cpp
Labels: refactor, review requested

#1345 Implement GPU embedding layer
  bamboo/unit_tests/test_unit_layer_embedding.py
  include/lbann/layers/learning/embedding.hpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/embedding.cpp
  src/layers/learning/embedding.cu
  src/proto/factories/layer_factory.cpp
Labels: enhancement, review requested

#1351 updated queue names for corona
  bamboo/allocate_and_run.sh
Labels: CI, bug, review requested

#1352 Layer norm
  bamboo/unit_tests/test_unit_layer_layer_norm.py
  include/lbann/layers/regularizers/CMakeLists.txt
  include/lbann/layers/regularizers/layer_norm.hpp
  src/layers/regularizers/CMakeLists.txt
  src/layers/regularizers/layer_norm.cpp
  src/layers/regularizers/layer_norm.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1355 Refactor core components in Python frontend
  python/lbann/__init__.py
  python/lbann/core/__init__.py
  python/lbann/core/callback.py
  python/lbann/core/layer.py
  python/lbann/core/metric.py
  python/lbann/core/model.py
  python/lbann/core/objective_function.py
  python/lbann/core/optimizer.py
  python/lbann/core/trainer.py
  python/lbann/core/util.py
  python/lbann/core/weights.py
  python/lbann/util/__init__.py
Labels: python, refactor, review requested

#1354 Refactor layer modules in Python frontend
  python/lbann/modules.py
  python/lbann/modules/__init__.py
  python/lbann/modules/base.py
  python/lbann/modules/rnn.py
  python/lbann/util/__init__.py
Labels: python, refactor, review requested

#1284 Feature improve spack build env
  docs/building_lbann.rst
  spack_environments/developer_release_cuda_spack.yaml
  spack_environments/developer_release_x86_64_cuda_spack.yaml
  spack_environments/externals_power9le_llnl_lc_cz.yaml
  spack_environments/externals_ppc64le_llnl_lc_cz.yaml
  spack_environments/externals_x86_64_broadwell_llnl_lc_cz.yaml
  spack_environments/std_versions_and_variants_llnl_lc_cz.yaml
Labels: bug, review requested
