Repository LLNL/lbann, pull requests merged in 2019-01, with the labels that each got.

#805 Added a command line flag that can disable the background I/O fetch.
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/models/model.hpp
  include/lbann/utils/threads/thread_pool.hpp
  src/models/model.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
Labels: enhancement

#810 Option to choose weights with L2 regularization.
  include/lbann/objective_functions/weight_regularization/l2.hpp
  src/objective_functions/weight_regularization/l2.cpp
  src/proto/factories/model_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#797 Minor updates to the superbuild
  superbuild/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/elemental/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: build, review requested

#806 Fix cmake 3.12 support
  CMakeLists.txt
  cmake/modules/SetupCUDAToolkit.cmake
  cmake/modules/SetupMPI.cmake
  docs/BuildingLBANN.md
  superbuild/hydrogen/CMakeLists.txt
Labels: build, enhancement, review requested

#814 Bump OpenCV version.
  superbuild/opencv/CMakeLists.txt
Labels: enhancement, review requested

#807 LTFB communication with checkpoint files
  include/lbann/callbacks/callback_ltfb.hpp
  src/callbacks/callback_ltfb.cpp
  src/io/file_io.cpp
  src/io/persist.cpp
  src/models/model.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#813 Minor improvements to dump outputs callback
  include/lbann/callbacks/callback_dump_outputs.hpp
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  model_zoo/models/jag/ae_cycle_gan/3models/ae.prototext
  model_zoo/models/jag/ae_cycle_gan/3models/ae_cyc.prototext
  model_zoo/models/jag/ae_cycle_gan/3models/ae_cyc2.prototext
  model_zoo/models/jag/ae_cycle_gan/3models/cycle_gan.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/ae_cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/ae_cycle_gan/vae1.prototext
  model_zoo/models/jag/ae_cycle_gan/vae_cyc.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3.prototext
  model_zoo/models/jag/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/jag/gan/cyclic/model_template.prototext
  model_zoo/models/jag/gan/vanilla/gan.prototext
  model_zoo/models/jag/gan/vanilla/gan_template.prototext
  model_zoo/models/jag/vae_fcn.prototext
  src/callbacks/callback_dump_outputs.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: bug, review requested

#817 Node-local batch normalization
  include/lbann/layers/regularizers/batch_normalization.hpp
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#816 Bug fix for invalid data reader position
  include/lbann/data_readers/data_reader.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  src/data_readers/data_reader.cpp
Labels: bug

#825 Correct batchnorm defaults
  src/proto/factories/layer_factory.cpp
Labels: bug, review requested

#782 Cleaning up global namespace pollution
  include/lbann/base.hpp
  include/lbann/data_readers/cv_utils.hpp
  include/lbann/data_readers/data_reader_multi_images.hpp
  include/lbann/data_readers/image_utils.hpp
  include/lbann/lbann.hpp
  include/lbann/proto/init_image_data_readers.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/utils/options.hpp
  model_zoo/tests/test_utils.hpp
  src/base.cpp
  src/data_readers/cv_utils.cpp
  src/data_readers/data_reader_mnist_siamese.cpp
  src/data_readers/data_reader_multi_images.cpp
  src/data_readers/data_reader_triplet.cpp
  src/data_readers/image_utils.cpp
  src/objective_functions/loss_functions/polya_negloglike.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
  src/utils/options.cpp
Labels: enhancement, review requested

#829 CUDA/CUBLAS error checking
  include/lbann/utils/cublas.hpp
  include/lbann/utils/cuda.hpp
Labels: enhancement, review requested

#818 Adding support for using spack environments to build LBANN.
  docs/BuildingLBANN.md
  docs/getting_started.rst
  docs/spack_environment.md
  spack_environments/developer_release_ppc64le_cuda_spack.yaml
  spack_environments/developer_release_x86_64_cuda_spack.yaml
  spack_environments/externals_llnl_lc_cz.yaml
Labels: enhancement, in progress

#833 Python Prototext interface
  scripts/proto/README.md
  scripts/proto/__init__.py
  scripts/proto/lbann_modules.py
  scripts/proto/lbann_proto.py
  scripts/proto/resnet50.py
  src/proto/CMakeLists.txt
Labels: enhancement, review requested

#837 Add setup.py for the Python frontend
  scripts/proto/.gitignore
  scripts/proto/README.md
  scripts/proto/examples/resnet50.py
  scripts/proto/lbann/__init__.py
  scripts/proto/lbann/lbann_modules.py
  scripts/proto/lbann/lbann_proto.py
  scripts/proto/setup.py
Labels: enhancement, review requested

#835 support finding HDF5 via the cmake module if not found by config
  CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: bug, build, enhancement, review requested

#834 Make the example LC build script work correctly when building outside…
  scripts/build_lbann_lc.sh
Labels: build, enhancement, review requested

#842 Improving Python implementation of ResNets
  scripts/proto/README.md
  scripts/proto/examples/resnet50.py
  scripts/proto/lbann/lbann_modules.py
  scripts/proto/lbann/lbann_proto.py
  scripts/proto/lbann/models/README.md
  scripts/proto/lbann/models/__init__.py
  scripts/proto/lbann/models/resnet.py
Labels: enhancement, review requested

#828 Remove deprecated objective functions and target layer
  include/lbann/layers/io/CMakeLists.txt
  include/lbann/layers/io/target/CMakeLists.txt
  include/lbann/layers/io/target/generic_target_layer.hpp
  include/lbann/layers/io/target/reconstruction.hpp
  include/lbann/layers/io/target/target_layer.hpp
  include/lbann/lbann.hpp
  include/lbann/metrics/metric.hpp
  include/lbann/objective_functions/CMakeLists.txt
  include/lbann/objective_functions/loss_functions/CMakeLists.txt
  include/lbann/objective_functions/loss_functions/binary_cross_entropy.hpp
  include/lbann/objective_functions/loss_functions/cross_entropy.hpp
  include/lbann/objective_functions/loss_functions/cross_entropy_with_uncertainty.hpp
  include/lbann/objective_functions/loss_functions/geom_negloglike.hpp
  include/lbann/objective_functions/loss_functions/loss_function.hpp
  include/lbann/objective_functions/loss_functions/mean_absolute_deviation.hpp
  include/lbann/objective_functions/loss_functions/mean_absolute_error.hpp
  include/lbann/objective_functions/loss_functions/mean_squared_error.hpp
  include/lbann/objective_functions/loss_functions/poisson_negloglike.hpp
  include/lbann/objective_functions/loss_functions/polya_negloglike.hpp
  include/lbann/objective_functions/weight_regularization/CMakeLists.txt
  include/lbann/objective_functions/weight_regularization/group_lasso.hpp
  include/lbann/objective_functions/weight_regularization/l1.hpp
  scripts/proto/lbann/contrib/__init__.py
  scripts/proto/lbann/contrib/objective_functions.py
  src/callbacks/callback_checknan.cpp
  src/callbacks/callback_checksmall.cpp
  src/callbacks/callback_io.cpp
  src/metrics/layer_metric.cpp
  src/metrics/metric.cpp
  src/objective_functions/CMakeLists.txt
  src/objective_functions/loss_functions/CMakeLists.txt
  src/objective_functions/loss_functions/binary_cross_entropy.cpp
  src/objective_functions/loss_functions/cross_entropy.cpp
  src/objective_functions/loss_functions/cross_entropy_with_uncertainty.cpp
  src/objective_functions/loss_functions/geom_negloglike.cpp
  src/objective_functions/loss_functions/loss_function.cpp
  src/objective_functions/loss_functions/mean_absolute_deviation.cpp
  src/objective_functions/loss_functions/mean_absolute_error.cpp
  src/objective_functions/loss_functions/mean_squared_error.cpp
  src/objective_functions/loss_functions/poisson_negloglike.cpp
  src/objective_functions/loss_functions/polya_negloglike.cpp
  src/objective_functions/weight_regularization/CMakeLists.txt
  src/objective_functions/weight_regularization/group_lasso.cpp
  src/objective_functions/weight_regularization/l1.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/objective_function_factory.cpp
  src/proto/lbann.proto
  viz/properties.txt
  viz/properties_rect.txt
Labels: refactor, review requested

#839 Feature data set metadata
  ReleaseNotes.txt
  include/lbann/proto/init_image_data_readers.hpp
  include/lbann/utils/protobuf_utils.hpp
  model_zoo/models/jag/ae_cycle_gan/data_reader_jag_conduit_lassen.prototext
  model_zoo/models/jag/ae_cycle_gan/data_reader_jag_conduit_lustre.prototext
  model_zoo/models/jag/ae_cycle_gan/jag_100M_metadata.prototext
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  src/utils/protobuf_utils.cpp
Labels: enhancement, review requested

#845 Python implementation of AlexNet
  scripts/proto/lbann/models/.gitignore
  scripts/proto/lbann/models/alexnet.py
  scripts/proto/lbann/models/resnet.py
Labels: enhancement, review requested

#841 Feature simplified conduit paths
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  model_zoo/models/jag/ae_cycle_gan/data_reader_jag_conduit_lassen.prototext
  model_zoo/models/jag/ae_cycle_gan/jag_100M_metadata.prototext
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#840 Updated the spack environment documentation
  CMakeLists.txt
  cmake/modules/SetupMPI.cmake
  cmake/modules/SetupProtobuf.cmake
  docs/BuildingLBANN.md
  model_zoo/jag_utils/compute_min_max_images.cpp
  spack_environments/developer_release_ppc64le_cuda_spack.yaml
  spack_environments/developer_release_x86_64_cuda_spack.yaml
  spack_environments/externals_llnl_lc_cz.yaml
Labels: bug, review requested

#849 Python cleanups and documentation
  scripts/proto/lbann/proto.py
Labels: enhancement
