Repository LLNL/lbann, pull requests merged in 2019-04, with the labels that each got.

#975 Bugfix for data store with bad indices
  include/lbann/data_store/data_store_jag.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
Labels: bug, review requested

#978 Fix WRN stride
  model_zoo/vision/wide_resnet.py
Labels: bug, review requested

#963 Data store preload
  include/lbann/callbacks/callback_dump_outputs.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/sample_list_jag.hpp
  include/lbann/data_readers/sample_list_jag_impl.hpp
  include/lbann/data_store/data_store_jag.hpp
  include/lbann/data_store/generic_data_store.hpp
  include/lbann/models/model.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
  src/data_store/generic_data_store.cpp
  src/models/model.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, in progress, review requested

#976 removing options::has_bool
  include/lbann/utils/options.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann_cycgan.cpp
  src/data_store/generic_data_store.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
  src/utils/options.cpp
  src/utils/stack_profiler.cpp
Labels: enhancement, refactor, review requested

#980 Python data reader bugfixes
  include/lbann/data_readers/data_reader_python.hpp
  src/data_readers/data_reader_python.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: bug, enhancement

#981 Split data store
  include/lbann/callbacks/callback_ltfb.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_store/data_store_jag.hpp
  include/lbann/data_store/generic_data_store.hpp
  src/callbacks/callback_ltfb.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
  src/data_store/generic_data_store.cpp
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#982 Mem check
  include/lbann/data_store/data_store_jag.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
Labels: enhancement, in progress, review requested

#990 Bugfix for thread safe random number generators
  include/lbann/utils/random.hpp
  src/data_readers/cv_augmenter.cpp
  src/data_readers/cv_cropper.cpp
  src/data_readers/data_reader_mesh.cpp
  src/data_readers/data_reader_moving_mnist.cpp
  src/data_readers/data_reader_synthetic.cpp
  src/data_readers/image_preprocessor.cpp
  src/data_readers/patchworks/patchworks.cpp
  src/data_readers/patchworks/patchworks_patch_descriptor.cpp
  src/utils/random.cpp
Labels: bug, review requested

#992 Don't create bias weights with no bias
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  src/layers/learning/fully_connected.cpp
Labels: enhancement, review requested

#984 combine generic_data_store and data_store_jag into a single entity
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_store/CMakeLists.txt
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/data_store/generic_data_store.hpp
  include/lbann/lbann.hpp
  model_zoo/lbann.cpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/CMakeLists.txt
  src/data_store/data_store_conduit.cpp
  src/data_store/generic_data_store.cpp
Labels: refactor, review requested

#996 In-place gradient buffers
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/optimizers/optimizer.hpp
  src/layers/learning/fully_connected.cpp
  src/optimizers/optimizer.cpp
Labels: enhancement, review requested

#998 ResNet cleanup/generalization
  model_zoo/vision/resnet.py
  model_zoo/vision/wide_resnet.py
  python/lbann/contrib/args.py
  python/lbann/contrib/models/__init__.py
  python/lbann/contrib/models/wide_resnet.py
  python/lbann/models/resnet.py
Labels: enhancement, review requested

#991 numpy_conduit_cache class
  include/lbann/data_readers/numpy_conduit_cache.hpp
  model_zoo/jag_utils/CMakeLists.txt
  model_zoo/jag_utils/test_numpy_conduit_cache.cpp
  src/data_readers/CMakeLists.txt
  src/data_readers/numpy_conduit_cache.cpp
  test_numpy_conduit_cache.cpp
Labels: enhancement, review requested

#896 Add `end_lr` field for polynomial weight decay
  include/lbann/callbacks/callback_learning_rate.hpp
  src/callbacks/callback_learning_rate.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#1013 Bugfix LTFB sample list
  src/data_readers/data_reader_jag_conduit.cpp
  src/utils/lbann_library.cpp
Labels: bug

#1006 Bugfix for LTFB to mark data store loaded
  include/lbann/models/model.hpp
  src/callbacks/callback_ltfb.cpp
  src/models/model.cpp
Labels: bug

#1005 data_reader_jag_conduit: more verbose exceptions
  src/data_readers/data_reader_jag_conduit.cpp
Labels: enhancement, review requested

#983 script that adds sample IDs from one list to others. Requested by Sam…
  model_zoo/jag_utils/add_overlap.py
Labels: enhancement, review requested

#1016 Bugfix HDF5 PQ stale data
  include/lbann/data_readers/sample_list_jag.hpp
  include/lbann/data_readers/sample_list_jag_impl.hpp
  src/models/model.cpp
Labels: bug

#1008 Python/experiment support for LSF/Lassen
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  model_zoo/vision/resnet.py
  python/lbann/contrib/args.py
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/paths.py
  python/lbann/contrib/lc/systems.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/lsf.py
  python/lbann/launcher/slurm.py
Labels: enhancement, python, review requested

#997 Parallelism in Python data reader
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_python.hpp
  src/data_readers/data_reader_python.cpp
Labels: enhancement, review requested

#979 LTFB sendrecv_weights algorithm will communicate optimizer hyperparameters
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/sgd.hpp
  src/callbacks/callback_ltfb.cpp
Labels: enhancement, review requested

#1015 Hacked bugfix for sendrecv bug in MVAPICH2-2.3.
  experiments/run_lbann_aecycgan_experiment.sh
  experiments/run_lbann_cycgan_experiment.sh
  experiments/run_lbann_cycgan_inference.sh
  experiments/run_lbann_experiment.sh
  python/lbann/contrib/lc/launcher.py
Labels: bug, review requested

#1009 Autotune cuDNN convolution algorithms
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/utils/cudnn.hpp
  src/utils/cudnn.cpp
Labels: enhancement, review requested

#1021 Fix build error from #1009
  src/utils/cudnn.cpp
Labels: bug, review requested

#1022 Bugfix for im2col convolution
  include/lbann/layers/learning/base_convolution.hpp
Labels: bug, review requested

#1023 Update build script on Pascal
  scripts/build_lbann_lc.sh
Labels: bug, review requested

#1017 data_store/data_reader refactor
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/utils/lbann_library.cpp
Labels: refactor, review requested

#1025 Fixed a bug in how the data store is being loaded during the
  include/lbann/callbacks/callback_debug_io.hpp
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/models/model.hpp
  src/callbacks/callback_ltfb.cpp
  src/data_readers/data_reader.cpp
  src/data_store/data_store_conduit.cpp
  src/models/model.cpp
Labels: bug
