Repository LLNL/lbann, pull requests merged in 2019-07, with the labels that each got.

#1107 Option to specify device for layers in Python frontend
  python/lbann/layer.py
Labels: enhancement, python, review requested

#1106 Embedding layer
  include/lbann/layers/learning/CMakeLists.txt
  include/lbann/layers/learning/embedding.hpp
  include/lbann/lbann.hpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/embedding.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#1109 Cleanup exception handling
  include/lbann/utils/opencv.hpp
  model_zoo/jag_utils/check_for_duplicate_samples.cpp
  model_zoo/jag_utils/check_images.cpp
  model_zoo/jag_utils/extract_random_samples.cpp
  model_zoo/jag_utils/generate_corrupt_samples.cpp
  model_zoo/jag_utils/load_balance.cpp
Labels: bug, build, review requested

#1108 Moving "check gradients" callback to end of test phase
  include/lbann/callbacks/callback_check_gradients.hpp
  src/callbacks/callback_check_gradients.cpp
Labels: review requested

#1110 LSTM module takes previous state as argument
  python/lbann/modules.py
Labels: enhancement, python, review requested

#1114 Fuse batchnorm allreduces in FP/BP
  include/lbann/layers/regularizers/batch_normalization.hpp
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
Labels: enhancement, review requested

#1116 Fixing the warnings raised by latest clang
  include/lbann/base.hpp
  include/lbann/callbacks/callback_checksmall.hpp
  include/lbann/callbacks/callback_perturb_adam.hpp
  include/lbann/callbacks/callback_perturb_dropout.hpp
  include/lbann/callbacks/callback_variable_minibatch.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  include/lbann/layers/activations/elu.hpp
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/embedding.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/math/clamp.hpp
  include/lbann/layers/misc/covariance.hpp
  include/lbann/layers/misc/variance.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/in_top_k.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/sort.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/transforms/normalize.hpp
  include/lbann/transforms/repack_HWC_to_CHW_layout.hpp
  include/lbann/transforms/vision/normalize_to_lbann_layout.hpp
  include/lbann/transforms/vision/to_lbann_layout.hpp
  include/lbann/weights/initializer.hpp
  include/lbann/weights/variance_scaling_initializers.hpp
  src/callbacks/callback_checksmall.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/optimizers/adagrad.cpp
  src/optimizers/adam.cpp
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/sgd.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
  src/weights/initializer.cpp
  src/weights/variance_scaling_initializers.cpp
Labels: build, review requested

#1119 Grouped batchnorm statistics
  include/lbann/comm.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  model_zoo/vision/resnet.py
  python/lbann/contrib/models/wide_resnet.py
  python/lbann/models/resnet.py
  src/comm.cpp
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#1122 Channel-wise scale/bias layer
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/lbann.hpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/channelwise_scale_bias.cpp
  src/layers/learning/channelwise_scale_bias.cu
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#1124 Fixing bug when parsing list of execution modes
  src/base.cpp
Labels: bug

#1126 Add parse list test
  CMakeLists.txt
  include/lbann/proto/proto_common.hpp
  src/base.cpp
  src/proto/proto_common.cpp
  src/proto/unit_test/CMakeLists.txt
  src/proto/unit_test/parse_list_test.cpp
  src/proto/unit_test/parse_set_test.cpp
  src/proto/unit_test/trim_test.cpp
Labels: bug, enhancement, review requested

#1129 Disable signal handler in Python worker processes
  src/data_readers/data_reader_python.cpp
Labels: bug, review requested

#1051 local cache: shared memory segment
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_store/data_store_conduit.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1132 remove a warning about a missing override
  include/lbann/layers/learning/entrywise_scale_bias.hpp
Labels: review requested

#1131 update the proto inputs
  src/proto/CMakeLists.txt
Labels: bug, review requested
