Repository LLNL/lbann, pull requests merged in 2019-02, with the labels that each got.

#850 Updating the documentation for building with spack
  docs/BuildingLBANN.md
Labels: enhancement, in progress

#848 ONNX support
  scripts/proto/.gitignore
  scripts/proto/README.md
  scripts/proto/docs/onnx/README.md
  scripts/proto/docs/onnx/l2o.md
  scripts/proto/docs/onnx/o2l.md
  scripts/proto/docs/onnx/support_status.md
  scripts/proto/docs/onnx/viz/l2o/alexnet/alexnet_lbann.pdf
  scripts/proto/docs/onnx/viz/l2o/alexnet/alexnet_lbann.png
  scripts/proto/docs/onnx/viz/l2o/alexnet/alexnet_onnx_netron.png
  scripts/proto/docs/onnx/viz/l2o/mnist/mnist_lbann.pdf
  scripts/proto/docs/onnx/viz/l2o/mnist/mnist_lbann.png
  scripts/proto/docs/onnx/viz/l2o/mnist/mnist_onnx_netron.png
  scripts/proto/docs/onnx/viz/l2o/mnist/mnist_onnx_netron_name.png
  scripts/proto/docs/onnx/viz/l2o/resnet50/resnet50_lbann.pdf
  scripts/proto/docs/onnx/viz/l2o/resnet50/resnet50_lbann.png
  scripts/proto/docs/onnx/viz/l2o/resnet50/resnet50_onnx_netron.png
  scripts/proto/examples/onnx/lbann2onnx.py
  scripts/proto/examples/onnx/onnx2lbann.py
  scripts/proto/lbann/onnx/__init__.py
  scripts/proto/lbann/onnx/l2o/__init__.py
  scripts/proto/lbann/onnx/l2o/layers/__init__.py
  scripts/proto/lbann/onnx/l2o/layers/learnings.py
  scripts/proto/lbann/onnx/l2o/layers/losses.py
  scripts/proto/lbann/onnx/l2o/layers/math.py
  scripts/proto/lbann/onnx/l2o/layers/regularizers.py
  scripts/proto/lbann/onnx/l2o/layers/transforms.py
  scripts/proto/lbann/onnx/l2o/util.py
  scripts/proto/lbann/onnx/o2l/__init__.py
  scripts/proto/lbann/onnx/o2l/layers/__init__.py
  scripts/proto/lbann/onnx/o2l/layers/learnings.py
  scripts/proto/lbann/onnx/o2l/layers/math.py
  scripts/proto/lbann/onnx/o2l/layers/regularizers.py
  scripts/proto/lbann/onnx/o2l/layers/transforms.py
  scripts/proto/lbann/onnx/parserDescriptor.py
  scripts/proto/lbann/onnx/tests/__init__.py
  scripts/proto/lbann/onnx/tests/lbann2onnx_layer_test.py
  scripts/proto/lbann/onnx/tests/lbann2onnx_test.py
  scripts/proto/lbann/onnx/tests/onnx2lbann_layer_test.py
  scripts/proto/lbann/onnx/tests/onnx2lbann_test.py
  scripts/proto/lbann/onnx/tests/util.py
  scripts/proto/lbann/onnx/util.py
  scripts/proto/lbann/proto.py
  scripts/proto/scripts/onnx/create_support_status.py
  scripts/proto/scripts/onnx/download_onnx_model_zoo.sh
  scripts/proto/setup.py
Labels: enhancement, review requested

#770 Add factory template
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/factory.hpp
  include/lbann/utils/factory_error_policies.hpp
  include/lbann/utils/memory.hpp
Labels: enhancement, review requested

#856 Merge lbplot to the Python interface
  scripts/lbplot/README.md
  scripts/lbplot/install.sh
  scripts/lbplot/requirements.txt
  scripts/lbplot/setup.py
  scripts/lbplot/src/script/lbplot
  scripts/lbplot/test.sh
  scripts/proto/README.md
  scripts/proto/docs/onnx/README.md
  scripts/proto/docs/plot/README.md
  scripts/proto/examples/plot/data/fmow_final_sgd_1e-3_1node.out
  scripts/proto/examples/plot/data/fmow_res_sgd_1e-3_1gpu.2.out
  scripts/proto/examples/plot/data/fmow_res_sgd_1e-3_1gpu.out
  scripts/proto/examples/plot/data/fmow_res_sgd_1e-3_proc_1gpu.out
  scripts/proto/examples/plot/data/fmow_res_sgd_1e-3_proc_1node.out
  scripts/proto/examples/plot/data/pascal_2_stats_res_sgd.json
  scripts/proto/examples/plot/data/pascal_2_stats_sgd.json
  scripts/proto/examples/plot/data/pascal_res_sgd_1e-3_1gpu.json
  scripts/proto/examples/plot/data/pascal_res_sgd_1e-3_orig_1node.json
  scripts/proto/examples/plot/data/pascal_res_sgd_1e-3_proc_1gpu.json
  scripts/proto/examples/plot/data/pascal_res_sgd_1e-3_proc_1node.json
  scripts/proto/examples/plot/test.sh
  scripts/proto/lbann/plot/__init__.py
  scripts/proto/lbann/plot/parser.py
  scripts/proto/lbann/plot/plot.py
  scripts/proto/scripts/plot/lbplot
  scripts/proto/setup.py
Labels: enhancement, refactor

#865 Model class for the Python frontend
  scripts/proto/lbann/proto.py
Labels: enhancement

#862 Some updates to the documentation
  README.md
  docs/BuildingLBANN.md
  docs/RunningLBANN.md
  docs/conf.py
  docs/getting_started.rst
Labels: documentation, enhancement, review requested

#868 Merge viz.py to the Python interface
  scripts/proto/MANIFEST.in
  scripts/proto/README.md
  scripts/proto/docs/viz/README.md
  scripts/proto/examples/viz/README.md
  scripts/proto/examples/viz/rnn_1.jpg
  scripts/proto/examples/viz/rnn_1.pdf
  scripts/proto/examples/viz/rnn_1a.pdf
  scripts/proto/examples/viz/rnn_2.pdf
  scripts/proto/examples/viz/rnn_3.jpg
  scripts/proto/examples/viz/rnn_3.pdf
  scripts/proto/examples/viz/rnn_4.pdf
  scripts/proto/lbann/proto.py
  scripts/proto/lbann/viz/__init__.py
  scripts/proto/lbann/viz/layer.py
  scripts/proto/lbann/viz/properties/__init__.py
  scripts/proto/lbann/viz/properties/properties.txt
  scripts/proto/lbann/viz/properties/properties_rect.txt
  scripts/proto/scripts/viz/lbviz
  scripts/proto/setup.py
  viz/.gitignore
  viz/README
  viz/examples/README
  viz/viz.py
Labels: enhancement, refactor

#857 Update hydrogen comm changes
  CMakeLists.txt
  include/lbann/comm.hpp
  src/comm.cpp
  src/data_readers/data_reader_csv.cpp
  src/data_readers/data_reader_pilot2_molecular.cpp
  src/data_store/generic_data_store.cpp
Labels: enhancement, review requested

#836 Models store layers in smart pointers
  include/lbann/models/directed_acyclic_graph.hpp
  include/lbann/models/model.hpp
  include/lbann/proto/factories.hpp
  include/lbann/utils/graph.hpp
  src/models/directed_acyclic_graph.cpp
  src/models/model.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/model_factory.cpp
  src/utils/graph.cpp
Labels: refactor, review requested

#879 Replacing AbsMat::operator*= with El::Scale.
  include/lbann/layers/regularizers/dropout.hpp
  src/data_readers/image_preprocessor.cpp
  src/utils/statistics.cpp
  src/weights/weights.cpp
Labels: bug

#869 Optimizing the implementation of the new Conduit-based generic data store
  include/lbann/data_store/data_store_jag.hpp
  include/lbann/data_store/generic_data_store.hpp
  include/lbann/utils/file_utils.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
  src/data_store/generic_data_store.cpp
Labels: help wanted, review requested

#889 remove code associated with data_reader_jag_conduit_hdf5
  include/lbann/data_store/jag_io.hpp
  include/lbann/data_store/jag_store.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_jag_conduit_hdf5.cpp
  src/data_store/CMakeLists.txt
  src/data_store/jag_converter.cpp
  src/data_store/jag_io.cpp
  src/data_store/jag_store.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/lbann.proto
Labels: in progress, refactor

#877 Data reader store refresh
  include/lbann/CMakeLists.txt
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_csv.hpp
  include/lbann/data_readers/data_reader_imagenet.hpp
  include/lbann/data_readers/data_reader_imagenet_patches.hpp
  include/lbann/data_readers/data_reader_merge_features.hpp
  include/lbann/data_readers/data_reader_merge_samples.hpp
  include/lbann/data_readers/data_reader_mnist_siamese.hpp
  include/lbann/data_readers/data_reader_multi_images.hpp
  include/lbann/data_readers/data_reader_pilot2_molecular.hpp
  include/lbann/data_readers/data_reader_triplet.hpp
  include/lbann/data_store/CMakeLists.txt
  include/lbann/data_store/data_store_csv.hpp
  include/lbann/data_store/data_store_image.hpp
  include/lbann/data_store/data_store_imagenet.hpp
  include/lbann/data_store/data_store_imagenet_patches.hpp
  include/lbann/data_store/data_store_merge_features.hpp
  include/lbann/data_store/data_store_merge_samples.hpp
  include/lbann/data_store/data_store_multi_images.hpp
  include/lbann/data_store/data_store_pilot2_molecular.hpp
  include/lbann/data_store/data_store_triplet.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/lbann.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_csv.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_readers/data_reader_imagenet_patches.cpp
  src/data_readers/data_reader_merge_features.cpp
  src/data_readers/data_reader_merge_samples.cpp
  src/data_readers/data_reader_mnist_siamese.cpp
  src/data_readers/data_reader_multi_images.cpp
  src/data_readers/data_reader_pilot2_molecular.cpp
  src/data_readers/data_reader_triplet.cpp
  src/data_store/CMakeLists.txt
  src/data_store/data_store_csv.cpp
  src/data_store/data_store_image.cpp
  src/data_store/data_store_imagenet.cpp
  src/data_store/data_store_imagenet_patches.cpp
  src/data_store/data_store_merge_features.cpp
  src/data_store/data_store_merge_samples.cpp
  src/data_store/data_store_multi_images.cpp
  src/data_store/data_store_pilot2_molecular.cpp
  src/data_store/data_store_triplet.cpp
  src/data_store/generic_data_store.cpp
Labels: refactor

#891 Data Store Hang
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
Labels: bug

#892 GPU implementation of RMSprop
  include/lbann/optimizers/rmsprop.hpp
  src/optimizers/CMakeLists.txt
  src/optimizers/rmsprop.cpp
  src/optimizers/rmsprop.cu
Labels: enhancement, review requested

#901 Removed the header file for the deprecated
  include/lbann/data_readers/data_reader_jag_conduit_hdf5.hpp
  include/lbann/lbann.hpp
Labels: bug, review requested

#902 Correcting modulo arithmetic to correct for mini-batch size
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_store/data_store_jag.hpp
  include/lbann/data_store/generic_data_store.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
  src/data_store/generic_data_store.cpp
  src/utils/lbann_library.cpp
Labels: bug, review requested

#903 Refactoring optimizers
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/transform/weights.hpp
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  src/layers/learning/fully_connected.cpp
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/optimizers/adagrad.cpp
  src/optimizers/adagrad.cu
  src/optimizers/adam.cpp
  src/optimizers/adam.cu
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/optimizer.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/rmsprop.cu
  src/optimizers/sgd.cpp
  src/optimizers/sgd.cu
  src/weights/weights.cpp
Labels: refactor, review requested

#854 NumPy .npz data reader
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_merge_samples.hpp
  include/lbann/data_readers/data_reader_numpy_npz.hpp
  include/lbann/lbann.hpp
  model_zoo/data_readers/data_reader_mnist_numpy_npz_int16.prototext
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_numpy_npz.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
  tools/mnist/.gitignore
  tools/mnist/mnist_to_npy_and_npz.py
Labels: enhancement, review requested

#888 Some more smart pointers and enhanced exception safety
  include/lbann/base.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/utils/lbann_library.hpp
  include/lbann/utils/protobuf_utils.hpp
  model_zoo/jag_utils/build_index.cpp
  model_zoo/jag_utils/build_sample_id_mapping.cpp
  model_zoo/jag_utils/check_for_duplicate_samples.cpp
  model_zoo/jag_utils/check_images.cpp
  model_zoo/jag_utils/compute_min_max_images.cpp
  model_zoo/jag_utils/compute_per_channel_image_avg_min_max.cpp
  model_zoo/jag_utils/detect_corruption.cpp
  model_zoo/jag_utils/dump_bundle.cpp
  model_zoo/jag_utils/extract_random_samples.cpp
  model_zoo/jag_utils/load_balance.cpp
  model_zoo/jag_utils/load_bundle2raw.cpp
  model_zoo/jag_utils/select_samples.cpp
  model_zoo/jag_utils/test_conduit_hdf5.cpp
  model_zoo/jag_utils/test_conduit_with_mpi.cpp
  model_zoo/jag_utils/test_mpi.cpp
  model_zoo/lbann.cpp
  model_zoo/lbann2.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_inf.cpp
  src/base.cpp
  src/models/model.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
  src/utils/protobuf_utils.cpp
  tests/test_shuffled_indices.cpp
Labels: enhancement, review requested
