Repository LLNL/lbann, pull requests merged in 2019-08, with the labels that each got.

#1139 change 'int' to 'size_t' to accommodate large sample sizes
  include/lbann/data_store/data_store_conduit.hpp
  src/data_store/data_store_conduit.cpp
Labels: enhancement, review requested

#1143 remove sync_selected callback and all references to it
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/sync_selected.hpp
  include/lbann/layers/layer.hpp
  include/lbann/lbann.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/sync_selected.cpp
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
Labels: bug, review requested

#1137 Refactor weights factory
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/transform/weights.hpp
  include/lbann/proto/factories.hpp
  include/lbann/weights/initializer.hpp
  include/lbann/weights/variance_scaling_initializers.hpp
  include/lbann/weights/weights.hpp
  src/proto/factories/callback_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/weights_factory.cpp
  src/weights/initializer.cpp
  src/weights/variance_scaling_initializers.cpp
  src/weights/weights.cpp
Labels: bug, refactor, review requested

#1138 Refactor optimizer factory
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  include/lbann/proto/factories.hpp
  src/optimizers/adagrad.cpp
  src/optimizers/adam.cpp
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/sgd.cpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/optimizer_factory.cpp
  src/proto/factories/weights_factory.cpp
Labels: refactor, review requested

#1140 Refactor transform factory
  include/lbann/transforms/normalize.hpp
  include/lbann/transforms/sample_normalize.hpp
  include/lbann/transforms/scale.hpp
  include/lbann/transforms/transform_pipeline.hpp
  include/lbann/transforms/vision/adjust_brightness.hpp
  include/lbann/transforms/vision/adjust_contrast.hpp
  include/lbann/transforms/vision/adjust_saturation.hpp
  include/lbann/transforms/vision/center_crop.hpp
  include/lbann/transforms/vision/color_jitter.hpp
  include/lbann/transforms/vision/colorize.hpp
  include/lbann/transforms/vision/cutout.hpp
  include/lbann/transforms/vision/grayscale.hpp
  include/lbann/transforms/vision/horizontal_flip.hpp
  include/lbann/transforms/vision/normalize_to_lbann_layout.hpp
  include/lbann/transforms/vision/random_affine.hpp
  include/lbann/transforms/vision/random_crop.hpp
  include/lbann/transforms/vision/random_resized_crop.hpp
  include/lbann/transforms/vision/random_resized_crop_with_fixed_aspect_ratio.hpp
  include/lbann/transforms/vision/resize.hpp
  include/lbann/transforms/vision/resized_center_crop.hpp
  include/lbann/transforms/vision/to_lbann_layout.hpp
  include/lbann/transforms/vision/vertical_flip.hpp
  src/proto/factories/transform_factory.cpp
  src/transforms/normalize.cpp
  src/transforms/sample_normalize.cpp
  src/transforms/scale.cpp
  src/transforms/vision/adjust_brightness.cpp
  src/transforms/vision/adjust_contrast.cpp
  src/transforms/vision/adjust_saturation.cpp
  src/transforms/vision/center_crop.cpp
  src/transforms/vision/color_jitter.cpp
  src/transforms/vision/colorize.cpp
  src/transforms/vision/cutout.cpp
  src/transforms/vision/grayscale.cpp
  src/transforms/vision/horizontal_flip.cpp
  src/transforms/vision/normalize_to_lbann_layout.cpp
  src/transforms/vision/random_affine.cpp
  src/transforms/vision/random_crop.cpp
  src/transforms/vision/random_resized_crop.cpp
  src/transforms/vision/random_resized_crop_with_fixed_aspect_ratio.cpp
  src/transforms/vision/resize.cpp
  src/transforms/vision/resized_center_crop.cpp
  src/transforms/vision/to_lbann_layout.cpp
  src/transforms/vision/vertical_flip.cpp
Labels: refactor, review requested

#1145 Refactor model factory
  include/lbann/proto/factories.hpp
  include/lbann/utils/exception.hpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/objective_function_factory.cpp
  src/utils/lbann_library.cpp
Labels: refactor, review requested

#1149 use realpaths instead of abspaths in setup.py
  cmake/configure_files/setup.py.in
Labels: bug, review requested

#1144 Fix an issue on OSX in which nonportable pthread features are not available
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  docs/build_osx.rst
  include/lbann/utils/threads/thread_pool.hpp
  include/lbann/utils/threads/thread_safe_queue.hpp
  include/lbann/utils/threads/thread_utils.hpp
  include/lbann/utils/threads/type_erased_function.hpp
  src/utils/threads/CMakeLists.txt
  src/utils/threads/thread_pool.cpp
Labels: bug, review requested

#1156 Fix the tests prototexts
  model_zoo/tests/layer_tests/model_channelwise_mean.prototext
  model_zoo/tests/layer_tests/model_clamp.prototext
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_elu.prototext
  model_zoo/tests/layer_tests/model_identity.prototext
  model_zoo/tests/layer_tests/model_l1_norm.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_leaky_relu.prototext
  model_zoo/tests/layer_tests/model_log_sigmoid.prototext
  model_zoo/tests/layer_tests/model_log_softmax.prototext
  model_zoo/tests/layer_tests/model_mean_absolute_error.prototext
  model_zoo/tests/layer_tests/model_relu.prototext
  model_zoo/tests/layer_tests/model_selu.prototext
  model_zoo/tests/layer_tests/model_sigmoid.prototext
  model_zoo/tests/layer_tests/model_softmax.prototext
  model_zoo/tests/layer_tests/model_softplus.prototext
  model_zoo/tests/layer_tests/model_softsign.prototext
  model_zoo/tests/layer_tests/model_squared_difference.prototext
  model_zoo/tests/layer_tests/model_tessellate.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
  model_zoo/tests/model_mnist_conv_graph.prototext
Labels: bug, review requested

#1155 Refactoring LBANN_ERROR to make it more flexible.
  include/lbann/utils/cublas.hpp
  include/lbann/utils/exception.hpp
  src/proto/factories/model_factory.cpp
Labels: refactor, review requested

#1158 Fix unit test error related to empty optimizer messages
  include/lbann/proto/helpers.hpp
  src/proto/factories/weights_factory.cpp
  src/proto/helpers.cpp
Labels: bug, review requested

#1160 update to HDF5's sudden deprecation of boolean API version options
  superbuild/hdf5/CMakeLists.txt
Labels: bug, build, review requested

#1163 Minor tweaks in entry-wise scale/bias layer.
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  src/layers/learning/entrywise_scale_bias.cpp
  src/layers/learning/entrywise_scale_bias.cu
Labels: bug

#1161 Protobuf message for no optimizer
  model_zoo/models/gan/mnist/adversarial_model.prototext
  model_zoo/models/gan/mnist/discriminator_model.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  model_zoo/tests/layer_tests/model_tessellate.prototext
  python/lbann/__init__.py
  python/lbann/proto.py
  src/proto/factories/optimizer_factory.cpp
  src/proto/optimizers.proto
Labels: enhancement, review requested

#1165 pin conduit version to v0.4.0
  superbuild/conduit/CMakeLists.txt
Labels: bug, build

#1162 Check gradient callback can be applied at any execution mode
  include/lbann/callbacks/check_gradients.hpp
  model_zoo/tests/layer_tests/model_channelwise_mean.prototext
  model_zoo/tests/layer_tests/model_clamp.prototext
  model_zoo/tests/layer_tests/model_covariance.prototext
  model_zoo/tests/layer_tests/model_elu.prototext
  model_zoo/tests/layer_tests/model_identity.prototext
  model_zoo/tests/layer_tests/model_l1_norm.prototext
  model_zoo/tests/layer_tests/model_l2_norm2.prototext
  model_zoo/tests/layer_tests/model_leaky_relu.prototext
  model_zoo/tests/layer_tests/model_log_sigmoid.prototext
  model_zoo/tests/layer_tests/model_log_softmax.prototext
  model_zoo/tests/layer_tests/model_mean_absolute_error.prototext
  model_zoo/tests/layer_tests/model_relu.prototext
  model_zoo/tests/layer_tests/model_selu.prototext
  model_zoo/tests/layer_tests/model_sigmoid.prototext
  model_zoo/tests/layer_tests/model_softmax.prototext
  model_zoo/tests/layer_tests/model_softplus.prototext
  model_zoo/tests/layer_tests/model_softsign.prototext
  model_zoo/tests/layer_tests/model_squared_difference.prototext
  model_zoo/tests/layer_tests/model_tessellate.prototext
  model_zoo/tests/layer_tests/model_variance.prototext
  model_zoo/tests/model_mnist_conv_graph.prototext
  model_zoo/tests/model_mnist_ridge_regression.prototext
  model_zoo/tests/model_mnist_softmax_classifier.prototext
  src/callbacks/check_gradients.cpp
  src/proto/callbacks.proto
Labels: enhancement, review requested

#1153 bug fixes for data_store_conduit for the mode: --preload_data_store. …
  include/lbann/data_readers/data_reader.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_ascii.cpp
  src/data_readers/data_reader_cifar10.cpp
  src/data_readers/data_reader_csv.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_merge_features.cpp
  src/data_readers/data_reader_merge_samples.cpp
  src/data_readers/data_reader_mesh.cpp
  src/data_readers/data_reader_mnist.cpp
  src/data_readers/data_reader_moving_mnist.cpp
  src/data_readers/data_reader_multi_images.cpp
  src/data_readers/data_reader_multihead_siamese.cpp
  src/data_readers/data_reader_numpy.cpp
  src/data_readers/data_reader_numpy_npz.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_readers/data_reader_pilot2_molecular.cpp
  src/data_readers/data_reader_python.cpp
  src/data_readers/data_reader_synthetic.cpp
  src/data_readers/data_reader_triplet.cpp
  src/data_store/data_store_conduit.cpp
Labels: bug, refactor, review requested

#1164 Allow no initializer specified in weights object
  src/proto/factories/weights_factory.cpp
Labels: bug, review requested

#1167 Entry-wise batchnorm
  include/lbann/layers/regularizers/CMakeLists.txt
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/lbann.hpp
  src/layers/regularizers/CMakeLists.txt
  src/layers/regularizers/entrywise_batch_normalization.cpp
  src/layers/regularizers/entrywise_batch_normalization.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1170 Destroy embedded Python session during LBANN finalization
  include/lbann/utils/python.hpp
  src/base.cpp
  src/data_readers/data_reader_python.cpp
  src/utils/python.cpp
Labels: bug

#1172 Fixing incorrect parentheses in entry-wise batchnorm
  src/layers/regularizers/entrywise_batch_normalization.cpp
  src/layers/regularizers/entrywise_batch_normalization.cu
Labels: bug

#1173 expose options for offline builds of all superbuild packages
  superbuild/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/cereal/CMakeLists.txt
  superbuild/cnpy/CMakeLists.txt
  superbuild/conduit/CMakeLists.txt
  superbuild/cub/CMakeLists.txt
  superbuild/hdf5/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/jpeg-turbo/CMakeLists.txt
  superbuild/openblas/CMakeLists.txt
  superbuild/opencv/CMakeLists.txt
  superbuild/protobuf/CMakeLists.txt
Labels: build, review requested

#1171 add the summarizer to the model class in the python front-end
  python/lbann/model.py
Labels: bug, review requested

#1174 add tmp and stamp dirs for openblas
  superbuild/openblas/CMakeLists.txt
Labels: bug, review requested

#1179 silence gcc warning by initializing a variable
  src/data_store/data_store_conduit.cpp
Labels: bug, build, review requested

#1180 install select_samples; simplify CMake targets
  model_zoo/jag_utils/CMakeLists.txt
Labels: build, review requested

#1182 update missed prototext
  bamboo/unit_tests/prototext/model_mnist_simple_1.prototext
  bamboo/unit_tests/prototext/model_mnist_simple_2.prototext
Labels: bug

#1190 Remove "moving MNIST" data reader
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_moving_mnist.hpp
  include/lbann/lbann.hpp
  model_zoo/data_readers/data_reader_moving_mnist.prototext
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_moving_mnist.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
Labels: review requested

#1191 Remove ASCII data reader
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_ascii.hpp
  include/lbann/lbann.hpp
  model_zoo/data_readers/data_reader_ascii.prototext
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_ascii.cpp
Labels: review requested

#1175 Build sample lists optimization
  include/lbann/layers/io/input/generic_input_layer.hpp
  model_zoo/jag_utils/CMakeLists.txt
  model_zoo/jag_utils/python/README.txt
  model_zoo/jag_utils/python/build_trainer_lists.py
  model_zoo/jag_utils/python/sanity.py
  model_zoo/jag_utils/python/shuffle.py
  model_zoo/jag_utils/select_samples.cpp
Labels: enhancement, in progress, refactor

#1195 Add non-CUB implementation of channel-wise scale/bias layer
  src/layers/learning/channelwise_scale_bias.cu
Labels: bug, review requested
