Repository LLNL/lbann, pull requests merged in 2019-10, with the labels that each got.

#1278 Fix bug in GPU not-equal layer
  src/layers/math/binary.cu
Labels: bug

#1270 Get Bamboo to turn green
  bamboo/allocate_and_run.sh
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script.sh
  bamboo/compiler_tests/test_compiler.py
  bamboo/run.sh
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_datareader_python.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
  include/lbann/callbacks/checkpoint.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  model_zoo/lbann2.cpp
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/systems.py
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
Labels: CI, enhancement, review requested

#1279 Add threading to data_reader_numpy_npz_conduit::preload_data_store()
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_readers/numpy_conduit_converter.cpp
Labels: enhancement, review requested

#1282 Clean up Ray and Corona testing time
  bamboo/run.sh
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
Labels: CI, enhancement, review requested

#1283 Performance tuning for explicit sample list
  include/lbann/data_readers/sample_list_open_files.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
Labels: enhancement

#1285 Modified linear search through a vector to a map lookup
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  src/data_readers/data_reader_jag_conduit.cpp
Labels: enhancement, review requested

#1286 Add Catch2 tests for embedded Python session
  include/lbann/utils/python.hpp
  src/utils/python.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/python_test.cpp
Labels: CI, review requested

#1288 Fix for case where global archive size is > INT_MAX
  include/lbann/data_readers/sample_list.hpp
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
Labels: bug, review requested

#1298 Cleanup entrywise layer macros to facilitate templating
  include/lbann/layers/activations/activations.hpp
  include/lbann/layers/loss/entrywise.hpp
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/math/unary.hpp
Labels: refactor, review requested

#1304 Creating a new application directory hierarchy.
  applications/.gitignore
  applications/ATOM/README.md
  applications/CONTRIBUTING.md
  applications/README.md
Labels: refactor, review requested

#1263 Make jag-utils optional in the build/install
  docs/build_with_cmake.rst
  model_zoo/jag_utils/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: build, enhancement, review requested

#1308 Revert "Make jag-utils optional in the build/install"
  docs/build_with_cmake.rst
  model_zoo/jag_utils/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: bug

#1303 Utility functions for hashing
  include/lbann/trainers/trainer.hpp
  include/lbann/utils/hash.hpp
  src/utils/random.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/hash_test.cpp
Labels: refactor, review requested

#1309 Redo of #1263
  docs/build_with_cmake.rst
  model_zoo/jag_utils/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: build, enhancement, review requested

#1292 Support "optional" message fields in Protobuf API
  python/lbann/util/class_generator.py
Labels: python, review requested

#1310 Add a hacky workaround to get OSX build to go through.
  CMakeLists.txt
Labels: bug, build, review requested

#1293 Memory optimization for data_reader_numpy_npz_conduit
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  include/lbann/data_readers/numpy_conduit_converter.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_readers/numpy_conduit_converter.cpp
Labels: enhancement, review requested

#1311 Fix model copy issue
  include/lbann/layers/io/input/generic_input_layer.hpp
Labels: bug, review requested

#1300 Embedding layer with padding index
  bamboo/unit_tests/test_unit_layer_embedding.py
  include/lbann/layers/learning/embedding.hpp
  src/layers/learning/embedding.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/weights/weights.cpp
Labels: enhancement, review requested

#1307 Tinkering with MPI launch invocations
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/lsf.py
Labels: bug, enhancement, python, review requested

#1316 Remove "ckpt_*" directories before running lenet checkpoint tests
  bamboo/unit_tests/test_unit_checkpoint.py
Labels: CI, bug, review requested

#1318 Bugfix for softmax and log-softmax layers
  bamboo/unit_tests/test_unit_datareader_python.py
  bamboo/unit_tests/test_unit_layer_argmax.py
  bamboo/unit_tests/test_unit_layer_argmin.py
  bamboo/unit_tests/test_unit_layer_channelwise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_convolution.py
  bamboo/unit_tests/test_unit_layer_cross_entropy.py
  bamboo/unit_tests/test_unit_layer_embedding.py
  bamboo/unit_tests/test_unit_layer_entrywise_batch_normalization.py
  bamboo/unit_tests/test_unit_layer_entrywise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_fully_connected.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_squared_error.py
  bamboo/unit_tests/test_unit_layer_one_hot.py
  bamboo/unit_tests/test_unit_layer_slice.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  include/lbann/layers/activations/softmax.hpp
  include/lbann/utils/cuda.hpp
  include/lbann/utils/impl/cuda.hpp
  src/layers/activations/log_softmax.cpp
  src/layers/activations/log_softmax.cu
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
  src/proto/layers.proto
Labels: bug, review requested

#1321 Refactor Bamboo helper function for Python frontend
  bamboo/clean.sh
  bamboo/common_python/tools.py
  bamboo/integration_tests/experiments/.gitignore
  bamboo/unit_tests/test_unit_datareader_python.py
  bamboo/unit_tests/test_unit_layer_argmax.py
  bamboo/unit_tests/test_unit_layer_channelwise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_embedding.py
  bamboo/unit_tests/test_unit_layer_entrywise_batch_normalization.py
  bamboo/unit_tests/test_unit_layer_entrywise_scale_bias.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_one_hot.py
  bamboo/unit_tests/test_unit_layer_slice.py
  bamboo/unit_tests/test_unit_layer_softmax.py
Labels: CI, refactor

#1323 Fix saving of the common RNG states for distributed checkpointing
  include/lbann/utils/random.hpp
  src/models/model.cpp
  src/utils/random.cpp
Labels: bug, review requested

#1322 Bamboo integration tests using Python frontend (attempt 2)
  bamboo/allocate_and_run.sh
  bamboo/clean.sh
  bamboo/full_alexnet_clang6/README.md
  bamboo/full_alexnet_gcc7/README.md
  bamboo/full_alexnet_intel19/README.md
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/error/.gitignore
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/gcc7/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/gcc7/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/gcc7/expected_performance.csv
  bamboo/integration_tests/expected_values/corona/gcc7/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/corona/gcc7/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/corona/gcc7/expected_performance.csv
  bamboo/integration_tests/expected_values/lassen/gcc7/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/lassen/gcc7/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/lassen/gcc7/expected_performance.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_performance.csv
  bamboo/integration_tests/full_alexnet.sh
  bamboo/integration_tests/output/.gitignore
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_lenet.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/integration_tests/test_integration_resnet50.py
  bamboo/run.sh
  python/lbann/contrib/lc/paths.py
Labels: CI, refactor, review requested

#1326 Fix compilation error in softmax layer
  src/layers/activations/softmax.cpp
Labels: bug, review requested

#1313 Data spill and checkpoint
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_store/data_store_conduit.cpp
  src/models/model.cpp
  src/utils/lbann_library.cpp
  src/utils/options.cpp
Labels: enhancement, refactor, review requested

#1327 Data store move preload
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_readers/data_reader_imagenet.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/proto_common.cpp
Labels: refactor, review requested

#1328 Data store reloading: Template Method design pattern
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_store/data_store_conduit.cpp
Labels: refactor, review requested

#1330 Pin cereal and libjpeg-turbo
  superbuild/cereal/CMakeLists.txt
  superbuild/jpeg-turbo/CMakeLists.txt
Labels: enhancement
