Repository LLNL/lbann, pull requests merged in 2019-12, with the labels that each got.

#1357 Fix bugs in Python frontend
  applications/vision/resnet.py
  python/lbann/contrib/args.py
Labels: bug, python

#1362 Clean up concatenate and slice layers
  bamboo/unit_tests/test_unit_layer_concatenate.py
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/layers/transform/concatenation.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/lbann.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/concatenate.cpp
  src/proto/factories/layer_factory.cpp
Labels: refactor, review requested

#1363 Support transposes in matrix multiply layer
  bamboo/unit_tests/test_unit_layer_matmul.py
  include/lbann/layers/math/matmul.hpp
  src/layers/math/matmul.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1361 Implement ETI for multiple data types
  include/lbann/base.hpp
  include/lbann/comm.hpp
  include/lbann/io/persist.hpp
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/macros/instantiate.hpp
  include/lbann/macros/instantiate_device.hpp
  include/lbann/optimizers/data_type_optimizer.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/random.hpp
  include/lbann/utils/summary.hpp
  include/lbann/utils/summary_impl.hpp
  include/lbann/weights/data_type_weights.hpp
  include/lbann/weights/initializer.hpp
  include/lbann/weights/variance_scaling_initializers.hpp
  src/comm.cpp
  src/io/persist.cpp
  src/layers/data_type_layer.cpp
  src/layers/learning/fully_connected.cpp
  src/optimizers/data_type_optimizer.cpp
  src/utils/random.cpp
  src/utils/summary.cpp
  src/weights/data_type_weights.cpp
  src/weights/initializer.cpp
  src/weights/variance_scaling_initializers.cpp
Labels: enhancement, review requested

#1367 Feature add ETI for multiple data type for learning layers
  include/lbann/base.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/embedding.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/utils/im2col.hpp
  src/layers/learning/channelwise_scale_bias.cpp
  src/layers/learning/channelwise_scale_bias.cu
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
  src/layers/learning/embedding.cpp
  src/layers/learning/embedding.cu
  src/layers/learning/entrywise_scale_bias.cpp
  src/layers/learning/entrywise_scale_bias.cu
  src/utils/cudnn.cpp
  src/utils/im2col.cpp
Labels: enhancement, review requested

#1368 Allow Layer classes to return a BaseDistMatrix for activations and error signals
  CMakeLists.txt
  include/lbann/base.hpp
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/math/matmul.hpp
  src/layers/data_type_layer.cpp
Labels: refactor, review requested

#1369 Adding ETI with support for doubles for the math layers.
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/entrywise.hpp
  include/lbann/layers/loss/l1_norm.hpp
  include/lbann/layers/loss/l2_norm2.hpp
  include/lbann/layers/loss/mean_absolute_error.hpp
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/math/binary.hpp
  include/lbann/layers/math/clamp.hpp
  include/lbann/layers/math/matmul.hpp
  include/lbann/layers/math/unary.hpp
  include/lbann/utils/cublas.hpp
  src/layers/loss/categorical_accuracy.cpp
  src/layers/loss/categorical_accuracy.cu
  src/layers/loss/cross_entropy.cpp
  src/layers/loss/cross_entropy.cu
  src/layers/loss/l1_norm.cpp
  src/layers/loss/l1_norm.cu
  src/layers/loss/l2_norm2.cpp
  src/layers/loss/l2_norm2.cu
  src/layers/loss/mean_absolute_error.cpp
  src/layers/loss/mean_absolute_error.cu
  src/layers/loss/mean_squared_error.cpp
  src/layers/loss/mean_squared_error.cu
  src/layers/loss/top_k_categorical_accuracy.cpp
  src/layers/loss/top_k_categorical_accuracy.cu
  src/layers/math/clamp.cpp
  src/layers/math/clamp.cu
  src/layers/math/matmul.cpp
  src/utils/cublas.cpp
Labels: review requested

#1359 Add support for LBANN launcher kwargs in Bamboo tests
  bamboo/common_python/tools.py
Labels: CI, enhancement

#1366 Add Bamboo unit test for data store with ImageNet
  bamboo/unit_tests/test_unit_datastore_imagenet.py
Labels: CI

#1373 Negative sampling in node2vec
  applications/graph/dataset.py
  applications/graph/main.py
Labels: application

#1376 Relax error tolerance in PyTest test for data store
  bamboo/unit_tests/test_unit_datastore_imagenet.py
Labels: CI, bug, review requested

#1371 Transformer model
  applications/nlp/transformer/dataset.py
  applications/nlp/transformer/main.py
  applications/nlp/transformer/model.py
  python/lbann/modules/__init__.py
  python/lbann/modules/base.py
  python/lbann/modules/transformer.py
  python/lbann/util/__init__.py
Labels: application, review requested

#1379 Feature add eti to transform layers
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/categorical_random.hpp
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/discrete_random.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/in_top_k.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/sort.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/tessellate.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/layers/transform/weights.hpp
  src/layers/transform/bernoulli.cpp
  src/layers/transform/categorical_random.cpp
  src/layers/transform/concatenate.cpp
  src/layers/transform/constant.cpp
  src/layers/transform/crop.cpp
  src/layers/transform/crop.cu
  src/layers/transform/discrete_random.cpp
  src/layers/transform/dummy.cpp
  src/layers/transform/evaluation.cpp
  src/layers/transform/gaussian.cpp
  src/layers/transform/hadamard.cpp
  src/layers/transform/in_top_k.cpp
  src/layers/transform/in_top_k.cu
  src/layers/transform/pooling.cpp
  src/layers/transform/reduction.cpp
  src/layers/transform/reshape.cpp
  src/layers/transform/slice.cpp
  src/layers/transform/sort.cpp
  src/layers/transform/sort.cu
  src/layers/transform/split.cpp
  src/layers/transform/stop_gradient.cpp
  src/layers/transform/sum.cpp
  src/layers/transform/tessellate.cpp
  src/layers/transform/tessellate.cu
  src/layers/transform/uniform.cpp
  src/layers/transform/unpooling.cpp
  src/layers/transform/weighted_sum.cpp
  src/layers/transform/weights.cpp
Labels: enhancement, review requested

#1385 Fix type error in transformer model data pipeline
  applications/nlp/utils/gutenberg.py
Labels: application, bug, review requested

#1384 Feature add eti to regularizer and image layers
  include/lbann/layers/image/bilinear_resize.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/regularizers/layer_norm.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/regularizers/selu_dropout.hpp
  src/layers/image/bilinear_resize.cpp
  src/layers/image/bilinear_resize.cu
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/layers/regularizers/dropout.cpp
  src/layers/regularizers/entrywise_batch_normalization.cpp
  src/layers/regularizers/entrywise_batch_normalization.cu
  src/layers/regularizers/layer_norm.cpp
  src/layers/regularizers/layer_norm.cu
  src/layers/regularizers/local_response_normalization.cpp
  src/layers/regularizers/selu_dropout.cpp
Labels: enhancement, review requested

#1383 Added ETI for multiple data types for the activations layers.
  include/lbann/layers/activations/activations.hpp
  include/lbann/layers/activations/elu.hpp
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/activations/log_softmax.hpp
  include/lbann/layers/activations/softmax.hpp
  src/layers/activations/elu.cpp
  src/layers/activations/elu.cu
  src/layers/activations/identity.cpp
  src/layers/activations/leaky_relu.cpp
  src/layers/activations/leaky_relu.cu
  src/layers/activations/log_softmax.cpp
  src/layers/activations/log_softmax.cu
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
Labels: enhancement, review requested

#1380 Layer factory revamp
  include/lbann/base.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/proto/factories.hpp
  python/lbann/__init__.py
  python/lbann/core/layer.py
  python/lbann/core/util.py
  src/base.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/fully_connected.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1387 Updated the I/O layers to properly support ETI with multiple data types
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/io/data_buffers/partitioned_io_buffer.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/layers/io/input/input_layer.hpp
  src/io/data_buffers/generic_io_buffer.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/layers/io/input/input_layer.cpp
Labels: enhancement, review requested

#1382 Optimize performance of concatenate layer
  bamboo/unit_tests/test_unit_layer_concatenate.py
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/utils/cuda.hpp
  include/lbann/utils/impl/cuda.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/concatenate.cpp
  src/layers/transform/concatenate.cu
Labels: enhancement, review requested

#1388 Optimize performance of slice layer
  bamboo/unit_tests/test_unit_layer_slice.py
  include/lbann/layers/transform/slice.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/slice.cpp
  src/layers/transform/slice.cu
  src/proto/factories/layer_factory.cpp
Labels: enhancement, review requested
