Repository LLNL/lbann, pull requests merged in 2019-06, with the labels that each got.

#1059 modified model_zoo/jag_utils/build_index to work with hydra data
  model_zoo/jag_utils/build_index.cpp
  model_zoo/jag_utils/build_sample_id_mapping.cpp
Labels: enhancement, review requested

#1062 Basic documentation for running LBANN
  docs/running_lbann.rst
  python/README.md
Labels: documentation, review requested

#1076 drivers to test ingest speed for JAG and HYDRA,
  model_zoo/jag_utils/CMakeLists.txt
  model_zoo/jag_utils/convert.cpp
  model_zoo/jag_utils/test_reading_speed.cpp
Labels: enhancement

#1074 Hydra normalization
  model_zoo/jag_utils/CMakeLists.txt
  model_zoo/jag_utils/compute_hydra_normalization.cpp
Labels: enhancement, in progress, review requested

#1080 Bugfix for model zoo Python scripts
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  model_zoo/vision/resnet.py
Labels: bug, review requested

#1065 Clean up tests
  bamboo/common_python/test_tools.py
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script.sh
  bamboo/compiler_tests/build_script_specific.sh
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/conftest.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_mnist_conv_graph.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
  docs/continuous_integration.rst
Labels: in progress

#919 Templated sample list
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/sample_list.hpp
  include/lbann/data_readers/sample_list_conduit_io_handle.hpp
  include/lbann/data_readers/sample_list_hdf5.hpp
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/data_readers/sample_list_jag.hpp
  include/lbann/data_readers/sample_list_jag_impl.hpp
  include/lbann/data_readers/sample_list_open_files.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  src/data_readers/data_reader_jag_conduit.cpp
Labels: enhancement, review requested

#1085 Add conduit include paths to wrapper interface target
  CMakeLists.txt
Labels: bug, build, review requested

#1083 Updated the spack environment to define the modules format
  docs/building_lbann.rst
  scripts/spack_recipes/build_lbann.sh
  spack_environments/std_versions_and_variants_llnl_lc_cz.yaml
Labels: enhancement, review requested

#1046 Color jitter transforms
  include/lbann/transforms/vision/CMakeLists.txt
  include/lbann/transforms/vision/adjust_brightness.hpp
  include/lbann/transforms/vision/adjust_contrast.hpp
  include/lbann/transforms/vision/adjust_saturation.hpp
  include/lbann/transforms/vision/color_jitter.hpp
  src/proto/factories/transform_factory.cpp
  src/proto/lbann.proto
  src/transforms/vision/CMakeLists.txt
  src/transforms/vision/adjust_brightness.cpp
  src/transforms/vision/adjust_contrast.cpp
  src/transforms/vision/adjust_saturation.cpp
  src/transforms/vision/color_jitter.cpp
Labels: enhancement, review requested

#1070 Beta distributions
  include/lbann/utils/beta.hpp
  include/lbann/utils/random.hpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/beta_distribution_test.cpp
  src/utils/unit_test/random_test.cpp
Labels: enhancement, review requested

#1082 Fix ImageNet validation
  model_zoo/data_readers/data_reader_imagenet.prototext
Labels: bug, review requested

#1027 CIFAR10 data reader cleanup
  include/lbann/data_readers/data_reader_cifar10.hpp
  model_zoo/data_readers/data_reader_cifar10.prototext
  src/data_readers/data_reader_cifar10.cpp
Labels: enhancement, review requested

#1092 change a constructor that was causing clang to throw an error
  include/lbann/utils/any.hpp
Labels: bug, build, review requested

#1089 Update to Clang 6
  bamboo/allocate_and_run.sh
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script_specific.sh
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/catalyst/clang6/expected_performance.csv
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_mnist_conv_graph.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
Labels: in progress

#1091 Mixup preprocessing
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/callback_mixup.hpp
  include/lbann/lbann.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_mixup.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement, review requested

#1072 Cutout preprocessing
  include/lbann/transforms/vision/CMakeLists.txt
  include/lbann/transforms/vision/cutout.hpp
  src/proto/factories/transform_factory.cpp
  src/proto/lbann.proto
  src/transforms/vision/CMakeLists.txt
  src/transforms/vision/cutout.cpp
Labels: enhancement, review requested

#1094 Pass reservation to launcher
  python/lbann/contrib/lc/launcher.py
Labels: bug, review requested

#1086 Add tb image support
  CMakeLists.txt
  external/TBinf/TBinf.cpp
  external/TBinf/TBinf.hpp
  include/lbann/utils/image.hpp
  src/utils/image.cpp
Labels: enhancement, review requested

#1088 Use shared memory for inter-process communication in Python data reader
  include/lbann/data_readers/data_reader_python.hpp
  src/data_readers/data_reader_python.cpp
Labels: enhancement, review requested

#1077 initial commit
  model_zoo/models/jag/ae_cycle_gan/hydra_metadata.prototext
Labels: enhancement, review requested

#1096 Python frontend can get exit status from running LBANN
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/lsf.py
  python/lbann/launcher/slurm.py
Labels: enhancement, python, review requested

#1087 remove a cpp file from the root directory that isn't in any CMakeLists
  test_numpy_conduit_cache.cpp
Labels: review requested

#1099 Test clean up
  bamboo/README.md
  bamboo/allocate_and_run.sh
  docs/continuous_integration.rst
Labels: documentation

#1100 Refactoring Python utility classes
  include/lbann/data_readers/data_reader_python.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/python.hpp
  python/lbann/launcher/__init__.py
  python/lbann/proto.py
  src/data_readers/data_reader_python.cpp
  src/utils/CMakeLists.txt
  src/utils/python.cpp
Labels: bug, refactor, review requested
