Repository LLNL/lbann, pull requests merged in 2019-03, with the labels that each got.

#906 Add some features to lbplot
  scripts/proto/lbann/plot/parser.py
  scripts/proto/lbann/plot/plot.py
  scripts/proto/scripts/plot/lbplot
  scripts/proto/setup.py
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#909 Unit testing and type-erased matrix
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/SetupCXX.cmake
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/any.hpp
  include/lbann/utils/memory.hpp
  include/lbann/utils/type_erased_matrix.hpp
  model_zoo/tests/CMakeLists.txt
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/any_test.cpp
  src/utils/unit_test/factory_test.cpp
  src/utils/unit_test/type_erased_matrix_test.cpp
  unit_test/CMakeLists.txt
  unit_test/SequentialCatchMain.cpp
Labels: enhancement, review requested

#910 Refactoring convolution layer
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/transform/pooling.hpp
Labels: bug, refactor

#895 remove obsolete layer references in the siamese prototext files
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
Labels: bug, review requested

#908 Refactoring model class
  include/lbann/callbacks/callback_save_images.hpp
  include/lbann/models/model.hpp
  src/callbacks/callback_check_dataset.cpp
  src/callbacks/callback_check_init.cpp
  src/callbacks/callback_checknan.cpp
  src/callbacks/callback_checkpoint.cpp
  src/callbacks/callback_checksmall.cpp
  src/callbacks/callback_confusion_matrix.cpp
  src/callbacks/callback_debug.cpp
  src/callbacks/callback_debug_io.cpp
  src/callbacks/callback_dump_error_signals.cpp
  src/callbacks/callback_dump_gradients.cpp
  src/callbacks/callback_dump_minibatch_sample_indices.cpp
  src/callbacks/callback_dump_outputs.cpp
  src/callbacks/callback_dump_weights.cpp
  src/callbacks/callback_imcomm.cpp
  src/callbacks/callback_io.cpp
  src/callbacks/callback_learning_rate.cpp
  src/callbacks/callback_ltfb.cpp
  src/callbacks/callback_perturb_adam.cpp
  src/callbacks/callback_print.cpp
  src/callbacks/callback_replace_weights.cpp
  src/callbacks/callback_save_images.cpp
  src/callbacks/callback_save_model.cpp
  src/callbacks/callback_summary.cpp
  src/callbacks/callback_timer.cpp
  src/callbacks/callback_variable_minibatch.cpp
  src/callbacks/profiler.cpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_moving_mnist.cpp
  src/data_store/data_store_jag.cpp
  src/data_store/generic_data_store.cpp
  src/models/model.cpp
Labels: bug, refactor

#920 Fixed a bug in the copy function of the partitioned_io_buffer.
  include/lbann/io/data_buffers/partitioned_io_buffer.hpp
  src/io/data_buffers/partitioned_io_buffer.cpp
Labels: bug

#917 add command line options to override index_list specified in prototext
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#894 allow using data without image, which is valid.
  src/data_readers/data_reader_jag_conduit.cpp
Labels: bug, review requested

#918 Miscellaneous Python development for VRAM
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  model_zoo/tests/model_mnist_conv_graph.prototext
  scripts/proto/examples/viz/README.md
  scripts/proto/examples/viz/rnn_1.jpg
  scripts/proto/examples/viz/rnn_1.pdf
  scripts/proto/examples/viz/rnn_1a.pdf
  scripts/proto/examples/viz/rnn_2.pdf
  scripts/proto/examples/viz/rnn_3.jpg
  scripts/proto/examples/viz/rnn_3.pdf
  scripts/proto/examples/viz/rnn_4.pdf
  scripts/proto/lbann/contrib/objective_functions.py
  scripts/proto/lbann/models/alexnet.py
  scripts/proto/lbann/models/resnet.py
  scripts/proto/lbann/modules.py
  scripts/proto/lbann/onnx/l2o/layers/transforms.py
  scripts/proto/lbann/onnx/o2l/layers/math.py
  scripts/proto/lbann/proto.py
  scripts/proto/lbann/viz.py
  scripts/proto/lbann/viz/__init__.py
  scripts/proto/lbann/viz/layer.py
  scripts/proto/lbann/viz/properties/__init__.py
  scripts/proto/lbann/viz/properties/properties.txt
  scripts/proto/lbann/viz/properties/properties_rect.txt
  scripts/proto/scripts/lbviz
  scripts/proto/scripts/viz/lbviz
  scripts/proto/setup.py
  src/proto/factories/layer_factory.cpp
  src/proto/lbann.proto
Labels: bug, enhancement, refactor

#899 Fix Tests
  bamboo/README.md
  bamboo/common_python/test_tools.py
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script.sh
  bamboo/compiler_tests/build_script_specific.sh
  bamboo/compiler_tests/conftest.py
  bamboo/compiler_tests/test_compiler.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/expected_values/pascal/clang4/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/clang4/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/clang4/expected_performance.csv
  bamboo/integration_tests/expected_values/pascal/gcc4/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc4/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc4/expected_performance.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/gcc7/expected_performance.csv
  bamboo/integration_tests/expected_values/pascal/intel18/expected_conv_autoencoder_imagenet_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/intel18/expected_conv_autoencoder_mnist_objective_functions.csv
  bamboo/integration_tests/expected_values/pascal/intel18/expected_performance.csv
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/unit_tests/conftest.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_mnist_conv_graph.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
Labels: in progress

#924 Callback augmentation
  include/lbann/callbacks/callback_print.hpp
  src/callbacks/callback_print.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement

#926 Python implementation of LeNet
  scripts/proto/lbann/models/lenet.py
Labels: enhancement

#929 Updating Python documentation with changes in PR #918.
  scripts/proto/README.md
Labels: documentation

#875 Adding directions for how an LBANN user can install with Spack.
  ReleaseNotes.txt
  docs/BuildingLBANN.md
  spack_environments/externals_llnl_lc_cz.yaml
  spack_environments/users/llnl_lc/ppc64le_cuda/spack.yaml
  spack_environments/users/llnl_lc/x86_64_cuda/spack.yaml
Labels: enhancement, in progress

#931 Adding optimizers to Python interface.
  model_zoo/optimizers/opt_sgd.prototext
  scripts/proto/lbann/proto.py
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement

#936 Split build instructions and move to rst
  README.md
  docs/BuildingLBANN.md
  docs/README
  docs/RunningLBANN.md
  docs/build_containers.rst
  docs/build_llnl_idiosyncracies.rst
  docs/build_spack_extra_config.rst
  docs/build_with_cmake.rst
  docs/build_with_superbuild.rst
  docs/building_lbann.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/running_lbann.rst
Labels: documentation, enhancement, review requested

#934 update find_package for conduit to reflect latest changes on their end.
  CMakeLists.txt
Labels: bug, build, review requested

#939 Removed deprecated parts of the multiheaded data reader that were
  include/lbann/data_readers/data_reader_multihead_siamese.hpp
  include/lbann/data_store/data_store_multihead_siamese.hpp
  src/data_readers/data_reader_multihead_siamese.cpp
  src/data_store/data_store_multihead_siamese.cpp
Labels: bug

#937 Python examples in model zoo
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  scripts/proto/lbann/models/__init__.py
  scripts/proto/lbann/models/alexnet.py
  scripts/proto/lbann/models/lenet.py
Labels: enhancement, review requested

#945 JAG Conduit data reader bug fix
  src/proto/proto_common.cpp
Labels: bug

#927 Python data reader
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_python.hpp
  include/lbann/lbann.hpp
  scripts/build_lbann_lc.sh
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_python.cpp
  src/proto/lbann.proto
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#947 Bugfix for mnist_conv_graph unit test
  model_zoo/tests/model_mnist_conv_graph.prototext
Labels: bug

#949 Change a -= to an Axpy for back compatibility
  model_zoo/tests/test_utils.hpp
Labels: enhancement, review requested

#950 Updating documentation with OSX build instructions and publications
  README.md
  docs/CMakeLists.txt
  docs/build_osx.rst
  docs/building_lbann.rst
  docs/conf.py
  docs/index.rst
  docs/lbann.rst
  docs/publications.rst
  spack_environments/developer_release_osx_spack.yaml
Labels: documentation

#953 Removing a deprecated SGD field
  bamboo/unit_tests/prototext/opt_sgd.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
Labels: bug, review requested

#922 modified detect_corruption to be more complete.
  model_zoo/jag_utils/detect_corruption.cpp
Labels: enhancement

#941 Python function to launch Slurm jobs
  model_zoo/vision/.gitignore
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  scripts/proto/lbann/contrib/args.py
  scripts/proto/lbann/contrib/lc/__init__.py
  scripts/proto/lbann/contrib/lc/launcher.py
  scripts/proto/lbann/contrib/lc/paths.py
  scripts/proto/lbann/contrib/lc/systems.py
  scripts/proto/lbann/launcher/__init__.py
  scripts/proto/lbann/launcher/slurm.py
  scripts/proto/lbann/models/__init__.py
  scripts/proto/lbann/modules.py
  scripts/proto/lbann/proto.py
  scripts/proto/lbann/utils.py
Labels: enhancement, review requested

#954 Bugfix for build failure with Conduit
  model_zoo/jag_utils/generate_corrupt_samples.cpp
Labels: bug

#942 adding get_random_node() method
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/sample_list_jag.hpp
  include/lbann/data_store/data_store_jag.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_jag.cpp
Labels: enhancement, in progress, review requested

#957 Moving core Python functionality to `lbann` module
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  python/README.md
  python/docs/viz/README.md
  python/lbann/__init__.py
  python/lbann/callback.py
  python/lbann/contrib/lc/paths.py
  python/lbann/contrib/objective_functions.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/slurm.py
  python/lbann/layer.py
  python/lbann/metric.py
  python/lbann/model.py
  python/lbann/models/alexnet.py
  python/lbann/models/lenet.py
  python/lbann/models/resnet.py
  python/lbann/modules.py
  python/lbann/objective_function.py
  python/lbann/onnx/l2o/__init__.py
  python/lbann/onnx/o2l/__init__.py
  python/lbann/onnx/o2l/layers/learnings.py
  python/lbann/onnx/o2l/layers/math.py
  python/lbann/onnx/o2l/layers/regularizers.py
  python/lbann/onnx/o2l/layers/transforms.py
  python/lbann/onnx/tests/lbann2onnx_layer_test.py
  python/lbann/onnx/tests/onnx2lbann_layer_test.py
  python/lbann/onnx/tests/onnx2lbann_test.py
  python/lbann/optimizer.py
  python/lbann/proto.py
  python/lbann/util/__init__.py
  python/lbann/util/class_generator.py
  python/lbann/viz.py
  python/lbann/weights.py
Labels: python, refactor, review requested
