Repository LLNL/lbann, pull requests merged in 2019-05, with the labels that each got.

#1020 Numpy conduit reader
  include/lbann/base.hpp
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  include/lbann/data_readers/numpy_conduit_converter.hpp
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/layers/io/input/generic_input_layer.hpp
  include/lbann/lbann.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_readers/numpy_conduit_converter.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/proto_common.cpp
Labels: enhancement, in progress, review requested

#1036 Fix grouped convolution.
  include/lbann/layers/learning/convolution.hpp
Labels: bug

#1026 Install Python frontend in CMake build process
  CMakeLists.txt
  ReleaseNotes.txt
  cmake/configure_files/python_config.ini.in
  cmake/configure_files/setup.py.in
  cmake/modules/FindPython.cmake
  docs/building_lbann.rst
  model_zoo/CMakeLists.txt
  model_zoo/vision/alexnet.py
  model_zoo/vision/lenet.py
  model_zoo/vision/resnet.py
  python/README.md
  python/lbann/__init__.py
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/paths.py
  python/lbann/contrib/lc/systems.py
  python/lbann/launcher/__init__.py
  python/lbann/util/__init__.py
  python/setup.py
  scripts/build_lbann_lc.sh
  spack_environments/developer_release_ppc64le_cuda_spack.yaml
  spack_environments/developer_release_x86_64_cuda_spack.yaml
  spack_environments/externals_llnl_lc_cz.yaml
  spack_environments/externals_ppc64le_llnl_lc_cz.yaml
  spack_environments/externals_x86_64_llnl_lc_cz.yaml
  spack_environments/std_versions_and_variants_llnl_lc_cz.yaml
  spack_environments/users/llnl_lc/ppc64le_cuda/spack.yaml
  spack_environments/users/llnl_lc/x86_64_cuda/spack.yaml
  superbuild/conduit/CMakeLists.txt
Labels: build, enhancement, python, review requested

#1039 Change LBANN to install python in normal site-packages directory
  CMakeLists.txt
  cmake/configure_files/lbann_module.lua.in
  docs/building_lbann.rst
  scripts/build_lbann_lc.sh
  src/proto/CMakeLists.txt
Labels: bug

#1045 Support specifying random seeds in Python
  model_zoo/vision/resnet.py
  python/lbann/model.py
Labels: enhancement, python, review requested

#1040 Add callback for dropout perturbation
  include/lbann/callbacks/callback_dump_outputs.hpp
  include/lbann/callbacks/callback_ltfb.hpp
  include/lbann/callbacks/callback_perturb_dropout.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/lbann.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/callback_ltfb.cpp
  src/callbacks/callback_perturb_dropout.cpp
  src/proto/factories/callback_factory.cpp
  src/proto/lbann.proto
Labels: enhancement

#1038 Update Weekly Develop
  bamboo/integration_tests/test_integration_performance.py
Labels: in progress

#1033 Imagenet data store
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_readers/data_reader_imagenet.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#987 Densenet with Python
  model_zoo/models/densenet/generated_densenet.prototext
  model_zoo/vision/densenet.py
Labels: in progress, review requested

#1049 Update Weekly Develop
  bamboo/allocate_and_run.sh
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/expected_values/catalyst/clang4/expected_performance.csv
  bamboo/integration_tests/expected_values/catalyst/gcc7/expected_performance.csv
  bamboo/integration_tests/full_alexnet.sh
  bamboo/integration_tests/test_integration_performance.py
  bamboo/run.sh
Labels: in progress

#1058 Fix build minor issues
  docs/build_with_cmake.rst
  docs/building_lbann.rst
  docs/index.rst
Labels: documentation, enhancement, review requested
