Repository LLNL/lbann, pull requests merged in 2019-09, with the labels that each got.

#1194 Move model visualization out of Python frontend
  cmake/configure_files/setup.py.in
  python/lbann/viz.py
  scripts/viz.py
Labels: bug, python, refactor, review requested

#1207 Fix bug in Python frontend Layer class
  python/lbann/layer.py
Labels: bug, python

#1217 Add Catch2 to the superbuild
  superbuild/CMakeLists.txt
  superbuild/catch2/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/lbann/CMakeLists.txt
Labels: build, enhancement, review requested

#1218 Make CUB a proper dependency of hydrogen in the superbuild
  superbuild/hydrogen/CMakeLists.txt
Labels: bug, build, review requested

#1177 Small update to OSX build instructions
  docs/build_osx.rst
Labels: bug, build, review requested

#1229 Set a fixed version of hydrogen in the superbuild
  superbuild/hydrogen/CMakeLists.txt
Labels: bug, build, review requested

#1188 Custom batch scripts in Python frontend
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/batch_script.py
  python/lbann/launcher/lsf.py
  python/lbann/launcher/slurm.py
Labels: enhancement, python, review requested

#1192 Enable dataset splitting for Python data reader
  src/proto/proto_common.cpp
Labels: bug, review requested

#1230 Setup data readers after model has been constructed
  src/utils/lbann_library.cpp
Labels: bug

#1238 Return LBANN exit code in Python-generated batch script
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/__init__.py
Labels: bug, python, review requested

#1240 Improve time reporting in Python-generated batch script
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/__init__.py
Labels: python

#1235 Store weights in unique_ptrs
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/transform/weights.hpp
  include/lbann/models/model.hpp
  src/models/model.cpp
  src/proto/factories/model_factory.cpp
Labels: refactor, review requested

#1241 Fix a mismatched forward-declaration
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
Labels: bug, build, review requested

#1237 Implementation of argmax and tovec layers
  include/lbann/layers/misc/CMakeLists.txt
  include/lbann/layers/misc/argmax.hpp
  include/lbann/layers/misc/argmin.hpp
  include/lbann/layers/misc/one_hot.hpp
  include/lbann/lbann.hpp
  src/layers/misc/CMakeLists.txt
  src/layers/misc/argmax.cpp
  src/layers/misc/argmin.cpp
  src/layers/misc/one_hot.cpp
  src/layers/misc/one_hot.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, in progress

#1249 Clean up LTFB callback code
  src/callbacks/ltfb.cpp
Labels: refactor, review requested

#1253 Fix bug in CIFAR autoencoder integration test
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
Labels: CI, bug

#1254 Add unit test for Python data reader
  bamboo/unit_tests/test_unit_datareader_python.py
Labels: CI, review requested

#1247 Refactor weights and objective fns to get comm at setup
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  include/lbann/proto/factories.hpp
  include/lbann/weights/weights.hpp
  src/optimizers/adagrad.cpp
  src/optimizers/adam.cpp
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/optimizer.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/sgd.cpp
  src/proto/factories/model_factory.cpp
  src/proto/factories/optimizer_factory.cpp
  src/proto/factories/weights_factory.cpp
  src/weights/weights.cpp
Labels: enhancement, review requested

#1256 Synchronize IO thread pool in input layer destructor
  include/lbann/layers/io/input/generic_input_layer.hpp
Labels: bug

#1250 Test length modes
  bamboo/common_python/tools.py
  bamboo/compiler_tests/conftest.py
  bamboo/integration_tests/common_code.py
  bamboo/integration_tests/conftest.py
  bamboo/integration_tests/test_integration_autoencoders.py
  bamboo/integration_tests/test_integration_debug.py
  bamboo/integration_tests/test_integration_performance.py
  bamboo/local_test.cmd
  bamboo/local_test.sh
  bamboo/unit_tests/conftest.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  bamboo/unit_tests/test_unit_checkpoint.py
  bamboo/unit_tests/test_unit_layer_clamp.py
  bamboo/unit_tests/test_unit_layer_covariance.py
  bamboo/unit_tests/test_unit_layer_elu.py
  bamboo/unit_tests/test_unit_layer_identity.py
  bamboo/unit_tests/test_unit_layer_l1_norm.py
  bamboo/unit_tests/test_unit_layer_l2_norm2.py
  bamboo/unit_tests/test_unit_layer_leaky_relu.py
  bamboo/unit_tests/test_unit_layer_log_sigmoid.py
  bamboo/unit_tests/test_unit_layer_log_softmax.py
  bamboo/unit_tests/test_unit_layer_mean_absolute_error.py
  bamboo/unit_tests/test_unit_layer_relu.py
  bamboo/unit_tests/test_unit_layer_selu.py
  bamboo/unit_tests/test_unit_layer_sigmoid.py
  bamboo/unit_tests/test_unit_layer_softmax.py
  bamboo/unit_tests/test_unit_layer_softplus.py
  bamboo/unit_tests/test_unit_layer_softsign.py
  bamboo/unit_tests/test_unit_layer_squared_difference.py
  bamboo/unit_tests/test_unit_layer_tessellate.py
  bamboo/unit_tests/test_unit_layer_variance.py
  bamboo/unit_tests/test_unit_lbann2_reload.py
  bamboo/unit_tests/test_unit_mnist_conv_graph.py
  bamboo/unit_tests/test_unit_mnist_ridge_regression.py
  bamboo/unit_tests/test_unit_mnist_softmax_classifier.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
  docs/continuous_integration.rst
Labels: CI

#1251 Clean up protobuf message for fully-connected layer
  include/lbann/layers/learning/fully_connected.hpp
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/candle/pilot1/combo.prototext
  model_zoo/models/jag/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/cycle_gan.prototext
  model_zoo/models/jag/wae_cycle_gan/cycle_gan_only.prototext
  model_zoo/models/jag/wae_cycle_gan/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/wae_fw_inv.prototext
  model_zoo/models/jag/wae_cycle_gan/wae_nobn.prototext
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  model_zoo/tests/data_reader_tests/jag_single_layer_ae.prototext
  model_zoo/tests/model_jag_single_layer_ae.prototext
  src/proto/factories/layer_factory.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/layers.proto
Labels: refactor, review requested

#1258 Add missed parameters in performance tests
  bamboo/integration_tests/test_integration_performance.py
Labels: CI

#1260 Fix some documentation problems
  docs/SourceTreeDoxyfile
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
Labels: bug, documentation

#1262 Add some doc text for new directories
  docs/RSTDocsFlavorText.py
Labels: documentation, enhancement

#1264 fix LBANNConfig.cmake.in so projects can depend on LBANN
  cmake/configure_files/LBANNConfig.cmake.in
Labels: build, enhancement

#1267 Update LeNet integration test to include a frequency string
  bamboo/integration_tests/test_integration_performance.py
Labels: CI

#1273 Clean up build_lbann_lc.sh
  scripts/build_lbann_lc.sh
Labels: bug, enhancement

#1275 Use CMake mechanism for correctly finding Python libraries
  cmake/modules/FindPython.cmake
Labels: build, enhancement, review requested
