Repository LLNL/lbann, pull requests merged in 2020-06, with the labels that each got.

#1559 Added an additional guard to when we do in-training validation work.
  src/training_algorithms/sgd_training_algorithm.cpp
Labels: bug, review requested

#1553 Optimize GPU performance of slice and concat layers
  src/layers/transform/concatenate.cu
  src/layers/transform/slice.cu
Labels: enhancement, review requested

#1558 Fix bug in distconv input layer
  src/layers/io/input/input_layer.cpp
Labels: bug, review requested

#1554 Bugfix objective function initialization
  CMakeLists.txt
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script.sh
  bamboo/unit_tests/test_unit_checkpoint.py
  cmake/configure_files/LBANNConfig.cmake.in
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/metrics/metric.hpp
  include/lbann/models/directed_acyclic_graph.hpp
  include/lbann/models/model.hpp
  include/lbann/objective_functions/objective_function.hpp
  include/lbann/objective_functions/objective_function_term.hpp
  include/lbann/objective_functions/weight_regularization/l2.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/hydrogen_utils.hpp
  spack_environments/cmake_lbann.sh
  src/data_readers/data_reader_mnist.cpp
  src/layers/transform/evaluation.cpp
  src/models/directed_acyclic_graph.cpp
  src/models/model.cpp
  src/proto/factories/model_factory.cpp
  src/proto/proto_common.cpp
  src/utils/random.cpp
Labels: bug

#1563 Quick refactor of weights layer
  include/lbann/layers/transform/weights.hpp
Labels: refactor, review requested

#1541 Updated NERSC environment
  applications/vision/data/imagenet/__init__.py
  applications/vision/lenet.py
  python/lbann/contrib/launcher.py
  python/lbann/contrib/nersc/__init__.py
  python/lbann/contrib/nersc/launcher.py
  python/lbann/contrib/nersc/paths.py
  python/lbann/contrib/nersc/systems.py
  python/lbann/launcher/slurm.py
  scripts/install_lbann.sh
  spack_environments/cmake_lbann.sh
  spack_environments/nersc/compilers.sh
  spack_environments/nersc/externals-cray-cnl7-skylake_avx512.sh
Labels: enhancement, python, review requested

#1560 Cleanup and consolidate initialization of the RNGs
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_lenet.py
  bamboo/integration_tests/test_integration_resnet50.py
  include/lbann/base.hpp
  include/lbann/comm.hpp
  include/lbann/data_coordinator/data_coordinator.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/proto/factories.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/trainers/trainer.hpp
  include/lbann/transforms/transform.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/lbann_library.hpp
  include/lbann/utils/random.hpp
  include/lbann/utils/random_number_generators.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_help.cpp
  model_zoo/lbann_inf.cpp
  src/base.cpp
  src/callbacks/ltfb.cpp
  src/callbacks/perturb_adam.cpp
  src/callbacks/perturb_dropout.cpp
  src/data_coordinator/data_coordinator.cpp
  src/data_readers/data_reader_synthetic.cpp
  src/models/model.cpp
  src/proto/factories/trainer_factory.cpp
  src/proto/proto_common.cpp
  src/trainers/trainer.cpp
  src/transforms/vision/color_jitter.cpp
  src/utils/CMakeLists.txt
  src/utils/lbann_library.cpp
  src/utils/random.cpp
  src/utils/random_number_generators.cpp
  tests/test_mpi_err_handling.cpp
  tests/test_shuffled_indices.cpp
  unit_test/MPICatchMain.cpp
  unit_test/SequentialCatchMain.cpp
Labels: bug, refactor

#1566 Bugfix for lbann inf
  model_zoo/lbann_inf.cpp
  python/lbann/contrib/nersc/launcher.py
  src/callbacks/load_model.cpp
  src/utils/lbann_library.cpp
Labels: bug

#1567 Move implementations - learning layers
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/learning/fully_connected.hpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/base_convolution.cpp
  src/layers/learning/channelwise_scale_bias.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
  src/layers/learning/fully_connected.cpp
  src/proto/factories/layer_factory.cpp
Labels: refactor, review requested

#1568 Allow dump weights to be used with LTFB
  include/lbann/callbacks/dump_weights.hpp
  src/callbacks/dump_weights.cpp
  src/proto/callbacks.proto
Labels: bug

#1569 3D Convolutional Auto Encoder Example for MOF Data
  applications/MOF/MOFae.py
  applications/MOF/README.md
  applications/MOF/data/MOFdataset.py
  applications/MOF/data/__init__.py
  applications/MOF/dataset.py
  applications/MOF/main.py
  applications/MOF/test/__init__.py
  applications/MOF/test/conftest.py
  applications/MOF/test/dataset_test.py
  applications/MOF/test/test_integration_mof.py
Labels: application, review requested

#1576 Update superbuild to build Hydrogen 1.3.4
  superbuild/hydrogen/CMakeLists.txt
Labels: bug, build, review requested
