Repository LLNL/lbann, pull requests merged in 2020-09, with the labels that each got.

#1555 first draft of callback docs
  docs/callbacks.rst
  docs/callbacks/selection_strategy/categorical_accuracy_strategy.rst
  docs/callbacks/selection_strategy/track_sample_ids_strategy.rst
  docs/callbacks/summarize_images.rst
  docs/index.rst
  docs/running_lbann.rst
Labels: documentation, enhancement, review requested

#1608 Update spack environment format
  CMakeLists.txt
  scripts/build_lbann_from_source.sh
  scripts/install_lbann.sh
  spack_environments/llnl_lc/compilers.sh
  spack_environments/llnl_lc/externals-linux-rhel7-broadwell.sh
  spack_environments/llnl_lc/externals-linux-rhel7-haswell.sh
  spack_environments/llnl_lc/externals-linux-rhel7-ivybridge.sh
  spack_environments/llnl_lc/externals-linux-rhel7-power8le.sh
  spack_environments/llnl_lc/externals-linux-rhel7-power9le.sh
  spack_environments/nersc/compilers.sh
  spack_environments/nersc/externals-cray-cnl7-skylake_avx512.sh
  spack_environments/osx/compilers.sh
  spack_environments/osx/externals-darwin-mojave-skylake.sh
  spack_environments/std_versions_and_variants.sh
Labels: enhancement

#1610 Support large numbers of channels in GPU batchnorm layer
  bamboo/unit_tests/test_unit_layer_batch_normalization.py
  src/layers/regularizers/batch_normalization.cu
Labels: bug, review requested

#1598 Feature add olcf center
  python/lbann/contrib/launcher.py
  python/lbann/contrib/olcf/__init__.py
  python/lbann/contrib/olcf/launcher.py
  python/lbann/contrib/olcf/paths.py
  python/lbann/contrib/olcf/systems.py
  scripts/build_lbann_from_source.sh
  scripts/install_lbann.sh
  spack_environments/olcf/compilers.sh
  spack_environments/olcf/externals-linux-rhel7-power9le.sh
  spack_environments/std_versions_and_variants.sh
Labels: enhancement, in progress

#1615 Bugfixes for SMILES data reader
  src/data_readers/data_reader_smiles.cpp
Labels: bug

#1617 Added a barrier after the conduit node exchange in the data store.
  src/data_store/data_store_conduit.cpp
Labels: bug

#1572 Merging data_reader_hdf5 and slab extensions (cont'd)
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_hdf5.hpp
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/layers/data_type_distconv_adapter.hpp
  include/lbann/lbann.hpp
  include/lbann/models/model.hpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_hdf5.cpp
  src/data_store/data_store_conduit.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/layers/data_type_distconv_adapter.cpp
  src/layers/io/input/input_layer.cpp
  src/layers/learning/base_convolution.cpp
  src/models/model.cpp
  src/proto/proto_common.cpp
Labels: bug, enhancement

#1621 Updated distconv adaptors to use new optimizer methods
  src/layers/learning/base_convolution.cpp
  src/layers/regularizers/batch_normalization.cu
Labels: bug, review requested

#1623 Bug fix for spack install script
  scripts/install_lbann.sh
Labels: build, spack

#1626 GRU layer
  applications/ATOM/models/vae.py
  applications/ATOM/train_atom_vae.py
  bamboo/unit_tests/test_unit_layer_gru.py
  include/lbann/layers/learning/CMakeLists.txt
  include/lbann/layers/learning/gru.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/cudnn.hpp
  python/lbann/modules/rnn.py
  src/callbacks/ltfb.cpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/gru.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/utils/cudnn.cpp
Labels: application, enhancement

#1627 Optimizations for ATOM VAE model
  applications/ATOM/models/vae.py
  applications/ATOM/train_atom_vae.py
  include/lbann/utils/cuda.hpp
  include/lbann/utils/impl/cuda.hpp
  src/layers/learning/gru.cpp
  src/optimizers/adam.cpp
  src/optimizers/adam.cu
Labels: application, in progress

#1629 CUDA kernel for tensor reordering in GRU layer
  applications/ATOM/models/vae.py
  include/lbann/utils/cuda.hpp
  src/layers/learning/gru.cpp
  src/utils/cuda.cu
Labels: enhancement, review requested

#1632 Add optimized launcher defaults for rzansel
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/systems.py
Labels: python, review requested

#1401 Sample list image bcast
  bamboo/common_python/data/imagenet/data_reader.prototext
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_resnet50.py
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_image.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/sample_list.hpp
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/data_readers/sample_list_open_files.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/utils/file_utils.hpp
  model_zoo/data_readers/data_reader_jag.prototext
  python/lbann/contrib/lc/paths.py
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_imagenet.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/proto_common.cpp
  src/proto/reader.proto
  src/utils/file_utils.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1580 Enhance the HDF5 data reader with Distconv
  include/lbann/data_coordinator/data_coordinator.hpp
  include/lbann/data_coordinator/data_coordinator_metadata.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_hdf5.hpp
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/activations/relu.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/io/input/input_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/deconvolution.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/sum.hpp
  src/data_coordinator/data_coordinator.cpp
  src/data_coordinator/data_coordinator_metadata.cpp
  src/data_readers/data_reader_hdf5.cpp
  src/io/data_buffers/partitioned_io_buffer.cpp
  src/layers/data_type_layer.cpp
  src/layers/io/input/input_layer.cpp
  src/layers/layer.cpp
  src/layers/learning/base_convolution.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/proto/proto_common.cpp
  src/proto/reader.proto
Labels: enhancement, review requested

#1625 Updated docs, added quick start guide
  docs/build_llnl_idiosyncracies.rst
  docs/building_lbann.rst
  docs/index.rst
  docs/quick_start.rst
Labels: documentation, review requested

#1639 Integrated fixes for Ray's build environment from szaman19
  spack_environments/llnl_lc/externals-linux-rhel7-power8le.sh
Labels: bug

#1637 Update reconstruction tests to use new sample lists format
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
Labels: bug, review requested
