Repository LLNL/lbann, pull requests merged in 2020-12, with the labels that each got.

#1717 Bugfixes on distconv
  src/layers/data_type_distconv_adapter.cpp
  src/layers/distconv_adapter.cpp
  src/utils/distconv.cpp
Labels: bug

#1718 Incrementally ingest offline node2vec walks
  applications/graph/node2vec/data/offline_walks.py
Labels: application

#1719 Feature modular trainer split
  applications/ATOM/eval_atom_wae.py
  applications/ATOM/eval_atom_wae_dec.py
  applications/ATOM/eval_atom_wae_enc.py
  applications/ATOM/train_atom_char_rnn.py
  applications/ATOM/train_atom_vae.py
  applications/ATOM/train_atom_wae.py
  applications/physics/ICF/eval_macc_surrogate.py
  applications/physics/ICF/pre_train_jag_wae.py
  applications/physics/ICF/train_macc_surrogate.py
  include/lbann/utils/lbann_library.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_help.cpp
  model_zoo/lbann_inf.cpp
  src/proto/proto_common.cpp
  src/proto/trainer.proto
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1722 Bugfix and unit tests for LTFB
  bamboo/unit_tests/test_unit_callback_ltfb.py
  bamboo/unit_tests/test_unit_callback_ltfb_data.py
  include/lbann/data_coordinator/buffered_data_coordinator.hpp
  src/data_coordinator/buffered_data_coordinator.cpp
Labels: CI, bug, review requested

#1687 Refactor pooling layer for cuDNN abstraction
  include/lbann/base.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/utils/dnn_lib/cudnn.hpp
  include/lbann/utils/dnn_lib/dnn_lib.hpp
  src/base.cpp
  src/layers/transform/pooling.cpp
  src/utils/cudnn.cpp
Labels: refactor, review requested

#1723 Refactor dnn_lib convolution parameter type from distmatrix to matrix
  include/lbann/utils/dnn_lib/cudnn/convolution.hpp
  src/layers/learning/base_convolution.cpp
Labels: refactor

#1727 Fixed the external definition in the llnl_lc environments for ppc64le
  spack_environments/llnl_lc/externals-linux-ppc64le.sh
Labels: bug

#1730 Upgrade superbuild for CUDA 11
  scripts/build_lbann_lc.sh
  superbuild/dihydrogen/CMakeLists.txt
Labels: bug
