Repository LLNL/lbann, pull requests merged in 2020-08, with the labels that each got.

#1594 Update superbuild to use Hydrogen 1.4.0 and Aluminum 0.4.0
  scripts/build_lbann_lc.sh
  superbuild/aluminum/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
Labels: bug, build, review requested

#1590 Add support for distributed embedding layer with double datatype
  src/layers/misc/dist_embedding.cpp
  src/layers/misc/dist_embedding.cu
Labels: enhancement, review requested

#1592 Graph Convolution Layers in Python Front End Modules
  applications/MOF/MOFae.py
  applications/MOF/README.md
  applications/graph/GNN/Dense_Graph_Trainer.py
  applications/graph/GNN/README.md
  applications/graph/GNN/Sparse_Graph_Trainer.py
  applications/graph/GNN/data/MNIST_Superpixel/__init__.py
  applications/graph/GNN/data/MNIST_Superpixel/update_adj_mat.py
  applications/graph/GNN/data/MNIST_Superpixel/utils.py
  applications/graph/GNN/data/PROTEINS/PROTEINS_Dataset.py
  applications/graph/GNN/data/PROTEINS/__init__.py
  applications/graph/GNN/data/PROTEINS/utils.py
  applications/graph/GNN/data/__init__.py
  applications/graph/GNN/main.py
  applications/graph/GNN/test/__init__.py
  applications/graph/GNN/test/conftest.py
  applications/graph/GNN/test/test_integration_DGCN.py
  applications/graph/GNN/test/test_integration_DGraph.py
  applications/graph/GNN/test/test_integration_GCN.py
  applications/graph/GNN/test/test_integration_GIN.py
  applications/graph/GNN/test/test_integration_GatedGraph.py
  applications/graph/GNN/test/test_integration_Graph.py
  python/lbann/modules/__init__.py
  python/lbann/modules/graph/__init__.py
  python/lbann/modules/graph/dense/DenseGCNConv.py
  python/lbann/modules/graph/dense/DenseGraphConv.py
  python/lbann/modules/graph/dense/__init__.py
  python/lbann/modules/graph/sparse/GCNConv.py
  python/lbann/modules/graph/sparse/GINConv.py
  python/lbann/modules/graph/sparse/GatedGraphConv.py
  python/lbann/modules/graph/sparse/GraphConv.py
  python/lbann/modules/graph/sparse/__init__.py
  python/lbann/modules/graph/utils.py
Labels: application, python, review requested

#1599 Reset data coordinator after each LTFB round
  include/lbann/io/data_buffers/generic_io_buffer.hpp
  src/callbacks/ltfb.cpp
Labels: bug, review requested

#1602 Fix bug in weights proxy when weights buffer is reallocated
  include/lbann/weights/weights_proxy.hpp
Labels: bug, review requested

#1607 Avoid char in hashing unit tests
  src/utils/unit_test/hash_test.cpp
Labels: bug, review requested

#1611 Acquire IO RNG objects in synthetic data reader
  src/data_readers/data_reader_synthetic.cpp
Labels: bug, review requested
