Repository LLNL/lbann, pull requests merged in 2020-04, with the labels that each got.

#1492 Serialization methods for fp16 types in Cereal
  include/lbann/base.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/serialization.hpp
  src/utils/CMakeLists.txt
  src/utils/serialization.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/serialize_half_test.cpp
Labels: enhancement, review requested

#1490 Cleanup checkpoint and restart hierarchy
  include/lbann/callbacks/checkpoint.hpp
  include/lbann/callbacks/load_model.hpp
  include/lbann/io/persist.hpp
  include/lbann/models/model.hpp
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/data_type_optimizer.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  include/lbann/trainers/trainer.hpp
  src/callbacks/checkpoint.cpp
  src/callbacks/load_model.cpp
  src/callbacks/ltfb.cpp
  src/callbacks/save_model.cpp
  src/io/persist.cpp
  src/metrics/layer_metric.cpp
  src/models/model.cpp
  src/optimizers/adagrad.cpp
  src/optimizers/adam.cpp
  src/optimizers/data_type_optimizer.cpp
  src/optimizers/hypergradient_adam.cpp
  src/optimizers/rmsprop.cpp
  src/optimizers/sgd.cpp
  src/trainers/trainer.cpp
  src/utils/lbann_library.cpp
Labels: bug, refactor, review requested

#1502 Flag to enable half support in spack build
  scripts/install_lbann.sh
Labels: review requested

#1506 Bugfix ckpt directory checking
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_checkpoint_lenet.py
  bamboo/unit_tests/test_unit_load_weights_lenet.py
Labels: bug, review requested

#1497 Add self-supervised learning scripts to application directory
  applications/selfsupervised/.gitignore
  applications/selfsupervised/README.md
  applications/selfsupervised/classifier.py
  applications/selfsupervised/data_reader_cub.prototext
  applications/selfsupervised/data_reader_imagenet.prototext
  applications/selfsupervised/main.py
  applications/selfsupervised/modules.py
  applications/selfsupervised/patch_generator/__init__.py
  applications/selfsupervised/patch_generator/chroma_blur.py
  applications/selfsupervised/patch_generator/extract_patches.py
  applications/selfsupervised/patch_generator/patterns.py
  applications/selfsupervised/pretrain_siamese.py
  applications/selfsupervised/resnet.py
  applications/selfsupervised/util.py
  bamboo/unit_tests/test_unit_check_proto_models.py
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader_multi_images.hpp
  include/lbann/data_readers/data_reader_multihead_siamese.hpp
  include/lbann/data_readers/data_reader_triplet.hpp
  include/lbann/data_readers/offline_patches_npz.hpp
  include/lbann/lbann.hpp
  model_zoo/models/siamese/finetune-cub/model_cub.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm.prototext
  model_zoo/models/siamese/finetune-cub/model_cub_batchnorm_transferred_and_frozen.prototext
  model_zoo/models/siamese/triplet/model_triplet_alexnet_batchnorm_dag_frozen_bn.prototext
  model_zoo/models/siamese/triplet/opt_sgd.prototext
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_multi_images.cpp
  src/data_readers/data_reader_multihead_siamese.cpp
  src/data_readers/data_reader_triplet.cpp
  src/data_readers/offline_patches_npz.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
  tools/siamese_patch_list/CMakeLists.txt
  tools/siamese_patch_list/lbann
  tools/siamese_patch_list/mem.hpp
  tools/siamese_patch_list/siamese_patches.cpp
Labels: application, refactor, review requested

#1510 Fix LTFB sendrecv_weights for ADAM
  src/callbacks/ltfb.cpp
Labels: bug, review requested

#1508 Clean up back-prop memory usage
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/layer.hpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
  src/layers/matrix_builder.hpp
Labels: enhancement, refactor, review requested

#1525 Remove reservation flag when Python frontend calls jsrun
  python/lbann/launcher/lsf.py
Labels: bug, python
