Repository LLNL/lbann, pull requests merged in 2020-03, with the labels that each got.

#1451 allow specifying checkpoint base directory for LTFB checkpoint method
  include/lbann/callbacks/ltfb.hpp
  src/callbacks/ltfb.cpp
  src/proto/callbacks.proto
Labels: enhancement, review requested

#1449 Un-superbuild-ify the script that just builds LBANN
  scripts/build_lbann_from_source.sh
  spack_environments/cmake_lbann.sh
Labels: refactor, review requested

#1454 Deprecate and delete old prototext files
  model_zoo/models/alexnet/model_alexnet.prototext
  model_zoo/models/densenet/generated_densenet.prototext
  model_zoo/models/lenet_mnist/model_lenet_mnist.prototext
  model_zoo/models/resnet50/README.md
  model_zoo/models/resnet50/model_resnet50.prototext
Labels: review requested

#1463 Add option to build with NVSHMEM
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/FindNVSHMEM.cmake
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/nvshmem.hpp
  python/lbann/contrib/lc/launcher.py
  scripts/build_lbann_lc.sh
  src/base.cpp
  src/utils/CMakeLists.txt
  src/utils/nvshmem.cu
Labels: build, enhancement, review requested

#1465 Improve error reporting in verify_prototext()
  src/utils/protobuf_utils.cpp
Labels: enhancement, review requested

#1476 Add option in Python frontend for custom executable
  python/lbann/contrib/launcher.py
  python/lbann/launcher/__init__.py
Labels: enhancement, python, review requested

#1479 Add a warning to the documentation for IBV_FORK_SAFE
  docs/running_lbann.rst
Labels: documentation, review requested

#1462 Pytest data store
  bamboo/unit_tests/test_unit_datastore_imagenet.py
  src/data_store/data_store_conduit.cpp
Labels: CI, review requested

#1483 Python frontend launcher will launch interactive job by default
  docs/running_lbann.rst
  python/lbann/contrib/launcher.py
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/systems.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/lsf.py
  python/lbann/launcher/slurm.py
Labels: python, refactor, review requested

#1478 Check labels in image data reader
  src/data_readers/data_reader_image.cpp
Labels: bug, review requested

#1482 Fix layer freezing
  include/lbann/layers/learning/fully_connected.hpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
  src/layers/learning/channelwise_fully_connected.cpp
Labels: bug, review requested

#1487 Add flexible error handling to Clara-based argument parser
  include/lbann/utils/argument_parser.hpp
  src/proto/proto_common.cpp
  src/utils/argument_parser.cpp
  src/utils/unit_test/argument_parser_test.cpp
Labels: enhancement, refactor, review requested
