Repository LLNL/lbann, pull requests merged in 2020-10, with the labels that each got.

#1622 Add a specialized FFT layer
  CMakeLists.txt
  bamboo/compiler_tests/build_script.sh
  bamboo/unit_tests/test_unit_layer_dft_abs.py
  cmake/configure_files/lbann_config.hpp.in
  cmake/modules/FindFFTW.cmake
  cmake/modules/FindcuFFT.cmake
  cmake/modules/SetupCUDAToolkit.cmake
  include/lbann/layers/misc/CMakeLists.txt
  include/lbann/layers/misc/dft_abs.hpp
  include/lbann/layers/misc/dft_abs_builder.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/cufft_wrapper.hpp
  include/lbann/utils/dim_helpers.hpp
  include/lbann/utils/fft_common.hpp
  include/lbann/utils/fftw_wrapper.hpp
  src/layers/misc/CMakeLists.txt
  src/layers/misc/dft_abs.cpp
  src/layers/misc/dft_abs.cu
  src/layers/misc/dft_abs_builder.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/utils/CMakeLists.txt
  src/utils/cufft_wrapper.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/cufft_test.cpp
  src/utils/unit_test/dim_helpers_test.cpp
  src/utils/unit_test/fftw_test.cpp
Labels: enhancement, review requested

#1644 Updated Hydrogen to v1.5.0 and Aluminum to v0.5.0
  CMakeLists.txt
  scripts/install_lbann.sh
Labels: enhancement

#1641 Optimize performance of GRU layer
  ReleaseNotes.txt
  applications/ATOM/models/vae.py
  bamboo/unit_tests/test_unit_layer_gru.py
  include/lbann/layers/learning/gru.hpp
  include/lbann/utils/cuda.hpp
  include/lbann/utils/cudnn.hpp
  scripts/install_lbann.sh
  src/layers/learning/gru.cpp
  src/proto/layers.proto
  src/utils/cuda.cu
  src/utils/cudnn.cpp
Labels: enhancement, review requested

#1646 Fixed dump_weights naming scheme
  include/lbann/weights/data_type_weights.hpp
  src/callbacks/dump_weights.cpp
  src/weights/data_type_weights.cpp
Labels: bug, review requested

#1651 Feature rng ltfb no sync
  include/lbann/utils/random_number_generators.hpp
  src/callbacks/ltfb.cpp
  src/utils/lbann_library.cpp
  src/utils/random.cpp
  src/utils/random_number_generators.cpp
Labels: enhancement

#1655 Disable global statistics
  include/lbann/utils/lbann_library.hpp
  src/callbacks/print_statistics.cpp
  src/callbacks/timer.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1656 Updated the WAE model to use the stacked GRU layer.
  applications/ATOM/models/wae.py
Labels: review requested

#1638 Refactor layers to use the cuDNN handle wrappers
  ReleaseNotes.txt
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/utils/cudnn.hpp
  include/lbann/utils/exception.hpp
  src/layers/learning/base_convolution.cpp
  src/utils/cudnn.cpp
  src/utils/unit_test/cufft_test.cpp
Labels: refactor, review requested

#1643 Abstract cuDNN from the Softmax implementation
  include/lbann/layers/activations/log_softmax.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/utils/dnn_lib/cudnn/softmax.hpp
  include/lbann/utils/dnn_lib/cudnn/utils.hpp
  src/layers/activations/log_softmax.cu
  src/layers/activations/softmax.cu
Labels: refactor, review requested

#1645 Abstract cuDNN from Dropout implementation
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/utils/dnn_lib/cudnn/dropout.hpp
Labels: refactor, review requested

#1664 Fixed two places where the hwloc bitmap was not properly deallocated.
  src/utils/threads/thread_pool.cpp
  src/utils/threads/thread_topology.cpp
Labels: bug, review requested

#1647 Abstract cuDNN from LRN implementation
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/utils/dnn_lib/cudnn/local_response_normalization.hpp
Labels: refactor, review requested

#1648 Abstract cuDNN from Pooling implementation
  include/lbann/layers/transform/pooling.hpp
  include/lbann/utils/dnn_lib/cudnn/pooling.hpp
Labels: refactor, review requested

#1633 Feature improvements for running at scale
  applications/ATOM/launch_merlin.sh
  applications/ATOM/merlin_pgen_make_test_permutations.py
  applications/ATOM/smiles_data_reader.prototext
  applications/ATOM/train_atom_vae.py
  applications/ATOM/train_atom_vae.yaml
  applications/ATOM/train_atom_wae.py
  applications/ATOM/train_atom_wae.yaml
  applications/ATOM/utils/flops.py
  applications/ATOM/utils/gather_atom_metrics.py
  applications/ATOM/utils/parse_objective.sh
  applications/ATOM/utils/parse_recon.sh
  applications/ATOM/utils/parse_time.sh
  scripts/install_lbann.sh
  spack_environments/llnl_lc/compilers.sh
  spack_environments/llnl_lc/externals-linux-rhel7-broadwell.sh
  spack_environments/llnl_lc/externals-linux-rhel7-power9le.sh
  src/base.cpp
  src/callbacks/ltfb.cpp
  src/data_readers/data_reader_smiles.cpp
Labels: enhancement

#1671 Fixed the resource launcher on lassen for the tests to set the correct
  bamboo/common_python/tools.py
Labels: bug

#1661 Update the CMake for HIP/ROCm integration
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  src/CMakeLists.txt
  src/layers/CMakeLists.txt
  src/layers/activations/CMakeLists.txt
  src/layers/image/CMakeLists.txt
  src/layers/learning/CMakeLists.txt
  src/layers/loss/CMakeLists.txt
  src/layers/math/CMakeLists.txt
  src/layers/misc/CMakeLists.txt
  src/layers/regularizers/CMakeLists.txt
  src/layers/transform/CMakeLists.txt
  src/objective_functions/CMakeLists.txt
  src/objective_functions/weight_regularization/CMakeLists.txt
  src/optimizers/CMakeLists.txt
  src/utils/CMakeLists.txt
  src/utils/unit_test/CMakeLists.txt
  superbuild/aluminum/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
Labels: build, review requested

#1672 Fix build errors when Distconv is enabled
  include/lbann/comm.hpp
  include/lbann/utils/distconv.hpp
  src/layers/learning/base_convolution.cpp
  src/utils/distconv.cpp
Labels: bug

#1673 Adding the CosmoFlow and the 3D U-Net models
  applications/physics/cosmology/cosmoflow/README.md
  applications/physics/cosmology/cosmoflow/cosmoflow.py
  applications/physics/cosmology/cosmoflow/split_cosmoflow_sample.py
  applications/segmentation/unet3d/README.md
  applications/segmentation/unet3d/unet3d.py
  applications/utils/verify_hdf5_dataset.py
  python/lbann/contrib/args.py
  python/lbann/core/util.py
Labels: enhancement

#1660 Abstract cuDNN from Convolution implementation
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/utils/dnn_lib/cudnn/convolution.hpp
  src/layers/learning/base_convolution.cpp
Labels: refactor, review requested

#1670 Refactor CUDA unary math functions
  include/lbann/utils/gpu/cuda.hpp
  include/lbann/utils/impl/cuda.hpp
Labels: refactor, review requested
