Repository LLNL/lbann, pull requests merged in 2020-11, with the labels that each got.

#1690 Bugfix distconv
  include/lbann/layers/io/input_layer.hpp
  include/lbann/utils/threads/thread_topology.hpp
  scripts/install_lbann.sh
  spack_environments/llnl_lc/externals-linux-rhel7-broadwell.sh
  spack_environments/llnl_lc/externals-linux-rhel7-haswell.sh
  spack_environments/llnl_lc/externals-linux-rhel7-ivybridge.sh
  spack_environments/llnl_lc/externals-linux-rhel7-power8le.sh
  spack_environments/llnl_lc/externals-linux-rhel7-power9le.sh
  spack_environments/olcf/externals-linux-rhel7-power9le.sh
  src/layers/io/input_layer.cpp
  src/utils/threads/thread_pool.cpp
  src/utils/threads/thread_topology.cpp
Labels: bug

#1692 Distribute ingestion of offline node2vec walks
  applications/graph/node2vec/data/offline_walks.py
  applications/graph/node2vec/default.config
  applications/graph/node2vec/main.py
  applications/graph/node2vec/test/test_offline_walks.py
Labels: application, review requested

#1691 Replace raw layer pointers with smart pointers
  include/lbann/layers/layer.hpp
  include/lbann/layers/misc/argmax.hpp
  include/lbann/layers/misc/argmin.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/metrics/layer_metric.hpp
  include/lbann/metrics/metric.hpp
  include/lbann/models/model.hpp
  include/lbann/objective_functions/layer_term.hpp
  include/lbann/objective_functions/objective_function.hpp
  include/lbann/objective_functions/objective_function_term.hpp
  include/lbann/proto/factories.hpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
  src/metrics/layer_metric.cpp
  src/metrics/metric.cpp
  src/models/model.cpp
  src/objective_functions/layer_term.cpp
  src/objective_functions/objective_function.cpp
  src/objective_functions/objective_function_term.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/model_factory.cpp
  src/proto/layers.proto
Labels: refactor, review requested

#1694 Replace raw weights pointers with smart pointers
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/embedding.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/transform/weights.hpp
  include/lbann/models/model.hpp
  include/lbann/objective_functions/objective_function.hpp
  include/lbann/objective_functions/objective_function_term.hpp
  include/lbann/weights/weights.hpp
  include/lbann/weights/weights_proxy.hpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
  src/layers/learning/base_convolution.cpp
  src/layers/learning/channelwise_fully_connected.cpp
  src/layers/learning/fully_connected.cpp
  src/layers/learning/gru.cpp
  src/models/model.cpp
  src/objective_functions/objective_function.cpp
  src/objective_functions/objective_function_term.cpp
  src/objective_functions/weight_regularization/l2.cpp
  src/proto/factories/layer_graph_factory.cpp
  src/proto/factories/model_factory.cpp
  src/weights/unit_test/weights_proxy_test.cpp
Labels: refactor, review requested

#1695 Manage metrics with smart pointers
  include/lbann/models/model.hpp
  src/models/model.cpp
  src/proto/factories/model_factory.cpp
Labels: refactor, review requested

#1685 Utility function to detect system in Bamboo tests
  bamboo/common_python/tools.py
  bamboo/compiler_tests/build_script.sh
  bamboo/unit_tests/test_unit_layer_gru.py
  bamboo/unit_tests/test_unit_layer_uniform_hash.py
Labels: CI, review requested

#1696 Manage objective function terms with smart pointers
  include/lbann/objective_functions/objective_function.hpp
  src/objective_functions/objective_function.cpp
  src/proto/factories/objective_function_factory.cpp
Labels: refactor, review requested

#1703 LBANN always sets the Hydrogen RNG seed
  ReleaseNotes.txt
  src/utils/random.cpp
  src/utils/random_number_generators.cpp
Labels: bug

#1701 Update documentation
  docs/bib/Dryden2016.rst
  docs/bib/Dryden2018.rst
  docs/bib/Dryden2019channel.rst
  docs/bib/Dryden2019spatial.rst
  docs/bib/Jacobs2017.rst
  docs/bib/Jacobs2019.rst
  docs/bib/Liu2019.rst
  docs/bib/VanEssen2015.rst
  docs/build_osx.rst
  docs/callbacks.rst
  docs/publications.rst
Labels: documentation, review requested

#1706 Remove pointer to LBANN comm in layer class
  include/lbann/layers/layer.hpp
  include/lbann/layers/transform/tessellate.hpp
  src/layers/distconv_adapter.cpp
  src/layers/layer.cpp
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
Labels: refactor, review requested

#1705 Better support for unknown systems in Python contrib launcher
  python/lbann/contrib/launcher.py
  python/lbann/contrib/lc/systems.py
  python/lbann/contrib/nersc/systems.py
  python/lbann/contrib/olcf/systems.py
Labels: bug, python, review requested

#1704 Flatten layer class hierarchy
  include/lbann/layers/learning/CMakeLists.txt
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/learning/learning.hpp
  include/lbann/layers/regularizers/CMakeLists.txt
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/regularizers/regularizer.hpp
  include/lbann/layers/regularizers/selu_dropout.hpp
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/categorical_random.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/discrete_random.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/in_top_k.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/sort.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/transform.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/unpooling.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/layers/transform/weights.hpp
  src/layers/learning/fully_connected.cpp
  src/layers/transform/evaluation.cpp
  src/proto/factories/layer_factory.cpp
Labels: refactor, review requested

#1674 Abstract CUDA backend implementation
  include/lbann/utils/gpu/cuda.hpp
  include/lbann/utils/gpu/gpu_lib.hpp
  include/lbann/utils/gpu/helpers.hpp
  include/lbann/utils/impl/cuda.hpp
  include/lbann/utils/impl/gpu_lib.hpp
  src/layers/math/unary.cu
  src/optimizers/adam.cu
  src/utils/cuda.cu
Labels: refactor, review requested

#1702 Support padding in distributed embedding layer
  bamboo/unit_tests/test_unit_layer_dist_embedding.py
  src/layers/misc/dist_embedding.cpp
  src/layers/misc/dist_embedding.cu
Labels: enhancement, review requested

#1710 Fix error with deterministic build in dropout layer
  include/lbann/layers/regularizers/dropout.hpp
Labels: bug, review requested

#1711 Use shared_ptr for weights in distributed embedding layer
  include/lbann/layers/misc/dist_embedding.hpp
Labels: bug, review requested

#1707 Allow LBANN to work with fewer samples than ranks per trainer
  src/data_coordinator/buffered_data_coordinator.cpp
Labels: enhancement

#1686 Refactor convolution algorithm selection and math type
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/layers/activations/log_softmax.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/data_type_layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/layers/learning/gru.hpp
  include/lbann/layers/regularizers/dropout.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/optimizers/adagrad.hpp
  include/lbann/utils/dnn_enums.hpp
  include/lbann/utils/dnn_lib/convolution.hpp
  include/lbann/utils/dnn_lib/cudnn.hpp
  include/lbann/utils/dnn_lib/cudnn/convolution.hpp
  include/lbann/utils/dnn_lib/cudnn/dropout.hpp
  include/lbann/utils/dnn_lib/cudnn/local_response_normalization.hpp
  include/lbann/utils/dnn_lib/cudnn/pooling.hpp
  include/lbann/utils/dnn_lib/cudnn/softmax.hpp
  include/lbann/utils/dnn_lib/cudnn/utils.hpp
  include/lbann/utils/dnn_lib/dnn_lib.hpp
  include/lbann/utils/dnn_lib/dropout.hpp
  include/lbann/utils/dnn_lib/helpers.hpp
  include/lbann/utils/dnn_lib/local_response_normalization.hpp
  include/lbann/utils/dnn_lib/miopen.hpp
  include/lbann/utils/dnn_lib/pooling.hpp
  include/lbann/utils/dnn_lib/softmax.hpp
  model_zoo/lbann.cpp
  src/base.cpp
  src/layers/activations/log_softmax.cu
  src/layers/activations/softmax.cu
  src/layers/learning/base_convolution.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
  src/layers/learning/gru.cpp
  src/proto/factories/layer_factory.cpp
  src/utils/cudnn.cpp
  src/utils/distconv.cpp
Labels: refactor, review requested

#1712 Include missing header in dropout layer
  include/lbann/layers/regularizers/dropout.hpp
Labels: bug, review requested

#1713 Fix assorted things that caused warnings when building with Clang
  include/lbann/data_coordinator/buffered_data_coordinator.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
  include/lbann/layers/io/input_layer.hpp
  include/lbann/metrics/layer_metric.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/training_algorithms/sgd_training_algorithm.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_numpy_npz.cpp
  src/execution_contexts/execution_context.cpp
  src/utils/cudnn.cpp
Labels: enhancement, review requested

#1714 Make sure CPU softmax layer has access to softmax mode enum
  include/lbann/layers/activations/softmax.hpp
Labels: bug, review requested

#1681 Atom bamboo integration
  applications/ATOM/train_atom_wae.py
  bamboo/common_python/data/atom/__init__.py
  bamboo/common_python/data/atom/data_reader_mpro.prototext
  bamboo/common_python/models/atom/wae.py
  bamboo/integration_tests/test_integration_atom_wae.py
  python/lbann/__init__.py
  python/lbann/core/util.py
Labels: CI, application, review requested
