Repository LLNL/lbann, pull requests merged in 2020-05, with the labels that each got.

#1523 Bugfix trainer specific callback outputs
  include/lbann/callbacks/callback.hpp
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/trainer_file_utils.hpp
  src/callbacks/dump_outputs.cpp
  src/utils/CMakeLists.txt
  src/utils/trainer_file_utils.cpp
Labels: bug, review requested

#1530 one-line bug fix for compiling in debug mode
  src/utils/lbann_library.cpp
Labels: bug, review requested

#1526 Remove deprecated model prototext files
  applications/physics/data/hydra_metadata.prototext
  bamboo/common_python/data/__init__.py
  bamboo/common_python/data/imagenet/__init__.py
  bamboo/common_python/data/imagenet/data_reader.prototext
  bamboo/common_python/data/mnist/__init__.py
  bamboo/common_python/data/mnist/data_reader.prototext
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_lenet.py
  bamboo/integration_tests/test_integration_resnet50.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
  model_zoo/data_readers/data_reader_imagenet.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_200x150x100x100x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp_500x250x100.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_sigmoid.prototext
  model_zoo/models/autoencoder_cifar10/model_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_cifar10/model_conv_autoencoder_cifar10.prototext
  model_zoo/models/autoencoder_imagenet/model_conv_autoencoder_imagenet.prototext
  model_zoo/models/autoencoder_mnist/model_autoencoder_mnist.prototext
  model_zoo/models/autoencoder_mnist/model_conv_autoencoder_mnist.prototext
  model_zoo/models/cosmoflow/model_cosmoflow.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m1_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m2_template.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3.prototext
  model_zoo/models/gan/jags/cycle_gan/cycgan_m3_template.prototext
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m1.py
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m2.py
  model_zoo/models/gan/jags/cycle_gan/generate_cycgan_m3.py
  model_zoo/models/jag/data_reader_jag_conduit.prototext
  model_zoo/models/jag/gan/cyclic/.gitignore
  model_zoo/models/jag/gan/cyclic/cyclic_gan_model.prototext
  model_zoo/models/jag/gan/cyclic/generate_model.py
  model_zoo/models/jag/gan/cyclic/model_template.prototext
  model_zoo/models/jag/gan/jag_data.prototext
  model_zoo/models/jag/gan/vanilla/.gitignore
  model_zoo/models/jag/gan/vanilla/gan.prototext
  model_zoo/models/jag/gan/vanilla/gan_template.prototext
  model_zoo/models/jag/gan/vanilla/generate_gan.py
  model_zoo/models/jag/input.minmax.1M.txt
  model_zoo/models/jag/scalar.minmax.1M.txt
  model_zoo/models/jag/vae_fcn.prototext
  model_zoo/models/jag/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/cycle_gan.prototext
  model_zoo/models/jag/wae_cycle_gan/cycle_gan_only.prototext
  model_zoo/models/jag/wae_cycle_gan/data_reader_jag_conduit_lassen.prototext
  model_zoo/models/jag/wae_cycle_gan/data_reader_jag_conduit_lustre.prototext
  model_zoo/models/jag/wae_cycle_gan/jag10k_data.prototext
  model_zoo/models/jag/wae_cycle_gan/jag_100M_metadata.prototext
  model_zoo/models/jag/wae_cycle_gan/wae.prototext
  model_zoo/models/jag/wae_cycle_gan/wae_fw_inv.prototext
  model_zoo/models/jag/wae_cycle_gan/wae_nobn.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_conv_molecular_bead_autoencoder_pilot2.prototext
  model_zoo/models/molecular_autoencoder_candle_pilot2/model_molecular_autoencoder_pilot2.prototext
  model_zoo/models/simple_mnist/README
  model_zoo/models/simple_mnist/model_mnist_simple_1.prototext
  model_zoo/models/simple_mnist/model_mnist_simple_2.prototext
  python/lbann/models/README.md
Labels: review requested

#1531 Fix AlexNet and ResNet integrated tests
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_resnet50.py
Labels: bug

#1537 Address issue #1536
  scripts/build_lbann_lc.sh
  scripts/install_lbann.sh
  spack_environments/superbuild_lbann_with_hydrogen_and_aluminum.sh
Labels: bug, review requested

#1535 Fail hard if an exception is not caught by the time it reaches main()
  model_zoo/lbann.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_inf.cpp
Labels: CI, bug, enhancement, review requested

#1534 Add per-convolutional-layer support for cuDNN tensor operations
  applications/vision/resnet.py
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/utils/argument_parser.hpp
  include/lbann/utils/cublas.hpp
  include/lbann/utils/cudnn.hpp
  model_zoo/lbann.cpp
  src/layers/learning/convolution.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/utils/argument_parser.cpp
  src/utils/cublas.cpp
  src/utils/cudnn.cpp
  src/utils/unit_test/argument_parser_test.cpp
Labels: enhancement, review requested

#1542 Fix a bug related to some recent changes in Hydrogen
  src/comm.cpp
Labels: bug, review requested

#1539 Fix PFE where trainer requires mini_batch_size
  applications/ATOM/train_atom_char_rnn.py
  applications/CANDLE/pilot2/train_ras_classifier.py
  applications/physics/ICF/eval_macc_surrogate.py
  applications/physics/ICF/pre_train_jag_wae.py
  applications/physics/ICF/train_macc_surrogate.py
  applications/selfsupervised/classifier.py
  applications/selfsupervised/main.py
  applications/selfsupervised/pretrain_siamese.py
Labels: bug, review requested

#1544 Fix bug when generating uniform random doubles
  include/lbann/utils/beta.hpp
  include/lbann/utils/random.hpp
  src/utils/unit_test/random_test.cpp
Labels: bug, review requested

#1545 Fix bug in utility function that generates uniform random floats
  include/lbann/utils/random.hpp
Labels: bug

#1550 Add option to shuffle data in Python data reader
  applications/graph/main.py
  applications/nlp/rnn/main.py
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_datastore_imagenet.py
  include/lbann/data_readers/data_reader_python.hpp
  src/data_readers/data_reader_python.cpp
  src/proto/proto_common.cpp
Labels: enhancement, review requested

#1549 Fix LBANN inference
  applications/physics/ICF/eval_macc_surrogate.py
  include/lbann/callbacks/load_model.hpp
  model_zoo/lbann_inf.cpp
  src/callbacks/load_model.cpp
  src/training_algorithms/sgd_training_algorithm.cpp
Labels: bug
