Repository LLNL/lbann, pull requests merged in 2020-01, with the labels that each got.

#1396 Fix typo in layer factory for "not equal" layer
  src/proto/factories/layer_factory.cpp
Labels: bug

#1391 Support sequences in embedding layer
  bamboo/unit_tests/test_unit_layer_embedding.py
  include/lbann/layers/learning/embedding.hpp
  src/layers/learning/embedding.cpp
  src/layers/learning/embedding.cu
Labels: enhancement, review requested

#1393 Optimize performance of node2vec
  applications/graph/dataset.py
  applications/graph/main.py
Labels: application

#1398 Update NLP example models to use new embedding layer functionality
  applications/nlp/rnn/main.py
  applications/nlp/transformer/main.py
Labels: application, bug

#1400 data readers: absolute sample counts are broken
  include/lbann/data_readers/data_reader.hpp
  src/data_readers/data_reader.cpp
  src/proto/proto_common.cpp
Labels: bug

#1389 Support the "channel" mode in softmax layers
  include/lbann/layers/activations/softmax.hpp
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement

#1410 Added guards for when the GPU FP16 datat type isn't supported.
  include/lbann/utils/impl/cuda.hpp
  src/utils/cudnn.cpp
Labels: bug

#1397 Instance norm layer
  bamboo/unit_tests/test_unit_layer_instance_norm.py
  include/lbann/layers/layer.hpp
  include/lbann/layers/regularizers/instance_norm.hpp
  include/lbann/lbann.hpp
  src/layers/regularizers/CMakeLists.txt
  src/layers/regularizers/instance_norm.cpp
  src/layers/regularizers/instance_norm.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1403 Channel-wise fully-connected layer
  bamboo/unit_tests/test_unit_layer_channelwise_fully_connected.py
  include/lbann/layers/learning/CMakeLists.txt
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/channelwise_fully_connected.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1404 Channel-wise softmax layer
  bamboo/unit_tests/test_unit_layer_channelwise_softmax.py
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/misc/channelwise_softmax.hpp
  include/lbann/lbann.hpp
  src/layers/misc/CMakeLists.txt
  src/layers/misc/channelwise_softmax.cpp
  src/layers/misc/channelwise_softmax.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1406 Fix testing on pascal
  bamboo/common_python/tools.py
  bamboo/integration_tests/test_integration_lenet.py
  bamboo/unit_tests/test_unit_reconstruction_loss.py
Labels: CI, bug, review requested

#1415 require version 1.3.3 of Hydrogen
  CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
Labels: build, review requested

#1419 Fix builder error signatures
  src/layers/learning/channelwise_fully_connected.cpp
  src/layers/learning/channelwise_scale_bias_builder.cpp
  src/layers/learning/embedding_builder.cpp
  src/layers/misc/channelwise_softmax.cpp
  src/layers/regularizers/instance_norm.cpp
  src/layers/transform/crop_builder.cpp
  src/layers/transform/pooling.cpp
Labels: bug, review requested

#1418 Moved the definition of WeightsDataType and AbsMatrixType into the
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  src/layers/learning/channelwise_fully_connected.cpp
Labels: bug

#1416 Fix bug when slice layer has only one output
  bamboo/unit_tests/test_unit_layer_slice.py
  include/lbann/layers/transform/slice.hpp
  src/layers/transform/slice.cpp
  src/layers/transform/slice.cu
Labels: bug, review requested

#1417 Update transformer model to use new channel-wise layers
  applications/nlp/transformer/main.py
  applications/nlp/transformer/model.py
  python/lbann/modules/transformer.py
Labels: application, review requested

#1425 Fix incorrect sbatch option in SLURM job launcher
  python/lbann/launcher/slurm.py
Labels: bug, python
