Repository LLNL/lbann, pull requests merged in 2020-02, with the labels that each got.

#1424 Add H2 to the build system as an optional package
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  docs/build_with_cmake.rst
  include/lbann/utils/factory.hpp
  include/lbann/utils/factory_error_policies.hpp
  include/lbann/utils/h2_tmp.hpp
  src/utils/unit_test/factory_test.cpp
Labels: build, enhancement, review requested

#1423 Fix bug in LTFB with checkpoint file communication
  include/lbann/layers/io/input/generic_input_layer.hpp
  src/callbacks/ltfb.cpp
Labels: bug, review requested

#1429 Bugfix for linker error from #1420
  src/callbacks/ltfb.cpp
Labels: bug

#1440 Add a TCL module
  CMakeLists.txt
  cmake/configure_files/lbann_module.tcl.in
Labels: enhancement, review requested

#1430 Data_store_conduit one off bug
  include/lbann/data_store/data_store_conduit.hpp
  src/data_readers/data_reader_npz_ras_lipid.cpp
  src/data_store/data_store_conduit.cpp
Labels: bug, review requested

#1432 Mpi error catching
  include/lbann/base.hpp
  src/base.cpp
  tests/CMakeLists.txt
  tests/test_mpi_err_handling.cpp
Labels: enhancement, review requested

#1445 Add options for bias and transpose in channel-wise FC layer
  bamboo/unit_tests/test_unit_layer_channelwise_fully_connected.py
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  src/layers/learning/channelwise_fully_connected.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1447 Evaluate Transformer on WMT 2014 dataset
  applications/nlp/README.md
  applications/nlp/experiments/.gitignore
  applications/nlp/transformer/dataset.py
  applications/nlp/transformer/evaluate.py
  applications/nlp/transformer/main.py
  applications/nlp/transformer/train.py
  applications/nlp/utils/paths.py
  python/lbann/models/__init__.py
  python/lbann/models/transformer.py
Labels: application, python, review requested

#1456 Generalize the system-optimized LBANN launcher
  applications/ATOM/train_atom_char_rnn.py
  applications/CANDLE/pilot2/train_ras_classifier.py
  applications/graph/main.py
  applications/nlp/rnn/main.py
  applications/nlp/transformer/train.py
  applications/physics/cosmology/ExaGAN/train_exagan.py
  applications/vision/alexnet.py
  applications/vision/densenet.py
  applications/vision/lenet.py
  applications/vision/resnet.py
  bamboo/common_python/tools.py
  docs/running_lbann.rst
  python/lbann/contrib/launcher.py
  python/lbann/contrib/lc/launcher.py
  python/lbann/launcher/__init__.py
Labels: python, refactor, review requested

#1458 fix the compilation error in debug mode
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/layers/regularizers/dropout.hpp
  src/data_store/data_store_conduit.cpp
Labels: bug, build, review requested
