Repository LLNL/lbann, pull requests merged in 2020-07, with the labels that each got.

#1579 Get environment variables from user's environment in contrib launcher
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/nersc/launcher.py
Labels: python, review requested

#1582 Bug fix and update to ATOM model
  applications/ATOM/train_atom_char_rnn.py
Labels: bug

#1562 Distributed embedding layer
  bamboo/unit_tests/test_unit_layer_dist_embedding.py
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/layers/misc/dist_embedding.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/any.hpp
  include/lbann/utils/memory.hpp
  include/lbann/utils/nvshmem.hpp
  include/lbann/weights/CMakeLists.txt
  include/lbann/weights/weights_helpers.hpp
  src/base.cpp
  src/layers/misc/CMakeLists.txt
  src/layers/misc/dist_embedding.cpp
  src/layers/misc/dist_embedding.cu
  src/layers/regularizers/batch_normalization.cpp
  src/layers/regularizers/batch_normalization.cu
  src/layers/regularizers/entrywise_batch_normalization.cpp
  src/layers/regularizers/entrywise_batch_normalization.cu
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
  src/utils/nvshmem.cu
Labels: enhancement, review requested

#1575 Pair RNG with I/O thread work
  bamboo/integration_tests/test_integration_alexnet.py
  bamboo/integration_tests/test_integration_lenet.py
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_python.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/lbann_library.hpp
  include/lbann/utils/random_number_generators.hpp
  include/lbann/utils/threads/CMakeLists.txt
  include/lbann/utils/threads/thread_pool.hpp
  include/lbann/utils/threads/thread_topology.hpp
  python/lbann/contrib/lc/launcher.py
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_python.cpp
  src/proto/proto_common.cpp
  src/transforms/vision/unit_test/horizontal_flip_test.cpp
  src/transforms/vision/unit_test/random_affine_test.cpp
  src/transforms/vision/unit_test/random_crop_test.cpp
  src/transforms/vision/unit_test/random_resized_crop_test.cpp
  src/transforms/vision/unit_test/random_resized_crop_with_fixed_aspect_ratio_test.cpp
  src/transforms/vision/unit_test/vertical_flip_test.cpp
  src/utils/lbann_library.cpp
  src/utils/random.cpp
  src/utils/random_number_generators.cpp
  src/utils/threads/CMakeLists.txt
  src/utils/threads/thread_pool.cpp
  src/utils/threads/thread_topology.cpp
  src/utils/threads/thread_utils.cpp
  src/weights/data_type_weights.cpp
Labels: bug, review requested

#1591 Updated the thread topology code to be compliant with Hydrogen 1.4 API
  src/utils/threads/thread_topology.cpp
Labels: bug
