Repository LLNL/lbann, pull requests merged in 2021-08, with the labels that each got.

#1934 Remove the autogenerated Breathe API documentation.
  docs/SourceTreeDoxyfile
  docs/conf.py
  docs/index.rst
  docs/lbann-api.rst
Labels: documentation

#1925 Add the hdf5 schema generator utility
  CMakeLists.txt
  data_utils/CMakeLists.txt
  data_utils/hdf5/CMakeLists.txt
  data_utils/hdf5/generate_schema_and_sample_list.cpp
  data_utils/hdf5/helpers.cpp
  data_utils/hdf5/helpers.hpp
  data_utils/hdf5/test_helpers.cpp
  data_utils/hdf5/test_main.cpp
Labels: enhancement, review requested

#1935 Disable K-FAC GRU implementation in GPU builds without cuDNN
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
Labels: bug, review requested

#1939 Run ExaGAN discriminators fully within distconv
  applications/physics/cosmology/ExaGAN/DistConvGAN.py
  applications/physics/cosmology/ExaGAN/train_distconv_gan.py
  include/lbann/layers/data_type_layer.hpp
  src/layers/learning/base_convolution.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
Labels: application, bug, review requested

#1941 Remove Catch2 dependency if unit tests are not enabled
  data_utils/hdf5/CMakeLists.txt
Labels: bug, review requested, build

#1938 Update the perturb weight callback
  include/lbann/callbacks/perturb_weights.hpp
  src/callbacks/perturb_weights.cpp
  src/proto/callbacks.proto
Labels: enhancement, review requested

#1930 Mutation Strategy of Replacing Random Activation
  include/lbann/execution_algorithms/ltfb/mutation_strategy.hpp
  include/lbann/execution_algorithms/ltfb/random_pairwise_exchange.hpp
  python/lbann/core/training_algorithm.py
  src/execution_algorithms/ltfb/CMakeLists.txt
  src/execution_algorithms/ltfb/mutation_strategy.cpp
  src/execution_algorithms/ltfb/random_pairwise_exchange.cpp
  src/models/model.cpp
  src/proto/training_algorithm.proto
Labels: enhancement, review requested

#1943 Fix initialization order warning in "perturb weights" callback
  include/lbann/callbacks/perturb_weights.hpp
  src/callbacks/perturb_weights.cpp
Labels: review requested, documentation

#1942 Update the rotation layer
  src/layers/image/rotation.cpp
Labels: enhancement, review requested

#1949 Fix error in data buffer with distconv CosmoFlow data
  src/data_coordinator/buffered_data_coordinator.cpp
Labels: bug, review requested

#1944 Add an image layer for multiple operation
  include/lbann/layers/image/CMakeLists.txt
  include/lbann/layers/image/composite_image_transformation.hpp
  src/layers/image/CMakeLists.txt
  src/layers/image/cereal_registration/CMakeLists.txt
  src/layers/image/cereal_registration/composite_image_transformation.cpp
  src/layers/image/composite_image_transformation.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1948 Mutation Strategy of Replacing Random Convolution
  include/lbann/execution_algorithms/ltfb/mutation_strategy.hpp
  include/lbann/models/model.hpp
  python/lbann/core/training_algorithm.py
  src/execution_algorithms/ltfb/mutation_strategy.cpp
  src/execution_algorithms/ltfb/random_pairwise_exchange.cpp
  src/models/model.cpp
  src/proto/training_algorithm.proto
Labels: enhancement, review requested

#1933 Reimplementation of Graph Neural Networks with Scatter/Gather layers
  applications/graph/GNN/Dense_Graph_Trainer.py
  applications/graph/GNN/NNConvModel.py
  applications/graph/GNN/OGB_LBANN_Trainer.py
  applications/graph/GNN/README.md
  applications/graph/GNN/Sparse_Graph_Trainer.py
  applications/graph/GNN/data/LSC_PPQM4M/LSC_100K.py
  applications/graph/GNN/data/MNIST_Superpixel/__init__.py
  applications/graph/GNN/data/MNIST_Superpixel/update_adj_mat.py
  applications/graph/GNN/data/MNIST_Superpixel/utils.py
  applications/graph/GNN/data/PROTEINS/PROTEINS_Dataset.py
  applications/graph/GNN/data/PROTEINS/PROTEINS_Dense_Dataloader.py
  applications/graph/GNN/data/PROTEINS/PROTEINS_Sparse_Dataloader.py
  applications/graph/GNN/data/PROTEINS/__init__.py
  applications/graph/GNN/data/PROTEINS/utils.py
  applications/graph/GNN/main.py
  applications/graph/GNN/test/test_integration_DGCN.py
  applications/graph/GNN/test/test_integration_DGraph.py
  applications/graph/GNN/test/test_integration_GCN.py
  applications/graph/GNN/test/test_integration_GIN.py
  applications/graph/GNN/test/test_integration_GatedGraph.py
  applications/graph/GNN/test/test_integration_Graph.py
  applications/graph/GNN/test/test_integration_NNConv.py
  bamboo/unit_tests/test_unit_layer_channelwise_gru_cell.py
  include/lbann/layers/transform/reshape.hpp
  python/lbann/modules/__init__.py
  python/lbann/modules/graph/__init__.py
  python/lbann/modules/graph/sparse/GCNConv.py
  python/lbann/modules/graph/sparse/GINConv.py
  python/lbann/modules/graph/sparse/GatedGraphConv.py
  python/lbann/modules/graph/sparse/GraphConv.py
  python/lbann/modules/graph/sparse/NNConv.py
  python/lbann/modules/graph/utils.py
  python/lbann/modules/rnn.py
Labels: review requested, application

#1947 Remove the explicit finding of HDF5
  CMakeLists.txt
  python/lbann/contrib/lc/launcher.py
  python/lbann/contrib/lc/systems.py
Labels: review requested, build

#1953 Fix typo in Python frontend launcher on LC systems
  python/lbann/contrib/lc/launcher.py
Labels: bug, python

#1946 Accommodate large channel dim in CUDA kernels for channel-wise layers
  include/lbann/utils/gpu/gpu_lib.hpp
  include/lbann/utils/impl/gpu_lib.hpp
  src/layers/learning/channelwise_scale_bias.cu
  src/layers/misc/channelwise_mean.cu
  src/layers/misc/channelwise_softmax.cu
  src/layers/regularizers/batch_normalization.cu
  src/layers/regularizers/instance_norm.cu
  src/layers/transform/gather.cu
  src/layers/transform/scatter.cu
  src/utils/cuda.cu
  src/utils/rocm.cpp
Labels: bug, review requested

#1954 Fix a batch of warnings introduced in recent PRs.
  src/data_readers/unit_test/data_reader_HDF5_sample_list_test.cpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
  src/models/model.cpp
  src/operators/math/unit_test/clamp_test.cpp
  src/utils/miopen.cpp
Labels: bug, review requested, build

#1957 Bugfix for sample list
  include/lbann/data_readers/sample_list_open_files_impl.hpp
Labels: bug
