Repository LLNL/lbann, pull requests merged in 2021-05, with the labels that each got.

#1862 Correctly shuffle data in CosmoFlow app
  applications/physics/cosmology/cosmoflow/cosmoflow.py
Labels: application, bug

#1863 Removed local fields to track if a data reader has labels or responses
  include/lbann/data_readers/compound_data_reader.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_hdf5.hpp
  include/lbann/data_readers/data_reader_numpy.hpp
  include/lbann/data_readers/data_reader_numpy_npz.hpp
  include/lbann/data_readers/data_reader_numpy_npz_conduit.hpp
  src/data_readers/data_reader_numpy.cpp
  src/data_readers/data_reader_numpy_npz.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
Labels: bug

#1866 Make build_lbann.sh script extensible
  ReleaseNotes.txt
  applications/ATOM/README.md
  applications/ATOM/build_lbann_atom_user.sh
  applications/ATOM/external_packages_atom.sh
  docs/building_lbann.rst
  scripts/.build_lbann_as_user.sh
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
Labels: enhancement

#1865 Documentation for training algorithms
  ReleaseNotes.txt
  docs/BuildRSTDocs.py
  docs/building_lbann.rst
  docs/conf.py
  docs/execution_algorithms.rst
  docs/execution_algorithms/batched_inference.rst
  docs/execution_algorithms/batched_iterative_optimization.rst
  docs/execution_algorithms/ltfb.rst
  docs/index.rst
  docs/publications.rst
  python/lbann/__init__.py
  python/lbann/core/callback.py
  python/lbann/core/layer.py
  python/lbann/core/optimizer.py
  python/lbann/core/weights.py
Labels: documentation, in progress, review requested

#1774 Add clang-format specification
  .clang-format
  CMakeLists.txt
  cmake/modules/LBANNClangFormat.cmake
Labels: enhancement, review requested

#1837 Optimizing tessellate, concatenate, and slice layers on CPU
  ReleaseNotes.txt
  src/layers/transform/concatenate.cpp
  src/layers/transform/slice.cpp
  src/layers/transform/tessellate.cpp
Labels: enhancement

#1839 CMake modifications inspired by work on Fugaku
  CMakeLists.txt
  cmake/configure_files/LBANNConfig.cmake.in
  cmake/modules/SetupCXX.cmake
Labels: build, review requested

#1811 Add initial mockup of transform documentation
  docs/SourceTreeDoxyfile
  docs/conf.py
  docs/data_transforms.rst
  docs/index.rst
Labels: documentation, enhancement, review requested

#1870 Fix install tree padding
  scripts/build_lbann.sh
Labels: bug

#1872 Download MNIST from PyTorch mirror
  applications/vision/data/mnist/__init__.py
Labels: application, bug, review requested

#1873 Fixed bug where Spack test command was not passed to install
  scripts/build_lbann.sh
Labels: bug
