Repository LLNL/lbann, pull requests merged in 2021-11, with the labels that each got.

#1986 Restore support for labels and responses in synthetic data reader
  src/data_readers/data_reader_synthetic.cpp
Labels: bug, review requested

#1984 Bugfix for polynomial learning rate schedule
  bamboo/unit_tests/test_unit_callback_poly_learning_rate.py
  include/lbann/callbacks/learning_rate.hpp
  src/callbacks/learning_rate.cpp
Labels: bug, review requested

#1995 Fix bug with user-specified random seeds
  src/proto/proto_common.cpp
  src/utils/options.cpp
Labels: bug, review requested

#1990 Debugging Distconv models
  applications/physics/cosmology/ExaGAN/train_distconv_gan.py
  include/lbann/layers/io/input_layer.hpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/layers/io/input_layer.cpp
  src/proto/proto_common.cpp
Labels: bug, review requested

#2000 Fix compile errors with distconv
  src/layers/data_type_distconv_adapter.cpp
  src/layers/io/input_layer.cpp
Labels: bug, review requested

#2005 Optimize GPU entry-wise operator functions with contiguous data
  include/lbann/utils/impl/gpu_lib.hpp
  src/layers/activations/relu.cu
Labels: enhancement, review requested, refactor

#2006 Fix grid dimensions in GPU entry-wise operator functions
  include/lbann/utils/impl/gpu_lib.hpp
Labels: bug, review requested

#2007 Use Aluminum shuffler in Distconv for ExaGAN model
  applications/physics/cosmology/ExaGAN/train_distconv_gan.py
Labels: review requested, application

#2008 Remove a redundant symbol from the layer API
  include/lbann/layers/layer.hpp
Labels: bug

#2012 Explicitly set the search name for Cereal to be all lowercase.
  CMakeLists.txt
  cmake/configure_files/LBANNConfig.cmake.in
Labels: bug, review requested, build

#2013 Cleanup Clang warnings
  src/data_readers/data_reader.cpp
  src/execution_algorithms/ltfb/checkpoint_common.hpp
Labels: review requested, build

#2015 Add option for distconv height groups in ExaGAN app
  applications/physics/cosmology/ExaGAN/train_distconv_gan.py
Labels: review requested, application
