Repository LLNL/lbann, pull requests merged in 2021-04, with the labels that each got.

#1827 Reformatting, documentation, and slight API tweaks
  include/lbann/execution_algorithms/sgd_training_algorithm.hpp
  include/lbann/execution_algorithms/training_algorithm.hpp
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
  src/callbacks/checkpoint.cpp
  src/callbacks/dump_weights.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/execution_algorithms/training_algorithm.cpp
  src/execution_contexts/execution_context.cpp
  src/execution_contexts/sgd_execution_context.cpp
  src/trainers/trainer.cpp
Labels: enhancement, refactor

#1828 Reformat trainer and frontend
  include/lbann/trainers/trainer.hpp
  model_zoo/lbann.cpp
  src/trainers/trainer.cpp
Labels: review requested

#1848 Fixed checkpointing of inference execution mode.
  include/lbann/io/persist.hpp
Labels: bug

#1849 Cleanup execution context
  include/lbann/callbacks/callback.hpp
  include/lbann/execution_contexts/execution_context.hpp
  include/lbann/execution_contexts/sgd_execution_context.hpp
  include/lbann/layers/io/input_layer.hpp
  include/lbann/trainers/trainer.hpp
  include/lbann/utils/lbann_library.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_inf.cpp
  src/callbacks/check_dataset.cpp
  src/callbacks/check_gradients.cpp
  src/callbacks/checkpoint.cpp
  src/callbacks/debug_io.cpp
  src/callbacks/dump_minibatch_sample_indices.cpp
  src/callbacks/dump_weights.cpp
  src/callbacks/learning_rate.cpp
  src/callbacks/ltfb.cpp
  src/callbacks/monitor_io.cpp
  src/callbacks/print_statistics.cpp
  src/callbacks/save_model.cpp
  src/callbacks/summarize_images.cpp
  src/callbacks/timer.cpp
  src/callbacks/variable_minibatch.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/execution_contexts/execution_context.cpp
  src/execution_contexts/sgd_execution_context.cpp
  src/layers/io/input_layer.cpp
  src/models/model.cpp
  src/proto/factories/trainer_factory.cpp
  src/trainers/trainer.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, refactor, review requested

#1846 Build script uses clingo
  docs/building_lbann.rst
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
Labels: enhancement

#1851 Fix LTFB's SendRecvWeights algorithm for handling different optimizers.
  include/lbann/optimizers/adagrad.hpp
  include/lbann/optimizers/adam.hpp
  include/lbann/optimizers/data_type_optimizer.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/optimizers/rmsprop.hpp
  include/lbann/optimizers/sgd.hpp
  src/callbacks/ltfb.cpp
  src/optimizers/data_type_optimizer.cpp
Labels: enhancement, review requested

#1853 Added the C language to the CMakeLists.txt and SetupMPI.cmake to
  CMakeLists.txt
  cmake/modules/SetupMPI.cmake
  scripts/build_lbann.sh
Labels: bug

#1854 Enable spack buildcache
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
Labels: bug, enhancement

#1859 Fix linkage issues in unit tests on OSX.
  src/utils/serialize_matrices/AbstractDistMatrix.cpp
  src/utils/serialize_matrices/CMakeLists.txt
  src/utils/serialize_matrices/Matrix.cpp
Labels: bug, review requested
