Repository LLNL/lbann, pull requests merged in 2021-07, with the labels that each got.

#1906 Bugfix for ROCm convolution
  include/lbann/utils/dnn_lib/miopen/convolution.hpp
  src/utils/miopen.cpp
Labels: bug, review requested

#1907 Fix a compilation error in gru layer
  include/lbann/layers/learning/gru.hpp
  src/layers/learning/gru.cpp
Labels: bug, build, review requested

#1902 Fix warnings of the day
  include/lbann/execution_algorithms/kfac/kfac_block_gru.hpp
  src/data_readers/unit_test/data_reader_smiles_fetch_datum_test.cpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
Labels: review requested

#1899 Add functionality to insert, remove and replace layers in the model
  include/lbann/models/model.hpp
  src/models/model.cpp
  src/models/unit_test/CMakeLists.txt
  src/models/unit_test/modify_test.cpp
Labels: enhancement, review requested

#1910 Disable LC build cache in build script
  scripts/customize_build_env.sh
Labels: bug, build, review requested

#1911 Fix segfault when checkpointing channel-wise mean layer
  include/lbann/layers/misc/channelwise_mean.hpp
Labels: bug, review requested

#1913 Fix compile error in channel-wise mean layer
  include/lbann/layers/misc/channelwise_mean.hpp
Labels: bug, review requested

#1912 Fix Corona build
  include/lbann/layers/transform/cross_grid_sum.hpp
  include/lbann/layers/transform/cross_grid_sum_slice.hpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
  src/models/model.cpp
Labels: bug, build, review requested

#1909 Run Catch2 tests and save Spack artifacts in Bamboo
  bamboo/compiler_tests/test_compiler.py
  bamboo/unit_tests/test_catch2_unit_tests.py
Labels: CI, enhancement

#1914 Align layer inputs when needed
  src/layers/data_type_layer.cpp
Labels: bug, review requested

#1915 Skip the DFT test on Corona
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_layer_dft_abs.py
Labels: CI, review requested

#1898 2D Scatter-Gather
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_layer_gather.py
  bamboo/unit_tests/test_unit_layer_scatter.py
  include/lbann/layers/transform/gather.hpp
  include/lbann/layers/transform/scatter.hpp
  src/layers/transform/gather.cpp
  src/layers/transform/gather.cu
  src/layers/transform/scatter.cpp
  src/layers/transform/scatter.cu
Labels: enhancement, review requested

#1908 Adding implementation for callback to perturb weights.
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/perturb_weights.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/perturb_weights.cpp
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
Labels: enhancement, review requested

#1916 Fix launch issue on Lassen
  bamboo/unit_tests/test_catch2_unit_tests.py
Labels: CI, bug, review requested

#1901 Channelwise Fully Connected Distconv Layer
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_layer_channelwise_fully_connected_distconv.py
  include/lbann/layers/learning/CMakeLists.txt
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  include/lbann/layers/learning/distconv/CMakeLists.txt
  include/lbann/layers/learning/distconv/distconv_layers.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/distconv.hpp
  src/layers/distconv_adapter.cpp
  src/layers/learning/CMakeLists.txt
  src/layers/learning/channelwise_fully_connected.cpp
  src/layers/learning/distconv/CMakeLists.txt
  src/layers/learning/distconv/distconv_layers.cpp
Labels: enhancement, review requested

#1918 Make data_type_layer safe for self-assignment
  src/layers/data_type_layer.cpp
Labels: bug, enhancement, review requested

#1919 Fix typo in build script cmd line args
  scripts/build_lbann.sh
Labels: bug

#1921 Fix invalid comparison in scatter layer
  include/lbann/layers/transform/scatter.hpp
Labels: bug, review requested

#1813 Actually-non-blocking allreduce without Aluminum
  include/lbann/comm.hpp
  include/lbann/comm_impl.hpp
  src/comm.cpp
  src/layers/transform/evaluation.cpp
Labels: enhancement, review requested

#1923 Fix typo in build_lbann.sh
  scripts/build_lbann.sh
Labels: review requested

#1922 Remove redundant check in "perturb weights" callback
  src/callbacks/perturb_weights.cpp
Labels: bug, review requested

#1688 Data reader hdf5
  ReleaseNotes.txt
  applications/dataset_schemas/jag_useme.json
  applications/dataset_schemas/jag_useme_short.json
  include/lbann/comm.hpp
  include/lbann/data_coordinator/data_coordinator.hpp
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_HDF5.hpp
  include/lbann/data_readers/data_reader_hdf5_legacy.hpp
  include/lbann/data_readers/data_reader_sample_list.hpp
  include/lbann/data_readers/sample_list_open_files.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  include/lbann/lbann.hpp
  spack_environments/std_versions_and_variants.sh
  src/callbacks/check_nan.cpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_HDF5.cpp
  src/data_readers/data_reader_hdf5_legacy.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_sample_list.cpp
  src/data_readers/unit_test/CMakeLists.txt
  src/data_readers/unit_test/data_reader_HDF5_hrrl_data_test.cpp
  src/data_readers/unit_test/data_reader_HDF5_sample_list_test.cpp
  src/data_readers/unit_test/data_reader_HDF5_test.cpp
  src/data_readers/unit_test/data_reader_common_catch2.hpp
  src/data_readers/unit_test/test_data/hdf5_hrrl_data_schema.yaml
  src/data_readers/unit_test/test_data/hdf5_hrrl_experiment_schema.yaml
  src/data_readers/unit_test/test_data/hdf5_hrrl_reader.prototext
  src/data_readers/unit_test/test_data/hdf5_hrrl_test.sample_list
  src/data_readers/unit_test/test_data/hdf5_hrrl_train.sample_list
  src/data_readers/unit_test/test_data/hdf5_hrrl_validate.sample_list
  src/data_readers/unit_test/test_data/hdf5_reader.prototext.inc
  src/proto/proto_common.cpp
  src/proto/reader.proto
  src/utils/file_utils.cpp
  src/utils/lbann_library.cpp
  unit_test/MPICatchMain.cpp
  unit_test/SequentialCatchMain.cpp
Labels: application, enhancement, in progress, refactor

#1903 Restore global batch/epoch count for validation
  include/lbann/execution_algorithms/sgd_training_algorithm.hpp
  src/execution_algorithms/sgd_training_algorithm.cpp
Labels: review requested

#1926 Add image layer for rotation operation
  include/lbann/layers/image/CMakeLists.txt
  include/lbann/layers/image/rotation.hpp
  src/layers/image/CMakeLists.txt
  src/layers/image/cereal_registration/CMakeLists.txt
  src/layers/image/cereal_registration/rotation.cpp
  src/layers/image/rotation.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1929 Fix compile errors in rotation layer
  include/lbann/layers/image/rotation.hpp
  src/layers/image/rotation.cpp
  src/proto/layers.proto
Labels: bug, review requested

#1928 Add axis parameter to Scatter-Gather layers
  bamboo/unit_tests/test_unit_layer_gather.py
  bamboo/unit_tests/test_unit_layer_scatter.py
  include/lbann/layers/transform/gather.hpp
  include/lbann/layers/transform/scatter.hpp
  src/layers/transform/cereal_registration/gather.cpp
  src/layers/transform/cereal_registration/scatter.cpp
  src/layers/transform/gather.cpp
  src/layers/transform/gather.cu
  src/layers/transform/gather_builder.cpp
  src/layers/transform/scatter.cpp
  src/layers/transform/scatter.cu
  src/layers/transform/scatter_builder.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1892 Bugfix for user builds
  scripts/build_lbann.sh
Labels: bug

#1924 Basic sub-grid parallelism for FC and Conv
  applications/optimizers/kfac/kfac.py
  bamboo/unit_tests/test_unit_algo_kfac.py
  include/lbann/comm.hpp
  include/lbann/execution_algorithms/kfac.hpp
  include/lbann/execution_algorithms/kfac/kfac_block.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_bn.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_fc_conv.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_gru.hpp
  include/lbann/execution_algorithms/kfac/kfac_util.hpp
  include/lbann/utils/lbann_library.hpp
  src/comm.cpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/kfac_block.cpp
  src/execution_algorithms/kfac/kfac_block_fc_conv.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
  src/execution_algorithms/kfac/kfac_util.cpp
  src/proto/training_algorithm.proto
  src/trainers/trainer.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested
