Repository LLNL/lbann, pull requests merged in 2021-06, with the labels that each got.

#1634 Add the K-FAC callback
  applications/optimizers/kfac/README.md
  applications/optimizers/kfac/kfac.py
  applications/vision/data/mnist/__init__.py
  bamboo/unit_tests/test_unit_callback_kfac.py
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/kfac/CMakeLists.txt
  include/lbann/callbacks/kfac/kfac.hpp
  include/lbann/callbacks/kfac/kfac_block.hpp
  include/lbann/callbacks/kfac/kfac_block_bn.hpp
  include/lbann/callbacks/kfac/kfac_block_fc_conv.hpp
  include/lbann/callbacks/kfac/kfac_util.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/base_convolution.hpp
  include/lbann/utils/any.hpp
  include/lbann/utils/im2col.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/kfac/CMakeLists.txt
  src/callbacks/kfac/kfac.cpp
  src/callbacks/kfac/kfac_block.cpp
  src/callbacks/kfac/kfac_block_bn.cpp
  src/callbacks/kfac/kfac_block_bn.cu
  src/callbacks/kfac/kfac_block_fc_conv.cpp
  src/callbacks/kfac/kfac_block_fc_conv.cu
  src/callbacks/kfac/kfac_util.cpp
  src/callbacks/kfac/kfac_util.cu
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
  src/utils/CMakeLists.txt
  src/utils/im2col.cpp
  src/utils/im2col.cu
Labels: enhancement, review requested

#1877 Change CUDA arch handling in LBANN
  CMakeLists.txt
Labels: bug, review requested

#1864 Edge Conditioned Graph Neural Networks
  applications/graph/GNN/NNConvModel.py
  applications/graph/GNN/OGB_LBANN_Trainer.py
  applications/graph/GNN/data/LSC_PPQM4M/LSC_100K.py
  applications/graph/GNN/data/LSC_PPQM4M/LSC_FULL_DATA.py
  applications/graph/GNN/data/LSC_PPQM4M/__init__.py
  applications/graph/GNN/data/Synthetic/Synthetic_Dense_Edge.py
  applications/graph/GNN/data/Synthetic/Synthetic_Sparse_Edge.py
  applications/graph/GNN/data/Synthetic/__init__.py
  applications/graph/GNN/test/conftest.py
  applications/graph/GNN/test/test_integration_NNConv.py
  python/lbann/modules/__init__.py
  python/lbann/modules/base.py
  python/lbann/modules/graph/__init__.py
  python/lbann/modules/graph/dense/DenseNNConv.py
  python/lbann/modules/graph/dense/__init__.py
  python/lbann/modules/graph/sparse/NNConv.py
  python/lbann/modules/graph/sparse/__init__.py
Labels: application, review requested

#1878 Fix typo in LTFB training algorithm with sendrecv communication
  python/lbann/core/training_algorithm.py
Labels: bug, python, review requested

#1880 Cleanup warnings and Aluminum-related errors in the K-FAC infrastructure
  include/lbann/callbacks/kfac/kfac_block_bn.hpp
  include/lbann/callbacks/kfac/kfac_block_fc_conv.hpp
  include/lbann/callbacks/kfac/kfac_util.hpp
  src/callbacks/kfac/kfac.cpp
  src/callbacks/kfac/kfac_util.cpp
Labels: bug, review requested

#1882 Fix incorrect args in example script in docs
  docs/running_lbann.rst
  model_zoo/data_readers/data_reader_mnist.prototext
Labels: bug, documentation, review requested

#1747 smiles reader update, with sample lists
  CMakeLists.txt
  ReleaseNotes.txt
  applications/ATOM/smiles_data_reader.prototext
  applications/ATOM/train_atom_wae.py
  applications/ATOM/utils/CMakeLists.txt
  applications/ATOM/utils/compute_vocab.cpp
  applications/ATOM/utils/compute_vocab_parallel.cpp
  applications/ATOM/utils/construct_SMILES_offset_file.cpp
  bamboo/common_python/data/atom/data_reader_mpro.prototext
  bamboo/compiler_tests/build_script.sh
  bamboo/integration_tests/experiments/.gitignore
  bamboo/integration_tests/test_integration_atom_wae.py
  cmake/modules/FindZSTR.cmake
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_smiles.hpp
  include/lbann/data_readers/sample_list.hpp
  include/lbann/data_readers/sample_list_ifstream.hpp
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/data_readers/sample_list_open_files.hpp
  include/lbann/data_readers/sample_list_open_files_impl.hpp
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/file_utils.hpp
  include/lbann/utils/lbann_library.hpp
  include/lbann/utils/vectorwrapbuf.hpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_smiles.cpp
  src/data_readers/unit_test/CMakeLists.txt
  src/data_readers/unit_test/data_reader_smiles_fetch_datum_test.cpp
  src/data_readers/unit_test/data_reader_smiles_sample_list_test.cpp
  src/data_readers/unit_test/data_reader_smiles_test.cpp
  src/data_readers/unit_test/test_data/A_smiles_reader.smi
  src/data_readers/unit_test/test_data/B_smiles_reader.smi
  src/data_readers/unit_test/test_data/C_smiles_reader.smi
  src/data_readers/unit_test/test_data/D_smiles_reader.smi
  src/data_readers/unit_test/test_data/smiles_reader.prototext
  src/data_readers/unit_test/test_data/smiles_reader_sample_list.txt
  src/data_readers/unit_test/test_data/vocab.txt
  src/proto/proto_common.cpp
  src/utils/file_utils.cpp
  src/utils/lbann_library.cpp
  unit_test/CMakeLists.txt
Labels: application, enhancement, refactor, review requested

#1883 Bug fixes for MIOpen convolution algorithms
  include/lbann/utils/dnn_enums.hpp
  include/lbann/utils/dnn_lib/miopen.hpp
  scripts/customize_build_env.sh
Labels: bug, review requested, spack

#1887 Fix a bug in the early stopping callback
  src/execution_algorithms/sgd_training_algorithm.cpp
Labels: bug, review requested

#1888 Fix a C++17 compilation issue with SMILES data reader
  src/data_readers/data_reader_smiles.cpp
Labels: bug, build, review requested

#1889 Fix some initializers
  include/lbann/data_readers/sample_list_open_files_impl.hpp
Labels: bug

#1876 Optimize data transfer in input layers
  ReleaseNotes.txt
  include/lbann/data_coordinator/io_data_buffer.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/tensor.hpp
  include/lbann/utils/tensor_impl.hpp
  src/base.cpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/layers/data_type_layer.cpp
  src/utils/lbann_library.cpp
Labels: enhancement

#1772 LBANN-core
  CMakeLists.txt
  ReleaseNotes.txt
  applications/ATOM/utils/CMakeLists.txt
  applications/CANDLE/pilot2/tools/CMakeLists.txt
  cmake/configure_files/LBANNConfig.cmake.in
  core-driver/CMakeLists.txt
  core-driver/main.cpp
  include/lbann/base.hpp
  include/lbann/data_coordinator/data_coordinator.hpp
  include/lbann/execution_algorithms/batch_functional_inference_algorithm.hpp
  include/lbann/layers/io/input_layer.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/lbann_library.hpp
  model_zoo/jag_utils/CMakeLists.txt
  src/base.cpp
  src/execution_algorithms/CMakeLists.txt
  src/execution_algorithms/batch_functional_inference_algorithm.cpp
  src/execution_algorithms/unit_test/CMakeLists.txt
  src/execution_algorithms/unit_test/inference_algorithm_test.cpp
  src/layers/io/input_layer.cpp
  src/utils/lbann_library.cpp
  src/utils/threads/thread_pool.cpp
Labels: review requested

#1739 Add complex numbers support
  include/lbann/layers/data_type_distconv_adapter.hpp
  include/lbann/layers/data_type_layer.hpp
  src/layers/cereal_registration/data_type_layer.cpp
  src/layers/data_type_distconv_adapter.cpp
  src/layers/data_type_layer.cpp
Labels: enhancement, review requested

#1886 Bug fix for K-FAC callback with ROCm
  include/lbann/utils/im2col.hpp
  src/callbacks/kfac/kfac_block_bn.cu
  src/callbacks/kfac/kfac_block_fc_conv.cpp
  src/callbacks/kfac/kfac_block_fc_conv.cu
  src/callbacks/kfac/kfac_util.cu
  src/utils/CMakeLists.txt
  src/utils/im2col.cu
Labels: bug

#1845 Add GRU layer support to the K-FAC callback
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_callback_kfac.py
  include/lbann/callbacks/kfac/CMakeLists.txt
  include/lbann/callbacks/kfac/kfac.hpp
  include/lbann/callbacks/kfac/kfac_block.hpp
  include/lbann/callbacks/kfac/kfac_block_gru.hpp
  include/lbann/callbacks/kfac/kfac_util.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/gru.hpp
  src/callbacks/kfac/CMakeLists.txt
  src/callbacks/kfac/kfac.cpp
  src/callbacks/kfac/kfac_block_bn.cu
  src/callbacks/kfac/kfac_block_fc_conv.cpp
  src/callbacks/kfac/kfac_block_fc_conv.cu
  src/callbacks/kfac/kfac_block_gru.cpp
  src/callbacks/kfac/kfac_block_gru.cu
  src/callbacks/kfac/kfac_util.cpp
  src/callbacks/kfac/kfac_util.cu
  src/proto/callbacks.proto
  src/utils/im2col.cu
Labels: review requested

#1897 Refactor K-FAC callback as training algorithm
  applications/optimizers/kfac/kfac.py
  bamboo/unit_tests/test_unit_algo_kfac.py
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/kfac/kfac.hpp
  include/lbann/execution_algorithms/CMakeLists.txt
  include/lbann/execution_algorithms/kfac.hpp
  include/lbann/execution_algorithms/kfac/CMakeLists.txt
  include/lbann/execution_algorithms/kfac/execution_context.hpp
  include/lbann/execution_algorithms/kfac/kfac_block.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_bn.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_fc_conv.hpp
  include/lbann/execution_algorithms/kfac/kfac_block_gru.hpp
  include/lbann/execution_algorithms/kfac/kfac_util.hpp
  include/lbann/layers/layer.hpp
  python/lbann/core/training_algorithm.py
  src/callbacks/CMakeLists.txt
  src/callbacks/kfac/kfac.cpp
  src/execution_algorithms/CMakeLists.txt
  src/execution_algorithms/factory.cpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/kfac/CMakeLists.txt
  src/execution_algorithms/kfac/execution_context.cpp
  src/execution_algorithms/kfac/kfac_block.cpp
  src/execution_algorithms/kfac/kfac_block_bn.cpp
  src/execution_algorithms/kfac/kfac_block_bn.cu
  src/execution_algorithms/kfac/kfac_block_fc_conv.cpp
  src/execution_algorithms/kfac/kfac_block_fc_conv.cu
  src/execution_algorithms/kfac/kfac_block_gru.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cu
  src/execution_algorithms/kfac/kfac_util.cpp
  src/execution_algorithms/kfac/kfac_util.cu
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
  src/proto/training_algorithm.proto
Labels: refactor, review requested

#1900 Bug fixes for ROCm builds
  include/lbann/utils/dnn_lib/cudnn.hpp
  include/lbann/utils/dnn_lib/miopen.hpp
  include/lbann/utils/gpu/cuda.hpp
  include/lbann/utils/gpu/rocm.hpp
  src/callbacks/check_nan.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cpp
  src/execution_algorithms/kfac/kfac_block_gru.cu
  src/utils/cuda.cu
  src/utils/rocm.cpp
Labels: bug, review requested

#1784 Added support for the compiler tests to use the spack build script.
  bamboo/compiler_tests/test_compiler.py
  bamboo/run.sh
  include/lbann/utils/dnn_lib/miopen.hpp
  scripts/customize_build_env.sh
Labels: review requested
