Repository LLNL/lbann, pull requests merged in 2021-12, with the labels that each got.

#2016 Layer documentation
  bamboo/unit_tests/test_unit_algo_kfac.py
  include/lbann/layers/activations/elu.hpp
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/activations/leaky_relu.hpp
  include/lbann/layers/activations/log_softmax.hpp
  include/lbann/layers/activations/relu.hpp
  include/lbann/layers/io/input_layer.hpp
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/learning/gru.hpp
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/l1_norm.hpp
  include/lbann/layers/loss/l2_norm2.hpp
  include/lbann/layers/loss/mean_absolute_error.hpp
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/layers/loss/top_k_categorical_accuracy.hpp
  include/lbann/layers/math/matmul.hpp
  include/lbann/layers/misc/argmax.hpp
  include/lbann/layers/misc/argmin.hpp
  include/lbann/layers/misc/dist_embedding.hpp
  include/lbann/layers/misc/one_hot.hpp
  include/lbann/layers/operator_layer.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/regularizers/instance_norm.hpp
  include/lbann/layers/regularizers/layer_norm.hpp
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/bernoulli.hpp
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/dummy.hpp
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/layers/transform/gather.hpp
  include/lbann/layers/transform/gaussian.hpp
  include/lbann/layers/transform/hadamard.hpp
  include/lbann/layers/transform/in_top_k.hpp
  include/lbann/layers/transform/reduction.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/layers/transform/scatter.hpp
  include/lbann/layers/transform/slice.hpp
  include/lbann/layers/transform/sort.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/layers/transform/stop_gradient.hpp
  include/lbann/layers/transform/sum.hpp
  include/lbann/layers/transform/tessellate.hpp
  include/lbann/layers/transform/uniform.hpp
  include/lbann/layers/transform/weighted_sum.hpp
  include/lbann/layers/transform/weights.hpp
  src/proto/layers.proto
Labels: review requested, documentation

#2014 Fix tensor dimension issues
  include/lbann/layers/operator_layer_impl.hpp
  include/lbann/utils/dim_helpers.hpp
  include/lbann/utils/tensor.hpp
  src/utils/unit_test/dim_helpers_test.cpp
Labels: bug, review requested

#2018 Add dimension checks to the binary operators
  src/layers/regularizers/layer_norm.cu
  src/operators/math/binary.cpp
  src/operators/math/binary.cu
Labels: bug, review requested

#2010 Bugfix for K-FAC with convolution layers
  bamboo/unit_tests/test_unit_algo_kfac_conv.py
  src/execution_algorithms/kfac/kfac_block_fc_conv.cpp
Labels: bug, review requested

#2021 Remove outdated APIs from the thread_topology interface
  include/lbann/utils/threads/thread_topology.hpp
  src/utils/threads/thread_topology.cpp
Labels: bug, review requested, build

#2020 Cleanup some Doxygen warnings/formatting issues.
  docs/SourceTreeDoxyfile
  include/lbann/base.hpp
  include/lbann/callbacks/dump_weights.hpp
  include/lbann/callbacks/load_model.hpp
  include/lbann/callbacks/ltfb.hpp
  include/lbann/callbacks/save_topk_models.hpp
  include/lbann/callbacks/summarize_images.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_HDF5.hpp
  include/lbann/data_readers/data_reader_synthetic.hpp
  include/lbann/data_store/data_store_conduit.hpp
  include/lbann/execution_algorithms/ltfb.hpp
  include/lbann/execution_algorithms/ltfb/random_pairwise_exchange.hpp
  include/lbann/execution_algorithms/ltfb/regularized_evolution.hpp
  include/lbann/execution_algorithms/ltfb/truncation_selection_exchange.hpp
  include/lbann/execution_algorithms/training_algorithm.hpp
  include/lbann/layers/layer.hpp
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  include/lbann/layers/learning/embedding.hpp
  include/lbann/layers/learning/gru.hpp
  include/lbann/layers/operator_layer_impl.hpp
  include/lbann/layers/regularizers/batch_normalization.hpp
  include/lbann/operators/builder_macros.hpp
  include/lbann/optimizers/hypergradient_adam.hpp
  include/lbann/optimizers/optimizer.hpp
  include/lbann/proto/operator_factory_impl.hpp
  include/lbann/trainers/trainer.hpp
  include/lbann/utils/image.hpp
  include/lbann/utils/make_abstract.hpp
  include/lbann/utils/random_number_generators.hpp
  include/lbann/utils/serialization/serialize_matrices.hpp
  include/lbann/weights/data_type_weights.hpp
  include/lbann/weights/weights.hpp
  include/lbann/weights/weights_proxy.hpp
  src/execution_algorithms/ltfb/random_pairwise_exchange.cpp
  src/execution_algorithms/ltfb/regularized_evolution.cpp
  src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
Labels: review requested, documentation

#2022 Make sure GPU grid dims are valid in slice/concat layers
  src/layers/transform/concatenate.cu
  src/layers/transform/slice.cu
Labels: bug, review requested

#2023 Fix changes that should not have been in #2020
  include/lbann/layers/operator_layer_impl.hpp
  include/lbann/proto/operator_factory_impl.hpp
Labels: bug, review requested
