Repository LLNL/lbann, pull requests merged in 2021-01, with the labels that each got.

#1724 Feature add tournament execution mode
  ReleaseNotes.txt
  applications/ATOM/eval_atom_wae.py
  applications/ATOM/train_atom_vae.py
  applications/ATOM/train_atom_wae.py
  applications/physics/data/jag_conduit_reader.prototext
  bamboo/unit_tests/test_unit_callback_ltfb.py
  bamboo/unit_tests/test_unit_callback_ltfb_data.py
  include/lbann/base.hpp
  include/lbann/data_coordinator/data_coordinator.hpp
  include/lbann/data_readers/compound_data_reader.hpp
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_jag_conduit.hpp
  include/lbann/io/persist.hpp
  include/lbann/proto/proto_common.hpp
  model_zoo/tests/data_reader_tests/jag_single_layer_ae.prototext
  model_zoo/tests/model_jag_single_layer_ae.prototext
  src/base.cpp
  src/callbacks/ltfb.cpp
  src/callbacks/monitor_io.cpp
  src/callbacks/print_statistics.cpp
  src/callbacks/timer.cpp
  src/data_coordinator/data_coordinator.cpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/models/model.cpp
  src/proto/proto_common.cpp
  src/proto/reader.proto
  src/proto/trainer.proto
  src/training_algorithms/sgd_training_algorithm.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1728 Perform LTFB model exchanges with temporary models
  bamboo/unit_tests/test_unit_callback_ltfb.py
  include/lbann/callbacks/ltfb.hpp
  include/lbann/models/model.hpp
  src/callbacks/ltfb.cpp
  src/models/model.cpp
Labels: refactor, review requested

#1729 Fix issues of Distconv-enabled 3D CNN models
  applications/physics/cosmology/cosmoflow/cosmoflow.py
  applications/segmentation/unet3d/unet3d.py
Labels: bug

#1740 Build OpenCV with imgcodecs module
  spack_environments/llnl_lc/externals-linux-ppc64le.sh
  spack_environments/llnl_lc/externals-linux-x86_64.sh
  spack_environments/nersc/externals-cray-cnl7-skylake_avx512.sh
  spack_environments/olcf/externals-linux-rhel7-power9le.sh
  spack_environments/osx/externals-darwin-x86_64.sh
Labels: bug, build, review requested

#1748 Skeleton for graph motif app
  applications/graph/motif/.gitignore
  applications/graph/motif/__init__.py
  applications/graph/motif/data/__init__.py
  applications/graph/motif/data/dataset.py
  applications/graph/motif/main.py
  applications/graph/motif/model/__init__.py
  applications/graph/motif/model/autoencoder.py
Labels: application

#1746 Fix bug in cuDNN filter desc wrapper copy constructor
  bamboo/unit_tests/test_unit_callback_ltfb.py
  src/utils/cudnn.cpp
Labels: bug, review requested

#1733 Move model checkpointing from end of training step to beginning
  ReleaseNotes.txt
  include/lbann/callbacks/checkpoint.hpp
  include/lbann/callbacks/dump_weights.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/enum_iterator.hpp
  include/lbann/utils/visitor_hooks.hpp
  src/callbacks/checkpoint.cpp
  src/callbacks/dump_weights.cpp
  src/training_algorithms/sgd_training_algorithm.cpp
  src/utils/CMakeLists.txt
  src/utils/lbann_library.cpp
  src/utils/visitor_hooks.cpp
Labels: review requested

#1750 Remove LBANN-written python module in favor of CMake module
  CMakeLists.txt
  cmake/modules/FindPython.cmake
Labels: build, enhancement, review requested

#1745 More LTFB refactoring
  ReleaseNotes.txt
  bamboo/unit_tests/test_unit_callback_ltfb.py
  include/lbann/callbacks/ltfb.hpp
  include/lbann/models/model.hpp
  src/callbacks/ltfb.cpp
Labels: enhancement, refactor, review requested

#1756 Add pkg-config search for FFTW
  cmake/modules/FindFFTW.cmake
Labels: build, enhancement, review requested

#1752 Refactor CNPY Optional Dependency
  ReleaseNotes.txt
  include/lbann/data_readers/CMakeLists.txt
  src/data_readers/CMakeLists.txt
  src/proto/proto_common.cpp
Labels: refactor, review requested

#1751 Refactor OpenCV Optional Dependency
  CMakeLists.txt
  ReleaseNotes.txt
  include/lbann/data_readers/CMakeLists.txt
  include/lbann/lbann.hpp
  include/lbann/transforms/CMakeLists.txt
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/vision.hpp
  src/callbacks/mixup.cpp
  src/callbacks/summarize_images.cpp
  src/data_readers/CMakeLists.txt
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/proto/factories/transform_factory.cpp
  src/proto/init_image_data_readers.cpp
  src/proto/proto_common.cpp
  src/transforms/CMakeLists.txt
  src/transforms/repack_HWC_to_CHW_layout.cpp
  src/utils/CMakeLists.txt
  src/utils/summary.cpp
  src/utils/unit_test/CMakeLists.txt
Labels: refactor, review requested

#1759 Fix how HWLOC external is specified
  spack_environments/llnl_lc/externals-linux-ppc64le.sh
  spack_environments/llnl_lc/externals-linux-x86_64.sh
Labels: bug

#1749 Script for constructing sample lists for the smiles data_reader
  applications/ATOM/utils/build_sample_lists.py
  applications/ATOM/utils/build_sample_lists_example_input.txt
Labels: application, review requested

#1760 Fixed preprocessor guards for building without CNPY library for some
  include/lbann/lbann.hpp
  include/lbann/utils/CMakeLists.txt
  src/utils/CMakeLists.txt
Labels: bug

#1758 Perform extra synchronization in LTFB with checkpoint communication
  src/callbacks/ltfb.cpp
Labels: bug, review requested

#1761 Debug node2vec to use double data type
  applications/graph/node2vec/data/offline_walks.py
  applications/graph/node2vec/main.py
  src/layers/activations/log_softmax.cu
  src/layers/activations/softmax.cu
Labels: application, bug

#1762 Implement CommunityGAN model with synthetic data
  applications/graph/communityGAN/.gitignore
  applications/graph/communityGAN/__init__.py
  applications/graph/communityGAN/data/__init__.py
  applications/graph/communityGAN/data/dataset.py
  applications/graph/communityGAN/main.py
  applications/graph/communityGAN/model/__init__.py
  applications/graph/communityGAN/model/discriminator.py
  applications/graph/communityGAN/model/gan.py
  applications/graph/communityGAN/model/generator.py
  applications/graph/communityGAN/util/__init__.py
Labels: application

#1738 Support DiHydrogen's mean squared error layers
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/utils/distconv.hpp
  src/layers/io/input_layer.cpp
Labels: enhancement

#1753 Update Python frontend to correctly specify procs_per_trainer
  python/lbann/contrib/launcher.py
  python/lbann/core/trainer.py
  python/lbann/launcher/__init__.py
Labels: bug, python, review requested

#1754 Add option to specify file format of "dump weights" callback
  applications/graph/node2vec/main.py
  include/lbann/callbacks/dump_weights.hpp
  src/callbacks/dump_weights.cpp
  src/proto/callbacks.proto
Labels: enhancement, review requested

#1734 Dump model graph callback
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/dump_model_graph.hpp
  src/callbacks/CMakeLists.txt
  src/callbacks/dump_model_graph.cpp
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
Labels: enhancement
