Repository LLNL/lbann, pull requests merged in 2021-03, with the labels that each got.

#1800 Specify correct OpenBLAS Spack variant when building on Lassen
  scripts/customize_build_env.sh
Labels: bug, build, review requested

#1804 Run clang-format on the lbann_comm implementation
  include/lbann/comm.hpp
  include/lbann/comm_impl.hpp
  src/comm.cpp
Labels: review requested

#1794 Debugging build system on Surface
  scripts/customize_build_env.sh
Labels: bug, build, review requested

#1799 Add OpenMPI launcher to Python front-end
  python/lbann/launcher/__init__.py
  python/lbann/launcher/openmpi.py
Labels: python, review requested

#1805 Fix error when not building with FP16 support
  src/optimizers/unit_test/optimizer_common.hpp
Labels: bug, review requested

#1802 Rename Training Algorithms
  include/lbann/CMakeLists.txt
  include/lbann/callbacks/checkpoint.hpp
  include/lbann/execution_algorithms/CMakeLists.txt
  include/lbann/execution_algorithms/sgd_training_algorithm.hpp
  include/lbann/execution_algorithms/training_algorithm.hpp
  include/lbann/lbann.hpp
  src/CMakeLists.txt
  src/callbacks/load_model.cpp
  src/callbacks/save_model.cpp
  src/execution_algorithms/CMakeLists.txt
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/execution_algorithms/training_algorithm.cpp
  src/execution_contexts/execution_context.cpp
  src/trainers/trainer.cpp
Labels: refactor

#1812 Fix 403 error when downloading MNIST
  applications/vision/data/mnist/__init__.py
Labels: application, bug, review requested

#1815 Fix bug in MIOpen dropout
  include/lbann/utils/dnn_lib/miopen/dropout.hpp
Labels: bug

#1801 Batch-wise reduce-sum layer
  bamboo/unit_tests/test_unit_layer_batchwise_reduce_sum.py
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/batchwise_reduce_sum.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/batchwise_reduce_sum.cpp
  src/layers/transform/batchwise_reduce_sum_builder.cpp
  src/layers/transform/cereal_registration/CMakeLists.txt
  src/layers/transform/cereal_registration/batchwise_reduce_sum.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1819 Handle weights with dims >2.1B
  include/lbann/layers/learning/channelwise_scale_bias.hpp
  include/lbann/layers/learning/embedding.hpp
  include/lbann/layers/learning/entrywise_scale_bias.hpp
  include/lbann/layers/misc/dist_embedding.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/transform/weights.hpp
  include/lbann/weights/data_type_weights.hpp
  include/lbann/weights/weights.hpp
  src/layers/learning/base_convolution.cpp
  src/layers/learning/channelwise_fully_connected.cpp
  src/layers/learning/fully_connected.cpp
  src/layers/learning/gru.cpp
  src/weights/data_type_weights.cpp
  src/weights/unit_test/weights_proxy_test.cpp
  src/weights/unit_test/weights_test.cpp
  src/weights/weights.cpp
Labels: bug, refactor, review requested

#1820 Make CommunityGAN generator probabilistic
  applications/graph/communityGAN/model/discriminator.py
  applications/graph/communityGAN/model/gan.py
  applications/graph/communityGAN/model/generator.py
Labels: application

#1826 Use size_t for weights positions
  include/lbann/weights/data_type_weights.hpp
  src/weights/data_type_weights.cpp
Labels: bug, review requested

#1824 Updated build environment
  docs/building_lbann.rst
  scripts/build_lbann.sh
Labels: bug

#1809 Added support for the Fugaku PJM launcher.
  python/lbann/launcher/__init__.py
  python/lbann/launcher/pjm.py
Labels: enhancement

#1797 Separate GRU layers in ATOM WAE decoder
  applications/ATOM/models/wae.py
Labels: application

#1830 Move data store exchange to primary thread
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/data_readers/data_reader.cpp
  src/data_store/data_store_conduit.cpp
Labels: enhancement

#1834 Configure trainer grid dims with environment variable
  include/lbann/comm.hpp
  src/comm.cpp
Labels: enhancement, review requested

#1836 Add command-line arg to set trainer grid height
  include/lbann/comm.hpp
  include/lbann/utils/lbann_library.hpp
  src/comm.cpp
  src/utils/lbann_library.cpp
Labels: enhancement, review requested

#1833 Fixed bug with MIOpen convolution algorithm selection
  src/utils/miopen.cpp
  src/utils/unit_test/dnn_lib_test.cpp
Labels: bug

#1838 Fix Clang compile error in row-wise weights norms layer
  src/layers/misc/rowwise_weights_norms.cpp
Labels: bug, review requested

#1832 Parallelize computation of Gaussian random numbers
  include/lbann/utils/random.hpp
  src/utils/random.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/random_fill_test.cpp
Labels: enhancement, review requested

#1842 Fixed typo in CMake building of sequential catch2 tests.
  src/proto/unit_test/CMakeLists.txt
Labels: bug

#1803 Add Batch Inference Algorithm
  include/lbann/base.hpp
  include/lbann/execution_algorithms/CMakeLists.txt
  include/lbann/execution_algorithms/batch_functional_inference_algorithm.hpp
  src/base.cpp
  src/execution_algorithms/CMakeLists.txt
  src/execution_algorithms/batch_functional_inference_algorithm.cpp
Labels: enhancement, refactor, review requested

#1835 Bug fix for ROCm spack install
  scripts/customize_build_env.sh
Labels: bug

#1843 Avoid GPU embedding and tessellate layers in ATOM WAE test
  bamboo/integration_tests/test_integration_atom_wae.py
Labels: CI
