Repository LLNL/lbann, pull requests merged in 2021-02, with the labels that each got.

#1742 Remove the superbuild ecosystem
  docs/CMakeLists.txt
  docs/build_with_superbuild.rst
  docs/building_lbann.rst
  scripts/build_lbann_lc.sh
  superbuild/CMakeLists.txt
  superbuild/README.md
  superbuild/aluminum/CMakeLists.txt
  superbuild/catch2/CMakeLists.txt
  superbuild/cereal/CMakeLists.txt
  superbuild/clara/CMakeLists.txt
  superbuild/cmake/modules/LBANNSuperBuildCreateCMakeArguments.cmake
  superbuild/cnpy/CMakeLists.txt
  superbuild/conduit/CMakeLists.txt
  superbuild/cub/CMakeLists.txt
  superbuild/cub/CUBCMakeLists.txt
  superbuild/dihydrogen/CMakeLists.txt
  superbuild/hdf5/CMakeLists.txt
  superbuild/hydrogen/CMakeLists.txt
  superbuild/jpeg-turbo/CMakeLists.txt
  superbuild/jpeg-turbo/jpeg-turbo_configure.sh.in
  superbuild/lbann/CMakeLists.txt
  superbuild/openblas/CMakeLists.txt
  superbuild/opencv/AddOpenCVOptions.cmake
  superbuild/opencv/CMakeLists.txt
  superbuild/protobuf/CMakeLists.txt
  superbuild/protobuf/protobuf_configure.sh.in
Labels: enhancement, review requested

#1768 Fix a bug in the constant layer Cereal registration
  src/layers/transform/cereal_registration/constant.cpp
Labels: bug, review requested

#1769 Clean up handling of GPU errors
  include/lbann/utils/dnn_lib/cudnn.hpp
  include/lbann/utils/dnn_lib/miopen.hpp
  include/lbann/utils/gpu/cuda.hpp
  include/lbann/utils/gpu/rocm.hpp
Labels: bug, review requested

#1771 Properly register the matmul layer
  include/lbann/layers/math/matmul.hpp
  src/layers/math/cereal_registration/CMakeLists.txt
  src/layers/math/cereal_registration/matmul.cpp
Labels: bug, review requested

#1779 Add support for ingesting multiple files in offline node2vec
  applications/graph/node2vec/data/offline_walks.py
Labels: application

#1780 Force model to setup after a copy constructor or copy assignment
  src/callbacks/ltfb.cpp
  src/models/model.cpp
Labels: bug, review requested

#1781 fixed bug causing segfault during cudnnHandle destructor
  unit_test/SequentialCatchMain.cpp
Labels: bug, review requested

#1773 Make OpenCV optional when building Catch2 tests
  CMakeLists.txt
Labels: build, review requested

#1766 Scatter and gather layers
  bamboo/unit_tests/test_unit_layer_gather.py
  bamboo/unit_tests/test_unit_layer_scatter.py
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/gather.hpp
  include/lbann/layers/transform/scatter.hpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/cereal_registration/CMakeLists.txt
  src/layers/transform/cereal_registration/gather.cpp
  src/layers/transform/cereal_registration/scatter.cpp
  src/layers/transform/gather.cpp
  src/layers/transform/gather.cu
  src/layers/transform/gather_builder.cpp
  src/layers/transform/scatter.cpp
  src/layers/transform/scatter.cu
  src/layers/transform/scatter_builder.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, review requested

#1767 Contrib module for radial profile
  python/lbann/contrib/modules/__init__.py
  python/lbann/contrib/modules/objective_functions.py
  python/lbann/contrib/modules/radial_profile.py
Labels: application, review requested

#1785 Use uniform distribution in GRU layer unit test
  bamboo/unit_tests/test_unit_layer_gru.py
Labels: CI, review requested

#1787 Add contrib module for fftshift
  python/lbann/contrib/modules/fftshift.py
Labels: application, review requested

#1788 Refactor CommunityGAN app
  applications/graph/communityGAN/data/dataset.py
  applications/graph/communityGAN/default.config
  applications/graph/communityGAN/driver/__init__.py
  applications/graph/communityGAN/driver/default.config
  applications/graph/communityGAN/driver/driver.py
  applications/graph/communityGAN/dump_motifs.py
  applications/graph/communityGAN/main.py
  applications/graph/communityGAN/model/__init__.py
Labels: application, refactor, review requested

#1789 Tweaking CommunityGAN hyperparameters
  applications/graph/communityGAN/default.config
Labels: application

#1790 Tweak CommunityGAN learning rate
  applications/graph/communityGAN/default.config
  applications/graph/communityGAN/main.py
Labels: application

#1606 Add vae mnist fe
  applications/autoencoders/data/__init__.py
  applications/autoencoders/data/mnist/__init__.py
  applications/autoencoders/data/mnist/data_reader_mnist.prototext
  applications/autoencoders/data/mnist/data_reader_mnist_numpy_npz_int16.prototext
  applications/autoencoders/mnist/vae_mnist.prototext
  applications/autoencoders/mnist/vae_mnist.py
  model_zoo/models/autoencoder_candle_pilot1/data_readers/data_reader_candle_pilot1.prototext
  model_zoo/models/autoencoder_candle_pilot1/model_autoencoder_chem_ecfp.py
  model_zoo/models/autoencoder_candle_pilot1/model_dnn_chem_ecfp.py
Labels: enhancement

#1731 Support nvprof in the Python frontend
  python/lbann/contrib/launcher.py
  python/lbann/launcher/__init__.py
  python/lbann/util/__init__.py
Labels: enhancement

#956 Set up Gitlab CI
  .gitlab-ci.yml
  bamboo/compiler_tests/script_compiler.sh
  bamboo/integration_tests/script_integration.sh
  bamboo/unit_tests/scipt_unit.sh
Labels: CI, on_hold

#1726 Adding Channelwise FC module to Python Frontend
  python/lbann/modules/base.py
Labels: python, review requested

#1763 oneDNN support on CPU
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/layers/activations/softmax.hpp
  include/lbann/utils/dnn_lib/onednn.hpp
  include/lbann/utils/dnn_lib/onednn/softmax.hpp
  include/lbann/utils/dnn_lib/openmp.hpp
  include/lbann/utils/dnn_lib/openmp/softmax.hpp
  include/lbann/utils/dnn_lib/softmax.hpp
  include/lbann/utils/sync_info_helpers.hpp
  src/callbacks/dump_model_graph.cpp
  src/layers/activations/softmax.cpp
  src/layers/activations/softmax.cu
  src/utils/CMakeLists.txt
  src/utils/onednn.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/onednn_infrastructure_test.cpp
Labels: enhancement, review requested

#1630 split the embedded python support from the python frontend
  CMakeLists.txt
  cmake/configure_files/LBANNConfig.cmake.in
  include/lbann/data_readers/data_reader_python.hpp
  include/lbann/utils/python.hpp
  spack_environments/cmake_lbann_zen.sh
  src/base.cpp
  src/data_readers/data_reader_python.cpp
  src/proto/CMakeLists.txt
  src/proto/proto_common.cpp
  src/utils/python.cpp
  src/utils/unit_test/python_test.cpp
Labels: enhancement, python, review requested

#1795 Only instantiate GRU serialization when supported; fix other errors
  .travis.yml
  cmake/configure_files/lbann_config.hpp.in
  src/layers/learning/cereal_registration/gru.cpp
Labels: bug, review requested

#1792 Updated the build script for ROCm on Corona
  CMakeLists.txt
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
Labels: enhancement

#1796 CPU GRU layer
  bamboo/unit_tests/test_unit_layer_gru.py
  include/lbann/layers/learning/gru.hpp
  src/callbacks/debug.cpp
  src/layers/learning/cereal_registration/gru.cpp
  src/layers/learning/gru.cpp
Labels: enhancement, review requested

#1793 Make XML archive optional
  CMakeLists.txt
  cmake/configure_files/lbann_config.hpp.in
  include/lbann/io/persist_impl.hpp
  include/lbann/macros/common_cereal_registration.hpp
  include/lbann/utils/serialization/cereal_utils.hpp
  include/lbann/utils/serialization/rooted_archive_adaptor.hpp
  include/lbann/utils/serialization/serialize_half.hpp
  src/callbacks/unit_test/print_statistics_test.cpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/data_readers/data_reader.cpp
  src/data_store/data_store_conduit.cpp
  src/execution_contexts/execution_context.cpp
  src/execution_contexts/sgd_execution_context.cpp
  src/layers/activations/unit_test/identity_test.cpp
  src/layers/learning/unit_test/convolution_test.cpp
  src/layers/math/unit_test/clamp_test.cpp
  src/layers/regularizers/unit_test/batch_normalization_test.cpp
  src/metrics/layer_metric.cpp
  src/models/model.cpp
  src/models/unit_test/model_test.cpp
  src/optimizers/unit_test/optimizer_common.hpp
  src/optimizers/unit_test/test_adagrad.cpp
  src/optimizers/unit_test/test_adam.cpp
  src/optimizers/unit_test/test_hypergradient_adam.cpp
  src/optimizers/unit_test/test_rmsprop.cpp
  src/optimizers/unit_test/test_sgd.cpp
  src/trainers/trainer.cpp
  src/utils/serialization.cpp
  src/utils/unit_test/rooted_archive_test.cpp
  src/utils/unit_test/serialize_distmatrix_test.cpp
  src/utils/unit_test/serialize_enum_test.cpp
  src/utils/unit_test/serialize_half_test.cpp
  src/utils/unit_test/serialize_matrix_test.cpp
  src/weights/unit_test/weights_test.cpp
Labels: enhancement, review requested

#1798 Implement ATOM WAE reconstruction loss with gather layer
  applications/ATOM/eval_atom_wae.py
  applications/ATOM/models/vae.py
  applications/ATOM/models/wae.py
  applications/ATOM/train_atom_vae.py
  applications/ATOM/train_atom_wae.py
Labels: application, enhancement, review requested
