Repository LLNL/lbann, pull requests merged in 2021-09, with the labels that each got.

#1958 Quick fix for a warning.
  include/lbann/data_readers/sample_list_impl.hpp
Labels: bug, review requested, build

#1891 Refactor input options to use argument parser class
  bamboo/common_python/tools.py
  bamboo/unit_tests/test_unit_checkpoint_lenet.py
  bamboo/unit_tests/test_unit_datastore_imagenet.py
  bamboo/unit_tests/test_unit_lbann_invocation.py
  bamboo/unit_tests/test_unit_load_weights_lenet.py
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_readers/data_reader_HDF5.hpp
  include/lbann/data_readers/data_reader_sample_list_impl.hpp
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/proto/proto_common.hpp
  include/lbann/utils/argument_parser.hpp
  include/lbann/utils/lbann_library.hpp
  include/lbann/utils/options.hpp
  include/lbann/utils/protobuf_utils.hpp
  model_zoo/jag_utils/build_index.cpp
  model_zoo/jag_utils/build_sample_id_mapping.cpp
  model_zoo/jag_utils/check_for_duplicate_samples.cpp
  model_zoo/jag_utils/check_images.cpp
  model_zoo/jag_utils/compute_hydra_normalization.cpp
  model_zoo/jag_utils/compute_min_max_images.cpp
  model_zoo/jag_utils/compute_per_channel_image_avg_min_max.cpp
  model_zoo/jag_utils/convert.cpp
  model_zoo/jag_utils/convert_npz_to_conduit.cpp
  model_zoo/jag_utils/detect_corruption.cpp
  model_zoo/jag_utils/extract_random_samples.cpp
  model_zoo/jag_utils/generate_corrupt_samples.cpp
  model_zoo/jag_utils/load_balance.cpp
  model_zoo/jag_utils/load_bundle2raw.cpp
  model_zoo/jag_utils/select_samples.cpp
  model_zoo/jag_utils/test_conduit_hdf5.cpp
  model_zoo/jag_utils/test_reading_speed.cpp
  model_zoo/lbann.cpp
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_help.cpp
  model_zoo/lbann_inf.cpp
  model_zoo/tests/conduit_timing_test.cpp
  src/callbacks/print_statistics.cpp
  src/callbacks/timer.cpp
  src/data_coordinator/data_coordinator.cpp
  src/data_readers/data_reader.cpp
  src/data_readers/data_reader_HDF5.cpp
  src/data_readers/data_reader_hdf5_legacy.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_npz_ras_lipid.cpp
  src/data_readers/data_reader_numpy_npz_conduit.cpp
  src/data_readers/data_reader_smiles.cpp
  src/data_readers/unit_test/data_reader_smiles_fetch_datum_test.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
  src/utils/options.cpp
  src/utils/protobuf_utils.cpp
  src/utils/stack_profiler.cpp
  tests/test_shuffled_indices.cpp
  tests/test_stack_tracing/test_sigint_tracing.cpp
  tests/test_stack_tracing/test_sigsev_tracing.cpp
Labels: review requested, refactor

#1960 Bug fix for arg parse refactor
  include/lbann/utils/dnn_lib/cudnn/convolution.hpp
  model_zoo/lbann.cpp
  model_zoo/lbann_help.cpp
  unit_test/MPICatchMain.cpp
  unit_test/SequentialCatchMain.cpp
Labels: bug

#1963 Add a bunch of f(x,C)-type operators
  include/lbann/operators/math/binary_with_constant.hpp
  include/lbann/operators/math/math_builders.hpp
  include/lbann/operators/math/math_builders_impl.hpp
  include/lbann/proto/operator_factory_impl.hpp
  src/operators/math/CMakeLists.txt
  src/operators/math/binary_with_constant.cpp
  src/operators/math/binary_with_constant.cu
  src/operators/math/cereal_registration/CMakeLists.txt
  src/operators/math/cereal_registration/add_constant.cpp
  src/operators/math/cereal_registration/constant_subtract.cpp
  src/operators/math/cereal_registration/equal_constant.cpp
  src/operators/math/cereal_registration/greater_constant.cpp
  src/operators/math/cereal_registration/greater_equal_constant.cpp
  src/operators/math/cereal_registration/less_constant.cpp
  src/operators/math/cereal_registration/less_equal_constant.cpp
  src/operators/math/cereal_registration/max_constant.cpp
  src/operators/math/cereal_registration/min_constant.cpp
  src/operators/math/cereal_registration/not_equal_constant.cpp
  src/operators/math/cereal_registration/scale.cpp
  src/operators/math/cereal_registration/subtract_constant.cpp
  src/operators/math/math_builders.cpp
  src/operators/math/unit_test/CMakeLists.txt
  src/operators/math/unit_test/add_constant_test.cpp
  src/operators/math/unit_test/constant_subtract_test.cpp
  src/operators/math/unit_test/equal_constant_test.cpp
  src/operators/math/unit_test/not_equal_constant_test.cpp
  src/operators/math/unit_test/scale_test.cpp
  src/operators/math/unit_test/subtract_constant_test.cpp
  src/proto/operators.proto
Labels: enhancement, review requested

#1965 Add binary-with-constant layers to the Python Front-End
  ReleaseNotes.txt
  python/lbann/core/operators.py
Labels: bug, review requested, python

#1968 Generate Python layer class for each operator class
  bamboo/unit_tests/test_unit_module_fully_connected.py
  python/lbann/__init__.py
  python/lbann/core/operator_layers.py
Labels: bug, review requested, python

#1971 Fix an erroneous comment
  include/lbann/execution_algorithms/factory.hpp
Labels: review requested, documentation

#1962 Always mix MPI rank within trainer into RNG seeds
  include/lbann/utils/random_number_generators.hpp
  src/utils/lbann_library.cpp
  src/utils/random_number_generators.cpp
Labels: bug, review requested

#1975 Bugfix data reader catch2 tests
  src/data_readers/unit_test/data_reader_synthetic_test_public_api.cpp
  src/models/unit_test/model_test.cpp
Labels: bug

#1974 Fix incorrect sample dims in numpy_npz_conduit_reader
  src/data_readers/data_reader_numpy_npz_conduit.cpp
Labels: bug, review requested

#1970 Optionally use default-allocated GPU memory for long-lived buffers
  include/lbann/utils/options.hpp
  src/layers/data_type_layer.cpp
  src/layers/matrix_builder.hpp
  src/optimizers/adam.cpp
  src/optimizers/sgd.cpp
  src/utils/options.cpp
  src/weights/data_type_weights.cpp
Labels: bug, review requested
