Repository LLNL/lbann, pull requests merged in 2022-02, with the labels that each got.

#2038 Fixed the MPI Catch2 filesystem test for the SMILES data reader.
  include/lbann/data_readers/data_reader.hpp
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
  src/data_readers/data_reader.cpp
  src/data_readers/unit_test/data_reader_HDF5_test.cpp
  src/data_readers/unit_test/data_reader_smiles_fetch_datum_test.cpp
Labels: bug

#2042 Cleanup of the month
  src/execution_algorithms/kfac/kfac_block_fc_conv.cu
  src/execution_algorithms/kfac/kfac_util.cu
  src/layers/loss/categorical_accuracy.cu
  src/layers/regularizers/instance_norm.cu
  src/layers/transform/in_top_k.cu
  src/layers/transform/tessellate.cu
  src/operators/loss/entrywise.cu
  src/operators/math/binary.cu
  src/operators/math/unary.cu
Labels: review requested

#2041 Python function to perform naive hyperparameter sweep
  docs/hyperparameter_tuning.rst
  docs/index.rst
  python/lbann/contrib/hyperparameter.py
  python/lbann/core/model.py
Labels: review requested, python

#2051 Add a missing filesystem tag to a test that expects LC filesystems
  src/data_readers/unit_test/data_reader_HDF5_sample_list_test.cpp
Labels: bug, review requested, CI

#2052 Silence warning message in Catch test for Python wrapper
  src/utils/unit_test/python_test.cpp
Labels: review requested, python, CI

#2054 Bugfix smiles unit test
  src/data_readers/data_reader_smiles.cpp
Labels: bug

#2056 SMILES data reader buffer bug fix
  src/data_readers/data_reader_smiles.cpp
Labels: bug

#2058 Add a block to optionally hang the MPI catch driver.
  unit_test/MPICatchMain.cpp
Labels: review requested

#2060 Cleanup data reader tests memory leaks
  src/data_readers/unit_test/data_reader_HDF5_hrrl_data_test.cpp
  src/data_readers/unit_test/data_reader_HDF5_hrrl_public_api.cpp
  src/data_readers/unit_test/data_reader_HDF5_sample_list_test.cpp
  src/data_readers/unit_test/data_reader_smiles_sample_list_test.cpp
  src/data_readers/unit_test/data_reader_smiles_test.cpp
Labels: bug

#2061 Fix a sporadic segfault in the invocation tests
  src/utils/protobuf_utils.cpp
Labels: bug, review requested, CI

#1992 Improvements to LBANN options and help message
  include/lbann/data_readers/sample_list_impl.hpp
  include/lbann/utils/options.hpp
  model_zoo/jag_utils/select_samples.cpp
  model_zoo/lbann.cpp
  src/data_readers/data_reader_image.cpp
  src/data_readers/data_reader_npz_ras_lipid.cpp
  src/data_store/data_store_conduit.cpp
  src/proto/proto_common.cpp
  src/utils/options.cpp
Labels: review requested, documentation

#2064 Remove unused variable.
  src/proto/proto_common.cpp
Labels: enhancement, review requested, build

#2001 Use tournament set in LTFB with truncation selection exchange
  ci_test/unit_tests/test_unit_algo_ltfb_trunc_selection.py
  src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
Labels: review requested, refactor

#2065 Remove the Cloneable interface from the training algorithms.
  include/lbann/execution_algorithms/kfac.hpp
  include/lbann/execution_algorithms/ltfb.hpp
  include/lbann/execution_algorithms/sgd_training_algorithm.hpp
  include/lbann/execution_algorithms/training_algorithm.hpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/execution_algorithms/unit_test/training_algorithm_factory_test.cpp
Labels: enhancement, review requested

#2055 Update Transformer app with recent API changes
  applications/nlp/transformer/dataset.py
  applications/nlp/transformer/evaluate.py
  applications/nlp/transformer/train.py
Labels: bug, review requested, application

#2068 Update ATOM WAE app driver to use LTFB training algorithm
  applications/ATOM/train_atom_wae.py
Labels: review requested, application

#2066 Add include guard for dist_embedding layer cerealization
  src/layers/misc/cereal_registration/dist_embedding.cpp
Labels: bug, review requested

#2067 Document layers
  docs/conf.py
  docs/index.rst
  docs/layers.rst
  docs/layers/activation_layers.rst
  docs/layers/image_layers.rst
  docs/layers/io_layers.rst
  docs/layers/learning_layers.rst
  docs/layers/loss_layers.rst
  docs/layers/math_layers.rst
  docs/layers/miscellaneous_layers.rst
  docs/layers/operator_layers.rst
  docs/layers/regularization_layers.rst
  docs/layers/transform_layers.rst
Labels: review requested, documentation
