Repository LLNL/lbann, pull requests merged in 2022-06, with the labels that each got.

#2116 Cleanup Convolution and Deconvolution Protobuf messages
  ReleaseNotes.txt
  applications/MOF/MOFae.py
  applications/nas/nasnet/cifar_networks.py
  applications/nas/nasnet/cifar_search.py
  applications/nas/nasnet/data/__init__.py
  applications/optimizers/kfac/kfac.py
  applications/vision/densenet.py
  applications/vision/lenet.py
  applications/vision/summarizing_images/autoencoder_conv_summarize.py
  ci_test/integration_tests/test_integration_nasnet.py
  ci_test/unit_tests/test_unit_algo_kfac.py
  ci_test/unit_tests/test_unit_algo_kfac_conv.py
  ci_test/unit_tests/test_unit_layer_convolution.py
  ci_test/unit_tests/test_unit_layer_convolution_distconv.py
  docs/layers/learning_layers.rst
  docs/quick_start.rst
  model_zoo/tests/model_lenet_mnist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_dist_ckpt.prototext
  model_zoo/tests/model_lenet_mnist_lbann2ckpt.prototext
  python/lbann/modules/base.py
  src/layers/learning/convolution.cpp
  src/layers/learning/deconvolution.cpp
  src/models/unit_test/lenet.prototext.inc
  src/proto/layers.proto
Labels: review requested, refactor

#2117 Move LC paths in PFE
  python/lbann/contrib/lc/paths.py
Labels: review requested

#2119 Get LBANN building with ROCm 5.1
  CMakeLists.txt
  src/utils/rocm.cpp
Labels: bug, review requested, build

#2120 Fix the nasnet integration test. For real this time.
  .gitlab/common/run-catch-tests.sh
  applications/nas/nasnet/cifar_networks.py
  python/lbann/contrib/lc/paths.py
Labels: review requested, CI
