Repository LLNL/lbann, pull requests merged in 2022-08, with the labels that each got.

#2128 Add MIOpen profiler annotations
  include/lbann/utils/dnn_lib/miopen/convolution.hpp
  include/lbann/utils/dnn_lib/miopen/dropout.hpp
  include/lbann/utils/dnn_lib/miopen/local_response_normalization.hpp
  include/lbann/utils/dnn_lib/miopen/pooling.hpp
  include/lbann/utils/dnn_lib/miopen/softmax.hpp
  include/lbann/utils/profiling.hpp
  src/utils/profiling.cpp
Labels: enhancement, review requested

#2132 Enforce consistent GPU targets in spack environment
  applications/ATOM/external_packages_atom.sh
  scripts/build_lbann.sh
Labels: bug

#2137 Add zlib as an explicit CMake dependency.
  CMakeLists.txt
Labels: review requested, build
