Repository LLNL/lbann, pull requests merged in 2022-01, with the labels that each got.

#2026 Make sure sub-graph-specific code is encapsulated in Python submodules
  python/lbann/models/__init__.py
  python/lbann/modules/__init__.py
Labels: bug, review requested, refactor, python

#2024 Match LayerNorm and InstanceNorm layers to PyTorch
  bamboo/unit_tests/test_unit_layer_instance_norm.py
  bamboo/unit_tests/test_unit_layer_layer_norm.py
  src/layers/regularizers/instance_norm.cpp
  src/layers/regularizers/instance_norm.cu
  src/layers/regularizers/layer_norm.cpp
  src/layers/regularizers/layer_norm.cu
Labels: review requested

#2027 Update CMake support for CUDA HPC SDK and HIP
  CMakeLists.txt
  cmake/configure_files/LBANNConfig.cmake.in
  cmake/modules/FindBreathe.cmake
  cmake/modules/FindSphinx.cmake
  cmake/modules/LBANNDebugUtilities.cmake
  cmake/modules/SetupCUDAToolkit.cmake
  cmake/modules/SetupMPI.cmake
  model_zoo/CMakeLists.txt
  src/operators/math/common.cuh
Labels: in progress, build

#2028 Bugfix ci tests
  bamboo/integration_tests/test_integration_atom_wae.py
  bamboo/integration_tests/test_integration_lenet.py
  python/lbann/core/operator_layers.py
Labels: bug

#2029 Fix a logic error in PFE
  python/lbann/core/operator_layers.py
Labels: bug, review requested

#2033 Fix a typo in the documentation preventing a link from rendering correctly,
  docs/continuous_integration.rst
Labels: review requested, documentation

#2035 Bugfix for the checkpoint lenet unit tests
  include/lbann/trainers/trainer.hpp
  src/callbacks/checkpoint.cpp
  src/trainers/trainer.cpp
Labels: bug

#2034 Update license template
  lbann_license_template_cxx.txt
  lbann_license_template_octothorpe.txt
Labels: review requested

#2040 Correct the copy semantics of the argument parser
  include/lbann/utils/argument_parser.hpp
  src/utils/unit_test/argument_parser_test.cpp
Labels: bug, review requested
