Repository LLNL/lbann, pull requests merged in 2022-03, with the labels that each got.

#2072 Fix Cereal error for distributed embedding
  src/layers/misc/cereal_registration/dist_embedding.cpp
Labels: bug, review requested

#2070 Refactor spack Python requirements
  .gitlab-ci.yml
  .gitlab/catalyst/pipeline.yml
  .gitlab/corona/pipeline.yml
  .gitlab/lassen/pipeline.yml
  .gitlab/pascal/pipeline.yml
  .gitlab/ray/pipeline.yml
  ci_test/compiler_tests/test_compiler.py
  scripts/build_lbann.sh
  scripts/common_spack_packages/aux_tools_spack_packages.sh
  scripts/common_spack_packages/ci_spack_packages.sh
  scripts/common_spack_packages/docs_spack_packages.sh
  scripts/customize_build_env.sh
Labels: enhancement

#2069 Training algorithm timers
  include/lbann/callbacks/timeline.hpp
  include/lbann/execution_algorithms/CMakeLists.txt
  include/lbann/execution_algorithms/ltfb.hpp
  include/lbann/execution_algorithms/ltfb/CMakeLists.txt
  include/lbann/execution_algorithms/sgd_training_algorithm.hpp
  include/lbann/execution_algorithms/training_algorithm.hpp
  include/lbann/utils/accumulating_timer.hpp
  include/lbann/utils/cloneable.hpp
  include/lbann/utils/output_helpers.hpp
  include/lbann/utils/running_statistics.hpp
  include/lbann/utils/timer.hpp
  include/lbann/utils/timer_map.hpp
  model_zoo/CMakeLists.txt
  src/callbacks/ltfb.cpp
  src/data_readers/data_reader.cpp
  src/execution_algorithms/kfac.cpp
  src/execution_algorithms/ltfb.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/layers/data_type_layer.cpp
  src/metrics/layer_metric.cpp
  src/proto/training_algorithm.proto
  src/trainers/trainer.cpp
  src/utils/CMakeLists.txt
  src/utils/output_helpers.cpp
  src/utils/timer_map.cpp
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/cloneable_test.cpp
  src/utils/unit_test/output_helpers_test.cpp
  src/utils/unit_test/statistics_test.cpp
  src/utils/unit_test/timer_test.cpp
  unit_test/utilities/TestHelpers.hpp
Labels: enhancement, review requested

#2073 Avoid constructing unnecessary weights in Python modules
  python/lbann/modules/base.py
Labels: review requested, python

#2076 Transformers apply LayerNorm with affine transform
  applications/nlp/transformer/evaluate.py
  python/lbann/models/transformer.py
Labels: review requested, application

#2077 Update release notes
  ReleaseNotes.txt
Labels: review requested, documentation

#2075 Feature add pip deps
  .gitlab/catalyst/pipeline.yml
  applications/ATOM/build_lbann_atom_user.sh
  applications/ATOM/external_packages_atom.sh
  applications/ATOM/requirements.txt
  ci_test/requirements.txt
  cmake/configure_files/setup.py.in
  docs/building_lbann.rst
  docs/quick_start.rst
  docs/running_lbann.rst
  scripts/.build_lbann_as_user.sh
  scripts/build_lbann.sh
  scripts/common_spack_packages/ci_spack_packages.sh
  scripts/customize_build_env.sh
Labels: enhancement

#1980 Move CommunityGAN app to external repo
  applications/graph/communityGAN/.gitignore
  applications/graph/communityGAN/__init__.py
  applications/graph/communityGAN/data/__init__.py
  applications/graph/communityGAN/data/dataset.py
  applications/graph/communityGAN/default.config
  applications/graph/communityGAN/dump_motifs.py
  applications/graph/communityGAN/main.py
  applications/graph/communityGAN/model/__init__.py
  applications/graph/communityGAN/model/discriminator.py
  applications/graph/communityGAN/model/gan.py
  applications/graph/communityGAN/model/generator.py
  applications/graph/communityGAN/util/__init__.py
Labels: review requested, application

#2080 Add a way to specify weekly-ness of testing
  .gitlab-ci.yml
  .gitlab/catalyst/pipeline.yml
  .gitlab/common/run-catch-tests.sh
  .gitlab/corona/pipeline.yml
  .gitlab/lassen/pipeline.yml
  .gitlab/pascal/pipeline.yml
  .gitlab/ray/pipeline.yml
Labels: enhancement, review requested, CI

#2084 Fix Catalyst CI build
  ci_test/integration_tests/test_integration_roberta.py
  ci_test/unit_tests/test_unit_layer_pooling.py
  scripts/customize_build_env.sh
Labels: bug

#2082 Remove DAG model
  include/lbann/execution_algorithms/kfac.hpp
  include/lbann/execution_algorithms/ltfb.hpp
  include/lbann/lbann.hpp
  include/lbann/models/CMakeLists.txt
  include/lbann/models/directed_acyclic_graph.hpp
  include/lbann/models/model.hpp
  src/base.cpp
  src/callbacks/load_model.cpp
  src/callbacks/ltfb.cpp
  src/execution_algorithms/ltfb/checkpoint_binary.cpp
  src/execution_algorithms/ltfb/checkpoint_file.cpp
  src/execution_algorithms/ltfb/random_pairwise_exchange.cpp
  src/execution_algorithms/ltfb/regularized_evolution.cpp
  src/execution_algorithms/ltfb/sendrecv_weights.cpp
  src/execution_algorithms/ltfb/truncation_selection_exchange.cpp
  src/execution_algorithms/unit_test/inference_algorithm_test.cpp
  src/models/CMakeLists.txt
  src/models/directed_acyclic_graph.cpp
  src/models/model.cpp
  src/models/unit_test/model_test.cpp
  src/models/unit_test/modify_test.cpp
  src/proto/factories/model_factory.cpp
  src/utils/lbann_library.cpp
Labels: review requested, refactor

#2078 Fix a warning and cleanup a utility file
  include/lbann/data_readers/data_reader_synthetic.hpp
  include/lbann/layers/regularizers/entrywise_batch_normalization.hpp
  include/lbann/layers/transform/concatenate.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/reshape.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/opencv.hpp
  include/lbann/utils/vision.hpp
  src/data_readers/data_reader_jag_conduit.cpp
  src/data_readers/data_reader_node2vec.cpp
  src/data_readers/data_reader_python.cpp
  src/data_readers/unit_test/data_reader_synthetic_test_public_api.cpp
  src/execution_algorithms/kfac/kfac_block_fc_conv.cpp
  src/layers/layer.cpp
  src/layers/learning/base_convolution.cpp
  src/layers/learning/distconv/distconv_layers.cpp
  src/transforms/repack_HWC_to_CHW_layout.cpp
  src/transforms/vision/adjust_brightness.cpp
  src/transforms/vision/adjust_contrast.cpp
  src/transforms/vision/adjust_saturation.cpp
  src/transforms/vision/center_crop.cpp
  src/transforms/vision/colorize.cpp
  src/transforms/vision/grayscale.cpp
  src/transforms/vision/horizontal_flip.cpp
  src/transforms/vision/normalize_to_lbann_layout.cpp
  src/transforms/vision/random_affine.cpp
  src/transforms/vision/random_crop.cpp
  src/transforms/vision/random_resized_crop.cpp
  src/transforms/vision/random_resized_crop_with_fixed_aspect_ratio.cpp
  src/transforms/vision/resize.cpp
  src/transforms/vision/resized_center_crop.cpp
  src/transforms/vision/to_lbann_layout.cpp
  src/transforms/vision/vertical_flip.cpp
  src/utils/cuda.cu
  src/utils/im2col.cpp
  src/utils/image.cpp
  src/utils/rocm.cpp
  src/utils/summary.cpp
  src/weights/weights.cpp
Labels: review requested, refactor

#2085 Add LBANN_HAS_NVSHMEM to the list of summarized CMake variables
  CMakeLists.txt
Labels: review requested, build

#2087 Move data store exchange to primary thread
  include/lbann/data_readers/data_reader.hpp
  include/lbann/data_store/data_store_conduit.hpp
  src/data_coordinator/buffered_data_coordinator.cpp
  src/data_readers/data_reader.cpp
  src/data_store/data_store_conduit.cpp
Labels: bug

#2088 Reduce LTFB startup overhead and reporting
  include/lbann/execution_algorithms/ltfb/random_pairwise_exchange.hpp
  include/lbann/utils/options.hpp
  src/callbacks/ltfb.cpp
  src/execution_algorithms/ltfb/checkpoint_common.hpp
  src/execution_algorithms/ltfb/random_pairwise_exchange.cpp
  src/proto/proto_common.cpp
  src/utils/lbann_library.cpp
  src/utils/options.cpp
Labels: enhancement

#2092 Fix buffer overflow in SMILES data reader
  include/lbann/data_readers/data_reader_smiles.hpp
  src/data_readers/data_reader_smiles.cpp
Labels: bug

#2090 Added support for the RIKEN data center and associated Fugaku system
  ReleaseNotes.txt
  python/lbann/contrib/launcher.py
  python/lbann/contrib/riken/__init__.py
  python/lbann/contrib/riken/launcher.py
  python/lbann/contrib/riken/systems.py
  python/lbann/launcher/__init__.py
  python/lbann/launcher/pjm.py
Labels: enhancement

#1996 Add onnx lenet layers
  CMakeLists.txt
  ci_test/integration_tests/test_integration_onnx_output.py
  cmake/configure_files/setup.py.in
  cmake/modules/LBANNWritePythonFeatures.cmake
  include/lbann/callbacks/export_onnx.hpp
  include/lbann/layers/activations/softmax.hpp
  include/lbann/layers/learning/convolution.hpp
  include/lbann/layers/learning/fully_connected.hpp
  include/lbann/layers/loss/categorical_accuracy.hpp
  include/lbann/layers/loss/cross_entropy.hpp
  include/lbann/layers/loss/mean_squared_error.hpp
  include/lbann/layers/transform/evaluation.hpp
  include/lbann/layers/transform/pooling.hpp
  include/lbann/layers/transform/split.hpp
  include/lbann/models/model.hpp
  include/lbann/utils/CMakeLists.txt
  include/lbann/utils/onnx_utils.hpp
  include/lbann/utils/tagged_dispatch.hpp
  include/lbann/weights/data_type_weights.hpp
  include/lbann/weights/weights.hpp
  python/lbann/__init__.py
  src/callbacks/export_onnx.cpp
  src/callbacks/unit_test/CMakeLists.txt
  src/layers/io/input_layer.cpp
  src/layers/layer.cpp
  src/layers/learning/convolution.cpp
  src/layers/learning/fully_connected.cpp
  src/models/model.cpp
  src/proto/callbacks.proto
  src/utils/unit_test/CMakeLists.txt
  src/utils/unit_test/onnx_utils_test.cpp
  src/weights/data_type_weights.cpp
Labels: review requested

#2093 Protect an onnx include in LBANN_HAS_ONNX
  include/lbann/models/model.hpp
Labels: bug, review requested
