Repository LLNL/lbann, pull requests merged in 2023-09, with the labels that each got.

#2315 Move some annotations for Caliper around
  include/lbann/optimizers/data_type_optimizer_impl.hpp
  include/lbann/utils/exception.hpp
  include/lbann/utils/options.hpp
  include/lbann/utils/profiling.hpp
  python/lbann/contrib/args.py
  src/base.cpp
  src/callbacks/profiler.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
  src/models/model.cpp
  src/proto/proto_common.cpp
  src/utils/options.cpp
  src/utils/profiling.cpp
Labels: review requested

#2317 Use Caliper's default-generated output name
  src/utils/options.cpp
Labels: enhancement

#2318 Update the event creation flags under HIP
  src/utils/rocm.cpp
Labels: enhancement, review requested

#2322 Clean up Caliper annotations and Adiak data
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/layers/data_type_layer.cpp
  src/layers/layer.cpp
Labels: enhancement, review requested

#2325 Fixed multiple bugs in data store
  include/lbann/data_store/data_store_conduit.hpp
  src/data_store/data_store_conduit.cpp
Labels: bug

#2331 Some mild clean up
  include/lbann/layers/data_type_layer.hpp
  src/layers/data_type_layer.cpp
  src/models/model.cpp
Labels: enhancement, review requested
