Repository LLNL/lbann, pull requests merged in 2023-03, with the labels that each got.

#2214 Use Aluminum's NCCLBackend instead of HostTransferBackend
  include/lbann/utils/distconv.hpp
  src/utils/distconv.cpp
Labels: review requested

#2222 Skip dft_abs and gru tests when not supported by the build
  ci_test/unit_tests/test_unit_layer_dft_abs.py
  ci_test/unit_tests/test_unit_layer_gru.py
Labels: review requested, CI

#2224 Bugfix ci and spack
  scripts/build_lbann.sh
  scripts/customize_build_env.sh
Labels: enhancement

#2226 Help crashing LBANN jobs die completely under flux.
  python/lbann/launcher/flux.py
Labels: python

#2233 Fixed KFAC conv unit test
  ci_test/unit_tests/test_unit_algo_kfac_conv.py
Labels: review requested, CI

#2241 Fix an issue in which makefile wouldn't create needed directories
  src/proto/CMakeLists.txt
Labels: bug, review requested
