Repository LLNL/lbann, pull requests merged in 2023-06, with the labels that each got.

#2270 Fix get_distconv_environment
  ci_test/common_python/tools.py
  ci_test/unit_tests/test_unit_layer_gather_distconv.py
  ci_test/unit_tests/test_unit_layer_scatter_distconv.py
  python/lbann/contrib/args.py
Labels: bug

#2272 Fix an issue with cuTT/hipTT not behaving correctly in inverse_permute
  src/layers/transform/permute/cutt_permuteimpl.hpp
Labels: bug, review requested

#2266 Remove the ROCm prefix from the implicit directories
  CMakeLists.txt
Labels: review requested, build, CI

#2273 Memoize cuTT/hipTT plans again
  src/layers/transform/permute/cutt_permuteimpl.hpp
Labels: enhancement, review requested

#2282 Update Python front-end LC system parameters
  python/lbann/contrib/lc/systems.py
Labels: enhancement, review requested, python

#2283 Bugfix channelwise softmax
  include/lbann/layers/misc/channelwise_softmax.hpp
  include/lbann/layers/misc/channelwise_softmax_impl.hpp
  src/layers/misc/channelwise_softmax.cpp
  src/layers/misc/channelwise_softmax.cu
Labels: bug
