Repository LLNL/lbann, pull requests merged in 2023-12, with the labels that each got.

#2395 Fix gradient clipping with half
  src/callbacks/gradient_clipping.cpp
Labels: bug

#2396 Fixes for half and CUDA 12.2
  include/lbann/layers/regularizers/local_response_normalization.hpp
  src/callbacks/gradient_clipping.cpp
  src/optimizers/adam.cpp
Labels: bug

#2382 Remove unused drivers
  CMakeLists.txt
  model_zoo/CMakeLists.txt
  model_zoo/lbann_aecycgan.cpp
  model_zoo/lbann_cycgan.cpp
  model_zoo/lbann_gan.cpp
  model_zoo/lbann_inf.cpp
  src/drivers/CMakeLists.txt
  src/drivers/lbann.cpp
  src/drivers/lbann_help.cpp
Labels: review requested

#2401 Force convolutions to be deterministic when LBANN_DETERMINISTIC
  src/utils/miopen.cpp
Labels: enhancement, review requested
