Repository LLNL/lbann, pull requests merged in 2023-04, with the labels that each got.

#2246 Expose height, width, channel, and filter groups to Cosmoflow CLI
  applications/physics/cosmology/cosmoflow/train_cosmoflow.py
Labels: review requested, application

#2250 Synthetic ImageNet support in ResNet/AlexNet
  applications/vision/alexnet.py
  applications/vision/data/imagenet/__init__.py
  applications/vision/data/imagenet/data_reader_synthetic.prototext
  applications/vision/resnet.py
Labels: enhancement

#2252 Fix error in NASNet integration test
  ci_test/integration_tests/test_integration_nasnet.py
Labels: bug, CI

#2253 Stop passing output/error redirection to flux
  python/lbann/launcher/flux.py
Labels: python

#2256 Fix bug in back-prop
  src/layers/misc/dft_abs.cpp
Labels: bug

#2259 Correct a check for subgraph parallelism
  ci_test/unit_tests/test_unit_subgrid_concat.py
  ci_test/unit_tests/test_unit_subgrid_cross_grid_sum.py
  ci_test/unit_tests/test_unit_subgrid_slice.py
  ci_test/unit_tests/test_unit_subgrid_split.py
  ci_test/unit_tests/test_unit_subgrid_sum.py
  src/models/model.cpp
Labels: bug, review requested

#2258 Always enable the check for distconv
  include/lbann/layers/layer.hpp
Labels: enhancement
