Repository LLNL/lbann, pull requests merged in 2023-10, with the labels that each got.

#2340 Fix an error in buffer views
  include/lbann/layers/transform/stop_gradient.hpp
Labels: bug, review requested

#2341 Cleanup warnings
  .gitlab/corona/pipeline.yml
  .gitlab/lassen/multi_stage_pipeline.yml
  .gitlab/pascal/pipeline.yml
  .gitlab/pascal/pipeline_compiler_tests.yml
  .gitlab/tioga/pipeline.yml
  ci_test/compiler_tests/test_compiler.py
  include/lbann/layers/misc/rowwise_weights_norms_impl.hpp
  include/lbann/layers/transform/crop.hpp
  include/lbann/layers/transform/cross_grid_sum.hpp
  include/lbann/layers/transform/cross_grid_sum_slice.hpp
  scripts/build_lbann.sh
  src/comm.cpp
  src/data_coordinator/unit_test/data_coordinator_HDF5_hrrl_public_api.cpp
  src/data_readers/data_reader_hdf5_legacy.cpp
  src/execution_algorithms/kfac/kfac_util.cpp
  src/execution_algorithms/sgd_training_algorithm.cpp
  src/layers/image/image_layer_builders.cpp
  src/layers/regularizers/layer_norm_builder.cpp
  src/layers/transform/permute/cutensor_permuteimpl.hpp
  src/layers/transform/permute/cutensor_support.hpp
  src/layers/transform/permute/cutt_permuteimpl.hpp
  src/layers/transform/permute/tensor_dims_utils.hpp
  src/layers/transform/unit_test/cutensor_permute_test.cpp
  src/layers/transform/unit_test/cutt_permute_test.cpp
  src/layers/transform/unit_test/tensor_dims_utils_test.cpp
  src/utils/python.cpp
  src/utils/rocm.cpp
  unit_test/CMakeLists.txt
Labels: bug, review requested

#2339 Reorganize Layer API
  include/lbann/layers/layer.hpp
  src/callbacks/check_dataset.cpp
  src/layers/layer.cpp
  src/models/unit_test/modify_test.cpp
Labels: review requested, refactor

#2349 Fix debugging check in cross-entropy
  src/layers/loss/cross_entropy.cpp
Labels: enhancement

#2350 Add datatype to weights description
  include/lbann/weights/data_type_weights.hpp
  include/lbann/weights/weights.hpp
  src/weights/weights.cpp
Labels: enhancement

#2351 Move check for layer construction failure before first use
  src/proto/factories/layer_graph_factory.cpp
Labels: bug

#2354 Make LBANN_ASSERT safer to use
  include/lbann/utils/exception.hpp
Labels: bug

#2357 Fix a warning about an unreachable loop
  include/lbann/execution_algorithms/kfac/kfac_block_gru.hpp
Labels: bug, review requested, build

#2346 Implement Model-Parallelism for Channelwise Fully Connected
  applications/nlp/transformer/modeling.py
  ci_test/unit_tests/test_unit_layer_channelwise_fully_connected_mp.py
  include/lbann/layers/learning/channelwise_fully_connected.hpp
  src/layers/learning/channelwise_fully_connected.cpp
Labels: CI

#2366 Fix FP16 support on ROCm platforms
  include/lbann/layers/regularizers/local_response_normalization.hpp
  include/lbann/layers/transform/constant.hpp
  include/lbann/utils/impl/cuda.hpp
  include/lbann/utils/impl/rocm.hpp
  src/layers/regularizers/selu_dropout.cpp
  src/layers/transform/reduction.cpp
  src/layers/transform/uniform.cpp
  src/optimizers/adam.cpp
  src/weights/initializer.cpp
Labels: bug, review requested

#2365 Fix --setup-only with pretrain_gpt
  applications/nlp/transformer/pretrain_gpt.py
  applications/nlp/transformer/trainer.py
Labels: bug
