Repository LLNL/lbann, pull requests merged in 2023-01, with the labels that each got.

#2157 Add alternating optimizer updates
  ReleaseNotes.txt
  applications/gan/README.md
  applications/gan/image/gan_model.py
  applications/gan/image/generate_samps.py
  applications/gan/image/image_dataset.py
  applications/gan/image/train_gan.py
  applications/gan/mnist/gan_model.py
  applications/gan/mnist/generate_samps.py
  applications/gan/mnist/mnist_dataset.py
  applications/gan/mnist/train_gan.py
  ci_test/integration_tests/test_integration_mnist_gan.py
  docs/callbacks.rst
  docs/layers/transform_layers.rst
  include/lbann/callbacks/CMakeLists.txt
  include/lbann/callbacks/alternate_updates.hpp
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/identity_zero.hpp
  include/lbann/layers/transform/transform_builders.hpp
  include/lbann/lbann.hpp
  src/base.cpp
  src/callbacks/CMakeLists.txt
  src/callbacks/alternate_updates.cpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/cereal_registration/CMakeLists.txt
  src/layers/transform/cereal_registration/identity_zero.cpp
  src/layers/transform/identity_zero.cpp
  src/proto/callbacks.proto
  src/proto/factories/callback_factory.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, in progress

#2166 Fixed a bug in the GPU-based computation of the batchnorm statistics
  src/layers/regularizers/batch_normalization.cu
Labels: bug

#2002 Remove deprecated Python scripts for ONNX conversion and plotting
  cmake/configure_files/setup.py.in
  python/.gitignore
  python/docs/onnx/README.md
  python/docs/onnx/l2o.md
  python/docs/onnx/o2l.md
  python/docs/onnx/support_status.md
  python/docs/onnx/viz/l2o/alexnet/alexnet_lbann.pdf
  python/docs/onnx/viz/l2o/alexnet/alexnet_lbann.png
  python/docs/onnx/viz/l2o/alexnet/alexnet_onnx_netron.png
  python/docs/onnx/viz/l2o/mnist/mnist_lbann.pdf
  python/docs/onnx/viz/l2o/mnist/mnist_lbann.png
  python/docs/onnx/viz/l2o/mnist/mnist_onnx_netron.png
  python/docs/onnx/viz/l2o/mnist/mnist_onnx_netron_name.png
  python/docs/onnx/viz/l2o/resnet50/resnet50_lbann.pdf
  python/docs/onnx/viz/l2o/resnet50/resnet50_lbann.png
  python/docs/onnx/viz/l2o/resnet50/resnet50_onnx_netron.png
  python/docs/plot/README.md
  python/examples/onnx/lbann2onnx.py
  python/examples/onnx/onnx2lbann.py
  python/examples/plot/data/fmow_final_sgd_1e-3_1node.out
  python/examples/plot/data/fmow_res_sgd_1e-3_1gpu.2.out
  python/examples/plot/data/fmow_res_sgd_1e-3_1gpu.out
  python/examples/plot/data/fmow_res_sgd_1e-3_proc_1gpu.out
  python/examples/plot/data/fmow_res_sgd_1e-3_proc_1node.out
  python/examples/plot/data/pascal_2_stats_res_sgd.json
  python/examples/plot/data/pascal_2_stats_sgd.json
  python/examples/plot/data/pascal_res_sgd_1e-3_1gpu.json
  python/examples/plot/data/pascal_res_sgd_1e-3_orig_1node.json
  python/examples/plot/data/pascal_res_sgd_1e-3_proc_1gpu.json
  python/examples/plot/data/pascal_res_sgd_1e-3_proc_1node.json
  python/examples/plot/test.sh
  python/lbann/onnx/__init__.py
  python/lbann/onnx/l2o/__init__.py
  python/lbann/onnx/l2o/layers/__init__.py
  python/lbann/onnx/l2o/layers/learnings.py
  python/lbann/onnx/l2o/layers/losses.py
  python/lbann/onnx/l2o/layers/math.py
  python/lbann/onnx/l2o/layers/regularizers.py
  python/lbann/onnx/l2o/layers/transforms.py
  python/lbann/onnx/l2o/util.py
  python/lbann/onnx/o2l/__init__.py
  python/lbann/onnx/o2l/layers/__init__.py
  python/lbann/onnx/o2l/layers/learnings.py
  python/lbann/onnx/o2l/layers/math.py
  python/lbann/onnx/o2l/layers/regularizers.py
  python/lbann/onnx/o2l/layers/transforms.py
  python/lbann/onnx/parserDescriptor.py
  python/lbann/onnx/tests/__init__.py
  python/lbann/onnx/tests/lbann2onnx_layer_test.py
  python/lbann/onnx/tests/lbann2onnx_test.py
  python/lbann/onnx/tests/onnx2lbann_layer_test.py
  python/lbann/onnx/tests/onnx2lbann_test.py
  python/lbann/onnx/tests/util.py
  python/lbann/onnx/util.py
  python/lbann/plot/__init__.py
  python/lbann/plot/parser.py
  python/lbann/plot/plot.py
  python/scripts/onnx/create_support_status.py
  python/scripts/onnx/download_onnx_model_zoo.sh
  python/scripts/plot/lbplot
Labels: bug, review requested, refactor

#2071 Move python docstrings to rst files
  docs/execution_algorithms.rst
  docs/execution_algorithms/batched_iterative_optimization.rst
  docs/execution_algorithms/kfac.rst
  docs/execution_algorithms/ltfb.rst
  docs/sphinx_requirements.txt
Labels: review requested, documentation

#2172 Update distconv_matmul.hpp
  include/lbann/layers/math/distconv/distconv_matmul.hpp
Labels: bug, review requested

#2175 Fix include path and remove Python.h inclusion from headers
  include/lbann/utils/python.hpp
  include/lbann/utils/tensor.hpp
  src/data_readers/data_reader_python.cpp
  src/utils/python.cpp
Labels: review requested, refactor

#2181 Fix a compiler warning message in a unit test.
  src/utils/unit_test/protobuf_utils_test.cpp
Labels: review requested, build
