Repository LLNL/lbann, pull requests merged in 2024-06, with the labels that each got.

#2459 Fix a couple issues with the auto-detection of the NVCC_GENCODE in NCCL
  scripts/superbuild/nccl/CMakeLists.txt
Labels: bug, build

#2248 Add support for changing distconv overlaps in Identity layer.
  ci_test/unit_tests/test_unit_layer_identity_overlap_change_distconv.py
  include/lbann/layers/activations/identity.hpp
  include/lbann/layers/distconv_adapter.hpp
  include/lbann/utils/dnn_lib/cudnn/transform_tensor.hpp
  include/lbann/utils/dnn_lib/miopen/transform_tensor.hpp
  include/lbann/utils/dnn_lib/transform_tensor.hpp
  src/layers/activations/identity.cpp
  src/layers/distconv_adapter.cpp
Labels: enhancement

#2255 Add Upsample Layer
  ci_test/common_python/tools.py
  ci_test/unit_tests/test_unit_layer_upsample.py
  ci_test/unit_tests/test_unit_layer_upsample_distconv.py
  include/lbann/layers/transform/CMakeLists.txt
  include/lbann/layers/transform/transform_builders.hpp
  include/lbann/layers/transform/upsample.hpp
  include/lbann/lbann.hpp
  include/lbann/utils/dnn_lib/cudnn/upsample.hpp
  include/lbann/utils/dnn_lib/miopen/upsample.hpp
  include/lbann/utils/dnn_lib/upsample.hpp
  src/base.cpp
  src/layers/transform/CMakeLists.txt
  src/layers/transform/cereal_registration/CMakeLists.txt
  src/layers/transform/cereal_registration/upsample.cpp
  src/layers/transform/upsample.cpp
  src/proto/factories/layer_factory.cpp
  src/proto/layers.proto
Labels: enhancement, in progress
