Repository LLNL/lbann, pull requests merged in 2024-01, with the labels that each got.

#2415 Fix compiler warning
  include/lbann/layers/regularizers/layer_norm.hpp
Labels: review requested, CI

#2405 Cleanup data ingestion types
  include/lbann/callbacks/variable_minibatch.hpp
  include/lbann/data_ingestion/data_store_conduit.hpp
  src/callbacks/variable_minibatch.cpp
  src/data_ingestion/coordinator/buffered_data_coordinator.cpp
  src/data_ingestion/data_store_conduit.cpp
Labels: bug

#2421 Restore the superbuild
  scripts/superbuild/CMakeLists.txt
  scripts/superbuild/README.md
  scripts/superbuild/adiak/CMakeLists.txt
  scripts/superbuild/aluminum/CMakeLists.txt
  scripts/superbuild/caliper/CMakeLists.txt
  scripts/superbuild/catch2/CMakeLists.txt
  scripts/superbuild/cereal/CMakeLists.txt
  scripts/superbuild/clara/CMakeLists.txt
  scripts/superbuild/cmake/modules/LBANNSuperBuildAddCMakeExternPkg.cmake
  scripts/superbuild/cmake/modules/LBANNSuperBuildAddPackages.cmake
  scripts/superbuild/cmake/modules/LBANNSuperBuildCreateCMakeArguments.cmake
  scripts/superbuild/cmake/modules/LBANNSuperBuildInitExternPkg.cmake
  scripts/superbuild/cnpy/CMakeLists.txt
  scripts/superbuild/conduit/CMakeLists.txt
  scripts/superbuild/dihydrogen/CMakeLists.txt
  scripts/superbuild/examples/cuda-distconv.sh
  scripts/superbuild/examples/rocm-distconv.sh
  scripts/superbuild/hdf5/CMakeLists.txt
  scripts/superbuild/hydrogen/CMakeLists.txt
  scripts/superbuild/jpeg-turbo/CMakeLists.txt
  scripts/superbuild/lbann/CMakeLists.txt
  scripts/superbuild/openblas/CMakeLists.txt
  scripts/superbuild/opencv/AddOpenCVOptions.cmake
  scripts/superbuild/opencv/CMakeLists.txt
  scripts/superbuild/protobuf/CMakeLists.txt
  scripts/superbuild/rccl/CMakeLists.txt
  scripts/superbuild/spdlog/CMakeLists.txt
  scripts/superbuild/zstr/CMakeLists.txt
Labels: build
